### ISSUE TITLE
How to implement bi-directional RNN/LSTM with Neon?

### ISSUE THREAD

**Issue by buriy** [NervanaSystems/neon#102]
How to implement bi-directional RNN/LSTM with Neon?

**Comment by yinyinl** [comment]
If you look at the RNN/LSTM implementation, you can see internal buffers to store activations for each time step of the sequence. You can follow the same design, but allocate separate buffers for forward passing the sequence and backward passing the sequence. 
We are working on and planning to add that feature to neon in the near future. Stay tuned.
