### ISSUE TITLE
Accessing Tensor results

### ISSUE THREAD

**Issue by tambetm** [NervanaSystems/neon#104]
I'm just recording this here, maybe somebody else struggles with it too. There is slight disparity in tensor indexing: `tensor[0,0]` returns another tensor, which is view to the original tensor and must be converted to numpy array to access the value, for example `tensor[0,0].asnumpyarray()`. On the other hand `tensor[0,0] = 1` works as expected and doesn't need any additional steps. My impression is, that for smallish matrices `tensor[0,0].asnumpyarray()` is actually slower than `tensor.asnumpyarray()[0,0]`, because it has to allocate another tensor. Am I correct?

**Comment by apark263** [comment]
Yes
