### ISSUE TITLE
Use Model without DataIterator

### ISSUE THREAD

**Issue by tambetm** [NervanaSystems/neon#105]
If you want to do wihout `DataIterator` and use `Model.fprop()`/`Model.bprop()` directly, then there is no obvious way to apply optimizer to the model - `Optimizer.optimize()` method takes `layer_list` as argument, but if you use the same layers list that you used to create `Model`, the code will give an error:
```
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    optimizer.optimize(layers, 1)
  File "/home/tambet/neon_new/neon/optimizers/optimizer.py", line 194, in optimize
    param_list = get_param_list(layer_list)
  File "/home/tambet/neon_new/neon/optimizers/optimizer.py", line 26, in get_param_list
    ptuple = l.get_params()
AttributeError: 'Conv' object has no attribute 'get_params'
```

I ended up copying these lines from `Model` constructor:
```
for layer in layers:
    if isinstance(layer, list):
        self.layers.extend(layer)
    else:
        self.layers.append(layer)

for layer in self.layers:
    if layer.has_params:
        self.layers_to_optimize.append(layer)

    elif isinstance(layer, Merge):
        self.layers_to_optimize += layer.layers_to_optimize
```

I would like to see those included in `Optimizer.optimize()`, so that I could give `Model` to it as first parameter. Alternatively there could be new method `Model.apply(Optimizer, epoch)`.

**Comment by apark263** [comment]
You can pass  models.layers_to_optimize to the optimizers instead of using the original layers list.

**Comment by tambetm** [comment]
Thanks, that was easy. I was used to thinking, that layers_to_optimize is somehow "private" to Model.
