### ISSUE TITLE
MultiCore CPU support

### ISSUE THREAD

**Issue by closedLoop** [NervanaSystems/neon#107]
The documentation for `gen_backend`  states that if `backend='cpu'` then it will create a single CPU core, float 32 backend.

* Is this a feature that is on the roadmap?
* Is this already implemented and this is just a documentation issue?

I see that Multi GPU support is coming soon (if you set  `backend='mgpu'`).   Does the implementation of this lend to an easier implementation of MultiCPU support?

**Comment by apark263** [comment]
>The documentation for gen_backend states that if backend='cpu' then it will create a single CPU core, float 32 backend.
> - Is this a feature that is on the roadmap?

yes, we support single cpu backend

> - Is this already implemented and this is just a documentation issue?

it's implemented and should be documented

> I see that Multi GPU support is coming soon (if you set backend='mgpu'). Does the implementation of this lend to an easier implementation of MultiCPU support?

MultiCPU and MultiGPU would be very different implementation-wise and one would not make the other any easier.  We currently have no plans to implement a MultiCPU backend, and even if we did, it would still lag single GPU by a very wide margin.   If you are interested in faster performance, my recommendation would be to try using the GPU backend.
