### ISSUE TITLE
Shape parameters missing in CPUTensor

### ISSUE THREAD

**Issue by Bam4d** [NervanaSystems/neon#109]
Suppose I want to save the intermediate states of a custom shaped network.

I want to save the state of the hidden layers in a flattened array in sequence (for GPU efficiency)
```hiddens = be.zeros([nodeCount, recurrentHidden.layers[0].nout])```

I then want to forward propagate and then add the values to this vector contiguously
```hiddens[0] = recurrentHidden.fprop(some value)```

Then I want to pass this to a new layer later on
```prediction = recurrentPrediction.fprop(hiddens[0])```

Here lies my issue...
The shape of hiddens[0] is ```(1,)``` (missing the second dimension)

which causes the following error:
```
File "/usr/local/lib/python2.7/dist-packages/neon/layers/layer.py", line 409, in init_buffers
    if inputs.shape[1] == self.be.bsz:
IndexError: tuple index out of range

##N.B my batch size is 1 as i'm overridding the training loop to hopefully build Recursive neural nets http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.383.1327&rep=rep1&type=pdf 
```

My current workaround is to set the 3rd value in be.zeros to 1 i.e.
```hiddens = be.zeros([nodeCount, recurrentHidden.layers[0].nout, 1])```

Should this not be implicit when indexing a Tensor hiddens[0], is there a reason why it does not default to 1?

**Comment by scttl** [comment]
I believe this issue has been addressed in commit @1f4c906f which was pushed with v1.1.0 a couple of weeks ago.  Can you try again and let us know if you're still seeing the same problem?
