### ISSUE TITLE
Recurrent benchmarks / Embeddings kernel?

### ISSUE THREAD

**Issue by an-kumar** [NervanaSystems/neon#110]
The convolutional network benchmarks are impressive. Most recurrent networks spend most of their computation in blas calls, and since neon has custom blas kernels, I was wondering if recurrent networks would be much faster too (than, say, torch). Do you guys have any benchmarking done on recurrent networks?

Also, I noticed there is no layer for an embeddings matrix (so, for example, the text examples you guys use actually use a Linear matrix with a one-hot vector). Some other deep learning frameworks (e.g torch) have a specific kernel for "embeddings", i.e, just indexing into a matrix rather than taking the dot product with a one-hot vector. My guess would be that it is faster, is this the case? and if so, are there any plans to make this? see: https://github.com/torch/cunn/blob/master/LookupTable.cu for torch's kernel.

**Comment by scott-gray** [comment]
In raw benchmarks our gemm kernels are definitely faster than cublas.  This is particularly true for small minibatches (32,64,96) or in fp16 where the speedup can be 2-3x over cublas.  I have not yet had a chance to profile our RNN code to make sure we're compounding all the operations we can be, but I do plan to do that soon.  Having your own gemm kernels offers interesting additional compounding opportunities not available when using a closed source library.  For example I was recently able to compound the mean component of batch norm inside the convolution kernels at no additional cost.  I'll be adding that code to the gemm kernels soon.  Or I could add a bias and/or perform various activations (relu is already supported).

I'll let the RNN experts here speak to the point on embeddings.  I will say that our backend supports numpy style fancy indexing and take operations which sounds similar to what you want.  But if there's some missing functionality that can speed these networks up it's a safe bet that we'll make the time to add it.

**Comment by yinyinl** [comment]
We are working on adding embedding layers and it does take advantage the numpy style fancy indexing supported in our backend. Some other optimizations will also be used for speedup. Comparing to one-hots, it also makes the word embedding scale better for larger dataset. Such layer will be added into neon soon.

**Comment by scott-gray** [comment]
Here's a great post from Erich at Baidu reviewing performance optimizations for RNNs.  He also has lots of benchmarks comparing my gemm kernels to cublas:

http://svail.github.io/

**Comment by petrux** [comment]
@yinyinl glad to ear that the embedding layer is coming soon. So, right now, the only way is to use a one-hot multiplied for the embedding matrix which is the weight matrix of a linear layer, right?

**Comment by yinyinl** [comment]
Yes.

**Comment by petrux** [comment]
Thanks. Actually I am experiencing some issues. For instance: is there any way to generate variable length output using a recurrent model? It doesn't seems so...

P.S. is there a neon user mailing list to ask such question? ok, too many questions here... :-)

**Comment by yinyinl** [comment]
We don't have off the shelf support to do layer padding for variable length or EOS symbol detection to stop generating outputs yet. 
We have a neon-users google group for questions or discussions like this:
https://groups.google.com/forum/?hl=en#!forum/neon-users

**Comment by petrux** [comment]
Great. Thanks!!!

**Comment by scttl** [comment]
Closing this as we now have embedding matrix support via our `LookupTable` layer, pushed as part of v1.1.0, and Scott pointed you at some RNN related benchmarks from the folks at Baidu.  As of v1.1.1 we've also got benchmark functionality baked into the Model class, so you can play around with that to get additional timings.
