### ISSUE TITLE
Bug in bprop?

### ISSUE THREAD

**Issue by theormech** [NervanaSystems/neon#111]
It seems to be a bug in nervanacpu backend in bprop_conv function line 1012:

```python
                    array_grad_I[:, m, h, w, :] = alpha * \
                        np.dot(slicedF.T, slicedE)
```

It should be `array_grad_I[:, d, h, w, :] = ...`, I suppose.

**Comment by ursk** [comment]
Thanks for finding this bug. We have confirmed that your suggested fix is correct, and will include it in the next update.
