### ISSUE TITLE
Macro batch data from data source

### ISSUE THREAD

**Issue by courageon** [NervanaSystems/neon#115]
Would it be possible to macro batch data in the new neon? That is, a dataset is larger that what you can fit into system memory, so you chunk-load it from disk one "macro batch" at a time. You had a similar feature in the old version dealing specifically with images. I was able to glean from that a way to implement a slightly different version to suit my dataset. Now that neon has changed, would it be possible/feasible/efficient enough to implement a data iterator that had a callback to ask for more data at the end of a "macro batch" set of data? This way we can pull a potentially endless supply of training data?

**Comment by scttl** [comment]
Hi,  Just to give you a long overdue update on this.  We're in the process of revamping data loading at the moment (including new macro batch support), and expect to push these changes publicly with the next neon release (v1.2.0).  This should happen around the beginning of December.

**Comment by tmbo** [comment]
@scottl Thats great! I am looking forward to that as well (just had a look to see if I can implement a DataIterator on my own that does that, but unfortunately one needs to provide `dataset.nbatches` which is not possible in my case). 

How is the process on this one, are you still on track for beginning of December?

**Comment by scttl** [comment]
We pushed an updated data loader library (see the stuff in `neon/data/loader` along with our `ImageLoader` implementation in `neon/data/imageloader.py`) as part of the v1.1.2 release.  The data loader code allows you to ingest macro batches of data from disk in an efficient (multi-threaded and pipelined) manner and avoids the in-memory only limitations of `DataIterator`.  You can use `neon.util.batch_writer.BatchWriter` to prepare the macro batches, and `examples/alexnet.py` shows it in action.

We're still enhancing the macro batch format to make it more easily amenable to other data formats, but that should provide an initial starting point if you wanted to play around.  Unfortunately we're still somewhat tied into having to pre-specify the total number of batches in the dataset at this time but are thinking about ways to remove that.

**Comment by scttl** [comment]
Our updated macrobatch format is now available in v1.2.0 as of 6bf4891

You can find a tutorial on using it in the [documentation](http://neon.nervanasys.com/docs/latest/introductory_resources.html#using-the-imageloader-module)
