### ISSUE TITLE
Virtualenv based Install Error- make: *** [.venv/bin/activate] Error 127

### ISSUE THREAD

**Issue by shivshil** [NervanaSystems/neon#118]
S:~ s$ git clone https://github.com/NervanaSystems/neon.git
fatal: destination path 'neon' already exists and is not an empty directory.
S:~ s$ cd neon
S:neon s$ make
Updating virtualenv dependencies in: .venv...
/bin/sh: virtualenv: command not found
make: *** [.venv/bin/activate] Error 127

What am I doing wrong? Here are computer specs:

Graphics: NVIDIA GeForce GTX 675MX 1024 MB
iMac (27-inch, Late 2012)
Processor: 3.2 GHz Intel Core i5
Memory: 20 GB 1333 MHz DDR3

Appreciate your help. 

-MachingLearningNewb

**Comment by ursk** [comment]
Looks like you may not have `virtualenv` installed on your machine. Have a look at http://neon.nervanasys.com/docs/latest/user_guide.html#installation for requirements that need to be satisfied before you can run `make`. 
Also note that with your hardware (GeForce GTX 675MX), you will not be able to use the GPU and you will be limited to the CPU backend.

**Comment by shivshil** [comment]
Thanks, overlooked that section. Understood.
