### ISSUE TITLE
Issue with C_interface testing for sgemm/hgemm

### ISSUE THREAD

**Issue by SudoNohup** [NervanaSystems/neon#119]
I follow Scott Gray's guide, run "make_kernel.py" in "neon/tree/master/neon/backends" and build the "cubin" files in "neon/tree/master/neon/backends/kernels/cubin" folder successfully (after installing necessary dependencies like pyCuda). Then I try to do the test with the code in "neon/neon/backends/kernels/C_interface". I compile the code with "make", and I get "libnervana.a" and "./test" executable file.
However, when I run "./test", it shows that "Mismatch at XX" error for "sgemm_nn" routine (The result is not correct..), and it shows "Error launching kernel sgemm_nt_128x128 700" error for "sgemm_nt"/"sgemm_tn" routine.
I run my test on a GeForce GTX 750 Ti (GM107) GPU. So it matches with the compile flag "-arch sm_50" in "make_kernel.py".

**Comment by scttl** [comment]
Closing as #120 is now in master
