### ISSUE TITLE
Data augmentation for images

### ISSUE THREAD

**Issue by scttl** [NervanaSystems/neon#12]
Add image transformations (rotation, cropping, scaling etc.) to the ImageSet loading pipeline.

**Comment by seba-1511** [comment]
Would this be continuous augmentation (every batch is augmented differently) or fixed augmentation (the images are all transformed before fitting) ?

**Comment by apark263** [comment]
This would be continuous augmentation, the same way they are currently
flipped and shifted within the larger image, but with more exotic
transforms.

**Comment by sihyun0826** [comment]
I found out that color jittering is not implemented yet, so the performance of original Alexnet couldn't be reproduced. It would be nice if we can use color augmentation!

**Comment by apark263** [comment]
Color noise along with additional brightness/contrast adjustment will be added to the augmentation pipeline.
