### ISSUE TITLE
Does current version support pre-Maxwell GPUs?

### ISSUE THREAD

**Issue by Jokeren** [NervanaSystems/neon#121]
I have noticed some issues discussing support for pre-Maxwell GPUs. However, I check it on my k20 machine, and find that **neon** cannot run on gpu backend.

`Device 0 does not have CUDA compute capability 5.0 or greater`

**Comment by nervanasys** [comment]
Kepler support is WIP

**Comment by ursk** [comment]
Just for context, Kepler generation cards are now a couple of years behind current technology and we recently dropped support in neon. While we are planning to add support for these GPUs again in the future, the performance of a top of the line Kepler card will only be about that of a $200 GTX960 Maxwell card, which has enough memory to support most current models. If you do not have access to a machine with a current generation Maxwell GPU (e.g. GTX960, GTX980, Titan X), we recommend running on the CPU backend. Older versions of neon (e.g. 0.8.2) did support Kepler GPUs, but there have been significant API changes in neon so we do not recommend using this older version.
