### ISSUE TITLE
set callback args without command-line parse

### ISSUE THREAD

**Issue by NeuroCampos** [NervanaSystems/neon#128]
I am trying to run a model using an ipython notebook, which means that I am not using command-line arguments.  It seems like this kind of thing:

callbacks = Callbacks(model, train_set, output_file="./data.h5")

does not work anymore, because Callbacks is expecting "parsed_args" instead things like "output_file".
Is there a good way to make statements like the above work again?

source: http://neon.nervanasys.com/docs/latest/callbacks.html

Thanks!

**Comment by pcallier** [comment]
I'll second this. Relatedly, using the NeonArgparser is unnecessarily cumbersome for many applications, especially to salvage existing code that didn't use cmd line arguments. Would one way to address this be to open up the NeonArgparser interface to inputs from within the program in addition to sys.argv or config files?

**Comment by scttl** [comment]
Hi guys,

We now have an internal patch that should restore the individual named arguments for Callbacks. We should be pushing that publicly in the next few days. 

-Scott

**Comment by scttl** [comment]
Closing as this behavior has been restored as of commit 41428445
