### ISSUE TITLE
BatchNorm stopped working - please provide example model with BatchNorm

### ISSUE THREAD

**Issue by NeuroCampos** [NervanaSystems/neon#129]
An example model that uses BatchNorm would be helpful.

Before the latest release, this used to work:

layers.append(Conv((3,1,4), init=init1, bias=Constant(0), activation=Rectlin()))
layers.append(BatchNorm(rho=0.99, eps=1e-06))
(note that I have 1-D data, so the second argument of fshape for Conv is 1)

but now I get this error:

neon/layers/layer.py", line 1087, in allocate
    if self.prev_layer is None or self.prev_layer.batch_sum is None:
AttributeError: 'Activation' object has no attribute 'batch_sum'

based on layer.py line 749, I tried...

layers.append(Conv((3,1,4), init=init1, batch_norm=True, activation=Rectlin()))
layers.append(BatchNorm(rho=0.99, eps=1e-06))

but I get the same error.

Wondering if setting batch_norm=True is also doing a batch normalization, I deleted the BatchNorm layer, but then got this error:

pycuda.driver.CompileError: nvcc compilation of /tmp/tmpl7jZgI/kernel.cu failed
[command: nvcc --cubin --use_fast_math -arch sm_52 -I/home/  /neon/neon/.venv/lib/python2.7/site-packages/pycuda/cuda kernel.cu]
[stderr:
kernel.cu(26): error: identifier "None" is undefined
kernel.cu(61): error: identifier "None" is undefined
2 errors detected in the compilation of "/tmp/tmpxft_000016fc_00000000-7_kernel.cpp1.ii".
]

Could someone provide an example model that uses BatchNorm?

**Comment by scttl** [comment]
Hi,

There are a few example networks using batch normalization.  See for instance: [cifar10_conv.py](https://github.com/NervanaSystems/neon/blob/master/examples/cifar10_conv.py) and [vgg_bn.py](https://github.com/NervanaSystems/neon/blob/master/examples/vgg_bn.py).

Your last intuition is correct.  In newer versions of neon, setting `batch_norm=True` in a particular layer is all that is needed and you no longer need to separately specify an explicit `BatchNorm()` layer.
