### ISSUE TITLE
When will this framework be compatible with OpenCL on Intel Graphics Chips e.g. Iris?

### ISSUE THREAD

**Issue by shyamalschandra** [NervanaSystems/neon#134]
When will that happen?  Do you need any help?  Could you please document the source code some more so I can reverse-engineer it to enable this feature?

**Comment by ursk** [comment]
We currently have no plans to add OpenCL support to neon. Community contributions are always welcome though! A good starting point would be to look at Andreas Klöckner's PyOpenCL package, that provides a very similar interface to his PyCUDA that neon is using for CUDA.
