### ISSUE TITLE
ROI pooling

### ISSUE THREAD

**Issue by rodrigob** [NervanaSystems/neon#135]
Current [fast convnet detectors](http://arxiv.org/abs/1506.01497) rely on a so-called "Region of Interest Pooling" layer.
Are there any plans on implementing such layer in neon ?

**Comment by yinyinl** [comment]
We have implemented such ROI pooling layer and the Fast RCNN model internally. Currently looking into ways to optimize the efficiency for such special case of pooling, before releasing to the public. Stay tuned.

**Comment by scttl** [comment]
This is now available publicly (along with FastRCNN) via commits 811cd1a0 and 1c2250fa
