### ISSUE TITLE
ImageLoader - AttributeError

### ISSUE THREAD

**Issue by leovetter** [NervanaSystems/neon#142]
Hi everyone,

I recently installed neon to train neural network on the ImageNet dataset. I followed the instruction given in the documentation so I downloaded the tar files for the imagenet datasets (training / validation and testing sets) then I use the following command to convert raw images into binaries :

`python neon/util/batch_writer.py  --data_dir /usr/local/data/tmp
--image_dir=/usr/local/data/I1K/imagenet_orig
--set_type=i1k`

But when I want to load my training dataset using `train = ImageLoader(repo_dir=args.data_dir, inner_size=224, set_name='train')` I get the following Traceback :
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/naabuser/naabVE/local/lib/python2.7/site-packages/neon-1.1.2-py2.7.egg/neon/data/imageloader.py", line 37, in __init__
    rgb, multiview, set_name, subset_pct, macro)
  File "/home/naabuser/naabVE/local/lib/python2.7/site-packages/neon-1.1.2-py2.7.egg/neon/data/imageloader.py", line 86, in configure
    self.minibatch_size = self.be.bsz
AttributeError: 'NoneType' object has no attribute 'bsz'
``` 

I don't get what is the problem ? Any help would be appreciated. Thanks.

**Comment by nervetumer** [comment]
You need to set up a backend before setting up the image loader.  In our examples this is done behind the scenes in the NeonArgparser based on the command line options given (or the defaults).  

Try:
```
from neon.backends import gen_backend
gen_backend(backend='cpu', batch_size=128)
```

Note there are many backend options please see the docs.  For examples, if you have a compatible GPU you can make a gnu backend by changing backend='cpu' to backend='gnu'.

**Comment by nervetumer** [comment]
Have you had a chance to try the backend generation?  If so, can i close this issue?

**Comment by leovetter** [comment]
Yes it's working. Thanks for the help.
