### ISSUE TITLE
Unpooling Layers for Conv AE

### ISSUE THREAD

**Issue by eracah** [NervanaSystems/neon#143]
Are there any plans for implementing unpooling layers for convolutional autoencoders or FCN's, like the ones described in section 3.2.1 in Hoh - "Learning Deconvolution Network for Semantic Segmentation"?

**Comment by nervanasys** [comment]
We were getting good performance using strided deconvolution instead of unpooling. Have you tried using that?

**Comment by eracah** [comment]
Thanks for the quick response. Currently trying out something similar in architecture to the conv-ae example. I'll let you know how it goes.

**Comment by ankitp94** [comment]
@eracah I would also like to see how to use unpooling instead of strided deconvolution ? Please do share your results and implementation once you're done. Thanks!

**Comment by etienne87** [comment]
@eracah +1, i would have thought unpooling to more effective? anyway, isn't there a way to do it using just the autodiff of the pooling layer (using last convolutional maps as inputs) ?

**Comment by scttl** [comment]
Hi,

Though we'd love to see a pull request for this, we don't have any plans internally to implement unpooling layers at this time.

If you want to see a successful application of the strided deconvolution approach, I'd recommend checking out @anlthms ' [right whale localizer code](https://github.com/anlthms/whale-2015)
