### ISSUE TITLE
Using a  2D y in a DataIterator

### ISSUE THREAD

**Issue by eracah** [NervanaSystems/neon#145]
Is it possible to set y equal to a 2D array for DataIterator? Based on the documentation, it looks like DataIterator expects a #ofexamples x 1 array for y. 
I am looking to have a #ofexamples x 8 x 24 array as y. The reason I want to do this is for a convolutional autoencoder, but my X is of slightly different dimensions as my y as weird as that may sound (so you can't technically call it an autoencoder I guess). 
Is this possible?

**Comment by tambetm** [comment]
In DataIterator constructor set X to your input, y to your output, nclass to number of columns in output and make_onehot=False. Like this:
```
train_set = DataIterator(X_train, y_train, nclass=y_train.shape[1], make_onehot=False)
```
