### ISSUE TITLE
Re-training network after importing weights

### ISSUE THREAD

**Issue by mwoodson1** [NervanaSystems/neon#146]
Is it possible to train a network after importing weights from a  model_file? I have tried myself with the code below but not even 1 epoch gets iterated. Yet I can still test the network with `model.val`.
Something like:

`model = constuct_network()`
`model.load_weights(args.model_file)`
`model.fit(train, optimizer=opt, num_epochs=args.epochs, cost=cost, callbacks=callbacks)`

**Comment by nervetumer** [comment]
Are you setting the epochs correctly.  If you're provious sessions went for 10 epochs, and you want to train for 10 more epochs, you'll need to set the number of epochs to be 20.  So on the command line put -e 20.

**Comment by mwoodson1** [comment]
Ah yes I didn't take that into account. Works now, thanks!
