### ISSUE TITLE
Install failed: nvcc fatal   : Unknown option 'std'

### ISSUE THREAD

**Issue by DavidWiesner** [NervanaSystems/neon#150]
Here is the complete error message
```
Building loader.so...
nvcc fatal   : Unknown option 'std'
Makefile:40: recipe for target 'loader.so' failed
make[1]: *** [loader.so] Error 255
Makefile:160: recipe for target 'neon/data/loader' failed
make: *** [neon/data/loader] Error 2
```
------------
Cuda V7.0.27

**Comment by scttl** [comment]
Hi,

Looks like your environment doesn't support C++11 via the `-std=c++11` flag.  CUDA's `nvcc` added support for this in v7 (not sure if this would have been before or after 7.0.27).  So you may need to upgrade that.  You'll also need to ensure you're using a version of gcc >= 4.7

**Comment by DavidWiesner** [comment]
Thx. It was indeed the wrong version of CUDA. I had CUDA 6.5 installed.
