### ISSUE TITLE
Model initialization issue

### ISSUE THREAD

**Issue by DavidYoungSoton** [NervanaSystems/neon#151]
I started looking at the cifar10 example (in version 1.1.3), and it seemed a natural check to modify the example to display the error before training, by inserting the first of these three lines (before the last two lines of the module):
```python
print('Misclassification error = %.1f%%' % (mlp.eval(test, metric=Misclassification())*100)
mlp.fit(train, optimizer=opt_gdm, num_epochs=args.epochs, cost=cost, callbacks=callbacks)
print('Misclassification error = %.1f%%' % (mlp.eval(test, metric=Misclassification())*100))
```
As expected, the first statement prints a 90% misclassification error. However the call to `Model.fit` then throws an exception. This is unexpected, because an evaluation should not change the state of the model.

The exception is ultimately from `GeneralizedCost.get_cost` in the layers module.  The error message is uninformative, but it turns out that the problem is that the call to `eval` sets `mlp.initialized` true, and then the call to `fit` ignores its `cost` argument because `Model.Initialize` returns immediately, without initializing `cost`. That is, the model object thinks it has been initialized, but the initialization process can't be completed until it has been passed a cost object.

The solution is to insert an explicit initialization call before the first line above, so the last four lines of the example become:
```
mlp.initialize(dataset=train, cost=cost)
print('Misclassification error = %.1f%%' % (mlp.eval(test, metric=Misclassification())*100))
mlp.fit(train, optimizer=opt_gdm, num_epochs=args.epochs, cost=cost, callbacks=callbacks)
print('Misclassification error = %.1f%%' % (mlp.eval(test, metric=Misclassification())*100))
```
My problem is that it took a lot of delving into the source code to figure this out, and this suggests that the documentation could be improved. I'd like to suggest:
* the code for the example includes the initial evaluation, so that users can see how this can be done;
* the `Model.initialize` method should be properly documented;
* the users' guide should have a section explaining when different components get initialized.

I also wonder if the initialization mechanisms should be reexamined to simplify the process. Perhaps a `GeneralizedCost` object should have its own flag, rather than relying on the flag in the `Model` object, given that the initialization of the latter isn't a unitary process.

**Comment by scttl** [comment]
Hi David,

Thanks for pointing this out.  We'll be pushing some updated documentation shortly which should help address this.  Note that the problem only occurs if you attempt to fit a model after first trying to do an eval (just fitting, just eval, fit then eval are all ok).

**Comment by DavidYoungSoton** [comment]
Many thanks.

David
