### ISSUE TITLE
Explanation of the constants in the tutorials for Neon

### ISSUE THREAD

**Issue by shyamalschandra** [NervanaSystems/neon#152]
Hi,

Would you be able to provide more explanation in the comments for the code (or at least the papers that are relevant to the underlying theory) for the Neon tutorials?

Thanks!

Shyamal

**Comment by scttl** [comment]
Hi,

Are you referring to the tutorials described here: http://neon.nervanasys.com/docs/latest/introductory_resources.html, or the example networks in the `examples` directory, and described here: http://neon.nervanasys.com/docs/latest/examples.html?  If you click on the python files in the latter you'll see that most of them already do include paper references in the docstrings at the top.  We'll add those same references to the docs so its a bit more prominent.

**Comment by shyamalschandra** [comment]
Can you include something like a embedded code example with comments (https://trinket.io) with paper references (similiar to theanets)?
