### ISSUE TITLE
Batch writing for custom sequence data

### ISSUE THREAD

**Issue by mwoodson1** [NervanaSystems/neon#154]
Are there any plans to extend the capabilities of the BatchWriter class to be able to process data other than images? For example I have a dataset of sequence data (videos) which I would like to process in batches. I managed to hack away a solution that works for now but official support for sequence data or other types of data besides images would be nice.

**Comment by nervanasys** [comment]
Yes, this is coming soon

**Comment by mwoodson1** [comment]
Any update on this? I was thinking of re-writing my old code for sequence data input to be more general but if something is already in the works I can hold off.

**Comment by hanlin-nervana** [comment]
We've added in version 1.5.1 macrobatching support for images, video, and audio. See http://neon.nervanasys.com/docs/latest/loading_data.html#dataloader for the documentation, as well as our `examples/video-c3d` folder for an example usage.
