### ISSUE TITLE
kaggle competition

### ISSUE THREAD

**Issue by andrewcz** [NervanaSystems/neon#160]
Hi,
Was just wondering if there are any plans to maybe show an example of the product based on the below competition. Apparently the data is quite challenging.

https://www.kaggle.com/c/the-winton-stock-market-challenge

Many thanks for your consideration,
Best,
Amdrew

**Comment by scttl** [comment]
Hi,

We just posted the video and slides for a different Kaggle competition: Right Whale detection, given by @anlthms.  You can find links to those here: http://neon.nervanasys.com/docs/latest/introductory_resources.html#sv-deep-learning-meetup-2015-11-17

At this point I don't believe there are any plans to post something similar for the Winton challenge dataset, but we may revisit if we get some time.
