### ISSUE TITLE
 neon.data.imageloader - ERROR - Unable to load loader.so

### ISSUE THREAD

**Issue by roshankr** [NervanaSystems/neon#161]
Hello , 
I have installed neon using 'make sysinstall' (System-wide Install) , but getting the below error  

Skipping prep...
Localizing first point: Tue Dec 15 22:05:27 CST 2015
2015-12-15 22:05:27,520 - neon.data.imageloader - ERROR - Unable to load loader.so. Ensure that this file has been compiled
Traceback (most recent call last):
  File "./localizer.py", line 47, in <module>
    point_num=point_num)
  File "/home/roshan/Desktop/DS/Others/data/Kaggle/RWR/whale-2015/localizer_loader.py", line 31, in __init__
    subset_pct, nlabels, macro, dtype)
  File "/home/roshan/anaconda3/envs/python2/lib/python2.7/site-packages/neon/data/imageloader.py", line 74, in __init__
    self.start()
  File "/home/roshan/anaconda3/envs/python2/lib/python2.7/site-packages/neon/data/imageloader.py", line 194, in start
    self.loader = self.loaderlib.start(ct.c_int(self.img_size),
AttributeError: 'LocalizerLoader' object has no attribute 'loaderlib'

There were no issues while running "make sysinstall" ,
Installing maxas...

62 kernels compiled.

Building loader.so...
Installing neon system wide...
Processing /home/roshan/neon
  Requirement already satisfied (use --upgrade to upgrade): neon==1.1.4 from file:///home/roshan/neon in /home/roshan/anaconda3/envs/python2/lib/python2.7/site-packages

also i tried 'make' in neon/data/loader folder as well
Building loader...
nvcc -o loader -DSTANDALONE -DHASGPU -I/usr/local/cuda/include  -O0 -g -std=c++11 -lcudart -lcuda loader.cpp $(pkg-config opencv --cflags --libs)

Thanks,
Roshan

**Comment by scttl** [comment]
Since you installed system wide, can you first check that `/home/roshan/anaconda3/envs/python2/lib/python2.7/site-packages/neon/data/loader/loader.so` exists and whatever user you are running as has the appropriate permissions to read/execute it?

**Comment by roshankr** [comment]
scttl, thanks for the suggestion. loader.so is available with full permissions, but still having the same issue
roshan@roshan-810-230qe:~/neon/neon/data/loader$ ls -l
total 1016
-rwxrwxrwx 1 roshan roshan   3227 Dec 16 09:56 buffer.hpp
-rwxrwxrwx 1 roshan roshan   2976 Dec 16 09:56 decoder.hpp
-rwxrwxrwx 1 roshan roshan   5506 Dec 16 09:56 device.hpp
-rwxrwxrwx 1 roshan roshan 846765 Dec 16 10:19 loader
-rwxrwxrwx 1 roshan roshan  23889 Dec 16 09:56 loader.cpp
-rwxrwxrwx 1 roshan roshan 122376 Dec 16 10:19 loader.so
-rwxrwxrwx 1 roshan roshan   1925 Dec 16 10:19 Makefile
-rwxrwxrwx 1 roshan roshan   1924 Dec 16 10:12 Makefile~
-rwxrwxrwx 1 roshan roshan   1053 Dec 16 09:56 matrix.hpp
-rwxrwxrwx 1 roshan roshan   9398 Dec 16 09:56 reader.hpp
drwxrwxrwx 2 roshan roshan   4096 Dec 16 09:56 test

**Comment by scttl** [comment]
That looks to me like a listing of your `/home/roshan/neon/neon/data/loader` dir.  From the first snippet, it appears neon was installed in a conda env under `/home/roshan/anaconda3/envs/python2/lib/python2.7/site-packages/neon`.  Can you list the `data/loader` directory under that instead?

**Comment by roshankr** [comment]
there were no directory "loader" under /home/roshan/anaconda3/envs/python2/lib/python2.7/site-packages/neon/data ...its missing...If that's the issue , shall i copy it from other directory and make ?

**Comment by scttl** [comment]
Yes that's the issue.  It should get created as part of your `make` install.  If you are using conda, I'd recommend creating a conda env and using the environment file as described here: http://neon.nervanasys.com/docs/latest/user_guide.html#anaconda

**Comment by roshankr** [comment]
I will try this and let you know the outcome...Many thanks

**Comment by roshankr** [comment]
Hi scttl, It worked, Many thanks for helping me out this.
