### ISSUE TITLE
Incorrect AutoDiff for dot(x, x.T) ?

### ISSUE THREAD

**Issue by oleg-trott** [NervanaSystems/neon#169]
I'm guessing that the last output is not the intended behavior and should be the same as the previous result (as `x` is symmetric here):

    In [271]: neon.__version__
    Out[271]: '1.1.3'
    
    In [272]: x = ng.ones((1, 1))
    
    In [273]: Autodiff(op_tree=ng.dot(x, x), be=ng, next_error=None).get_grad_asnumpyarray([x])
    Out[273]: [array([[ 2.]], dtype=float32)]
    
    In [274]: Autodiff(op_tree=ng.dot(x, x.T), be=ng, next_error=None).get_grad_asnumpyarray([x])
    Out[274]: [array([[ 1.]], dtype=float32)]

**Comment by linuxthink** [comment]
Thanks for spotting this. Issue confirmed. It's due to the fact the gradient for `x.T` is not accumulated correctly to the gradient for `x`. Will push a fix soon.
