### ISSUE TITLE
Incorrect AutoDiff for some expressions with "max" ?

### ISSUE THREAD

**Issue by oleg-trott** [NervanaSystems/neon#170]
The last result apparently violates the linearity of the gradient operator (as it should be the sum of the previous two)

    In [352]: neon.__version__
    Out[352]: '1.1.3'
    
    In [353]: x = ng.array(np.array([[2, 3]]))
    
    In [354]: Autodiff(op_tree=(0+x), be=ng, next_error=ng.ones(x.shape)).get_grad_asnumpyarray([x])
    Out[354]: [array([[ 1.,  1.]], dtype=float32)]
    
    In [355]: Autodiff(op_tree=ng.max(x), be=ng, next_error=ng.ones(x.shape)).get_grad_asnumpyarray([x])
    Out[355]: [array([[ 0.,  1.]], dtype=float32)]
    
    In [356]: Autodiff(op_tree=(ng.max(x) + x), be=ng, next_error=ng.ones(x.shape)).get_grad_asnumpyarray([x])
    Out[356]: [array([[ 1.,  3.]], dtype=float32)]

I guess it is the second result that should be considered incorrect, which also differs from `ng.max(x) + 0`. 

`min` and `sum` seem to be similarly affected:

    In [382]: Autodiff(op_tree=(ng.sum(x)), be=ng, next_error=ng.ones(x.shape)).get_grad_asnumpyarray([x])
    Out[382]: [array([[ 1.,  1.]], dtype=float32)]
    
    In [383]: Autodiff(op_tree=(ng.sum(x) + 0), be=ng, next_error=ng.ones(x.shape)).get_grad_asnumpyarray([x])
    Out[383]: [array([[ 2.,  2.]], dtype=float32)]

**Comment by oleg-trott** [comment]
"min" seems to be similarly affected.

**Comment by linuxthink** [comment]
This behavior is expected. The linearity of the gradient operator applies to element-wise operations. However, `min`, `max` and `sum` are reduction operations. In `max(x) + x` for example, the value of `max(x)` (scalar) gets broadcast to the subsequent operations.

You could checkout the following scripts to test against numerical gradients:
```
import numpy as np

def get_numerical_gradient(f, tensors, delta=1e-5):
    # buffer for gradients
    gradients = []
    for i in range(len(tensors)):
        tensors[i] = tensors[i].astype(np.float64)
        gradients.append(np.zeros(tensors[i].shape))

    # iterate throuth each tensor
    for tensor, gradient in zip(tensors, gradients):

        tensor_flat = tensor.reshape((-1, ))
        gradient_flat = gradient.reshape((-1, ))

        # iterate throuth each element
        for idx in range(len(tensor_flat)):
            # backup
            backup = tensor_flat[idx]
            # increment
            tensor_flat[idx] = tensor_flat[idx] + delta
            f_inc = np.sum(f(*tensors))
            # decrement
            tensor_flat[idx] = backup - delta
            f_dec = np.sum(f(*tensors))
            # recover
            tensor_flat[idx] = backup
            # gradient
            gradient_flat[idx] = (f_inc - f_dec) / (2.0 * delta)

    return gradients

print get_numerical_gradient(lambda x: np.sum(np.max(x) + x), 
                             [np.array([2., 3.])], 
                             delta=1e-5)

# The result is [array([ 1.,  3.])]
```

Or, we could also use HIPS's [autograd](https://github.com/HIPS/autograd) to verify the result:
```
import autograd.numpy as np
from autograd import grad

func_grad = grad(lambda x: np.sum(np.max(x) + x))
print func_grad(np.array([2., 3.]))  # [ 1.  3.]

func_grad = grad(lambda x: np.sum(np.max(x)))
print func_grad(np.array([2., 3.]))  # [ 0.  1.]

func_grad = grad(lambda x: np.sum(x))
print func_grad(np.array([2., 3.]))  # [ 1.  1.]
```

In the above examples, applying `sum` to the final results is equivalent to setting `next_error` to a matrix of ones in neon's autodiff.

**Comment by oleg-trott** [comment]
As I mentioned, it's the second result that's suspect, rather than the third.

Note that `ng.max(x)` and `ng.max(x) + 0` can have different gradients in Neon:

    In [498]: x = ng.array(np.array([[2, 3]]))
    
    In [499]: def grad(e): return Autodiff(op_tree=e, be=ng, next_error=ng.ones(x.shape)).get_grad_asnumpyarray([x])
    
    In [500]: grad(ng.max(x))
    Out[500]: [array([[ 0.,  1.]], dtype=float32)]
    
    In [501]: grad(ng.max(x)+0)
    Out[501]: [array([[ 0.,  2.]], dtype=float32)]

I'm assuming that this is because the broadcasting isn't taken into account in the gradient calculation, even though the broadcasting itself takes place with or without `+0`:

    In [502]: y = ng.zeros(x.shape)
    
    In [503]: y[:] = ng.max(x)
    
    In [504]: y.get()
    Out[504]: array([[ 3.,  3.]], dtype=float32)

**Comment by linuxthink** [comment]
Oh thanks, now I see what you mean. Will update this post after I find the solution.

**Comment by oleg-trott** [comment]
I realize that it's the shape of `next_error` that triggers the bug -- that's why I mentioned broadcasting. Broadcasting is very useful, and it's obviously a differentiable operation. I think it's more helpful to fix its gradient than to forbid it. Perhaps add a `0` to all expressions? :-)

**Comment by linuxthink** [comment]
Yeah, but I guess in that case it might be more reasonable to do the broadcasting manually. `next_error` is typically the back-propagated gradients from the final cost to an intermediate output (such as a layer's activation), so the shape of `next_error` shall be consistent to the shape of that intermediate output. 

If the output shape needs broadcasting to match the shape of the `next_error`, we could just define another "broadcasted output" that is the same shape as the `next_error`.
