### ISSUE TITLE
Race condition in softmax-like expressions?

### ISSUE THREAD

**Issue by oleg-trott** [NervanaSystems/neon#171]
There appears to be a race condition in certain expressions, such as the denominator of softmax with `axis=1` (unlike in `neon.transforms.activation`):

https://gist.github.com/oleg-trott/30b802902fd8c63ce002

 I tried this on several GTX 980 cards and see it on all of them. The errors are rare, about 0.1-0.2%. However, when they happen, they are usually dramatic.

I also see these errors on GTX 750, but they are about 100 times less frequent.

**Comment by ursk** [comment]
Thanks for finding this! I tried it on a couple of Titan X's and can confirm the issue, with about the same frequency as you get on the 750. We will look into what's causing it.

**Comment by ursk** [comment]
Oleg, we have a fix for the issue that will be included in the next point release of neon. Thanks again!

**Comment by oleg-trott** [comment]
That's great to hear, thanks! I know these things can be hard to track down.

**Comment by scott-gray** [comment]
I haven't been able to track it down yet.  I only reduced the number of
reduction threads:

From float_ew:

                    # speed up deep reduction by using more than 32 threads
                    # if reduction and not argminmax:
                    #     if red_depth >= 4096:
                    #         threads = 1024
                    #     elif red_depth >= 2048:
                    #         threads = 512
                    #     elif red_depth >= 1024:
                    #         threads = 256
                    #     elif red_depth >= 512:
                    #         threads = 128
                    #     elif red_depth >= 256:
                    #         threads = 64
                    # TODO: The above code can lead to a race condition.
                    # Temporary workaround while investigating further:
                    if red_depth > 256:
                            threads = 64

By doing this, the shared memory reduction is much simplified and the
problem seems to go away.  This does reduce reduction performance a bit
though.

**Comment by oleg-trott** [comment]
One possibly silly suggestion I have is to insert `_synchthreads();` after every `;` , `\n` and  `}` in the kernel, one at a time, and retest. This is tedious to do manually, but I think it can be automated and run overnight.

Many of those insertions will break compilation, others might make the program incorrect, but if one of them apparently fixes the issue, it might provide insights into what's going on. (Feel free to ignore, especially if you are sure that it's not a missing `_synchthreads()` )

**Comment by scott-gray** [comment]
There are no missing synchthreads.  I analyzed the code at the assembly
level and didn't spot any potential race issues.  This may actually be a
hardware bug (I've seen flakiness with predicated shared stores before).  I
need to spend some more time generating the simplest possible repro.  But
for now the above code change should let you work.

**Comment by oleg-trott** [comment]
I think I may have a fix for this issue (relative to v1.1.3):

If you add `__syncthreads();` after https://github.com/NervanaSystems/neon/blob/v1.1.3/neon/backends/cuda_templates.py#L102
(with extra `{{` and `}}` around the body of the loop), 

        #pragma unroll
        for (int i = 16; i > 0; i >>= 1) {{
            __syncthreads();
            %(shfl_red{0})s
        }}

the problem goes away.

As I understand it, the need to syncthreads within a warp is somewhat controversial:
https://devtalk.nvidia.com/default/topic/632471/is-syncthreads-required-within-a-warp-/

I don't want to get into that debate, because I'm not a hardware guy, but I just wanted to report that this change appears to fix this problem for me: the number of errors over 5 trials goes from about 1000 to 0.

**Comment by scott-gray** [comment]
Thanks,  don't know why I didn't think to try adding a __syncthreads there.  I still want to spend some time investigating why it's needed.  It's probably the best work around to a hardware shared memory store erratum.  Most of the time is spent in the first loop reducing memory into all the threads.  Adding a syncthreads here will not effect performance in any meaningful way.

**Comment by oleg-trott** [comment]
> a hardware shared memory store erratum

Nvidia acknowledged this as a hardware bug, or is this something unrelated?

**Comment by scott-gray** [comment]
I'm not sure.  I need to study it more.

**Comment by scott-gray** [comment]
Actually, I'm not sure why that works at all.  You shouldn't be putting a __syncthreads inside code that can be executed conditionally.  At least that's how it used to work.  But I see in the sass the branching is managed with SYNCs so maybe that's ok.  A SYNC branch doesn't actually branch, just executes the instructions as no-ops if the thread is inactive.

Looking very closely at the sass I still can not spot any problem.  Sometimes adding __syncthreads just modifies the timing of things making the problem go away.  Shuffle instructions require no syncing as far as I know.  It's more likely the first __syncthreads is the effective one so maybe try moving it out and just above the loop:

```
    if ( tid < 32 )
    {{
        %(share2_red{0})s

        __syncthreads(); // Seems to be required to prevent a race condition.

        #pragma unroll
        for (int i = 16; i > 0; i >>= 1)
            %(shfl_red{0})s

        sPartials[tid] = %(var_red{0})s;
    }}
```
Indeed I just checked this and it works too.  There's probably something very subtle going on with interactions between SYNC branches and shared memory operations.  If I were hand coding the sass I'd see that all the branches are warp uniform and hence use real branches.  This would run faster.  But the compiler doesn't seem smart enough to tie conditional logic back to the thread id and assumes all conditionals can be non-warp-uniform.  I guess I could use inline ptx here and use real branches.  But, if that syncthreads mysteriously solves the problem, I guess I'll hold off on that.
