### ISSUE TITLE
clarifications on caffe support

### ISSUE THREAD

**Issue by mtamburrano** [NervanaSystems/neon#172]
I read that it is possible to set a flag to enable caffe compatibility, from the doc:
"if this is set to 'caffe' then the conv and pooling layer output sizes will match that of caffe as will the dropout layer implementation"
I see in the code that dropout changes is behaviour from "keep" to "drop", like caffe does, but what about convolutional and pooling layers? What are the differences between neon and caffe? I can't find any reference to it neither code to check the caffe flag to change the behaviour of those layers

**Comment by nervetumer** [comment]
The output sizes of conv and pooling layers in neon and caffe are computed differently.  Setting the caffe flag will make neon use the caffe formula for setting the output size of a conv and pooling layer.  The code that shows this difference is located in the class "Backend" under the method named "output_dim".  https://github.com/NervanaSystems/neon/blob/master/neon/backends/backend.py

**Comment by mtamburrano** [comment]
thank you, I missed that change
