### ISSUE TITLE
Non-square image inputs are distorted when passed from the loader

### ISSUE THREAD

**Issue by lolz0r** [NervanaSystems/neon#177]
Hello,
After combing through the neon codebase it looks like the loader is rescaling image inputs and in cases where that input is non-square it is rescaled to be square thereby loosing the aspect ratio and distorting the image.

**Comment by scttl** [comment]
Hi, thanks for pointing this out.  We've already changed the data loader internally so that aspect ratio can be maintained or adjusted during the scaling process, and we plan on pushing this publicly in our next release.

**Comment by scttl** [comment]
Just a heads up that the new data loader code has been pushed with the v1.2.0 release.

**Comment by lolz0r** [comment]
Thanks nice job!
