### ISSUE TITLE
make install failed!

### ISSUE THREAD

**Issue by andyyuan78** [NervanaSystems/neon#18]
ubgpu@ubgpu:~/github/neon$ . .venv/bin/activate
(.venv)ubgpu@ubgpu:~/github/neon$ sudo make install
[sudo] password for ubgpu: 
The directory '/home/ubgpu/.cache/pip/log' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubgpu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubgpu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.1 in /usr/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.11 in /usr/local/lib/python2.7/dist-packages
The directory '/home/ubgpu/.cache/pip/log' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubgpu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubgpu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): nose>=1.3.0 in /usr/lib/python2.7/dist-packages
Collecting Pillow>=2.5.0
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading Pillow-2.8.1.tar.gz (9.0MB)
    100% |鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅| 9.0MB 70kB/s 
Collecting flake8>=2.2.2
  Downloading flake8-2.4.0-py2.py3-none-any.whl
Collecting pep8-naming>=0.2.2
  Downloading pep8_naming-0.2.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): sphinx>=1.2.2 in /usr/lib/python2.7/dist-packages
Collecting sphinxcontrib-napoleon>=0.2.8
  Downloading sphinxcontrib_napoleon-0.3.4-py2.py3-none-any.whl (50kB)
    100% |鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅| 53kB 276kB/s 
Collecting scikit-learn>=0.15.2
  Downloading scikit-learn-0.16.1.tar.gz (7.3MB)
    100% |鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅| 7.3MB 81kB/s 
Collecting matplotlib>=1.4.0
  Downloading matplotlib-1.4.3.tar.gz (50.4MB)
    100% |鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅| 50.4MB 14kB/s 
Collecting imgworker>=0.2.5 from git+https://github.com/NervanaSystems/imgworker.git#egg=imgworker>=0.2.5
  Cloning https://github.com/NervanaSystems/imgworker.git to /tmp/pip-build-b5tfve/imgworker
Collecting cudanet>=0.2.5 from git+https://github.com/NervanaSystems/cuda-convnet2.git#egg=cudanet>=0.2.5
  Cloning https://github.com/NervanaSystems/cuda-convnet2.git to /tmp/pip-build-b5tfve/cudanet
Collecting pycuda>=2014.1
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading pycuda-2014.1.tar.gz (1.6MB)
    100% |鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅鈻堚枅| 1.6MB 117kB/s 
    Complete output from command python setup.py egg_info:
    *** WARNING: nvcc not in path.
    *************************************************************
    *** I have detected that you have not run configure.py.
    *************************************************************
    *** Additionally, no global config files were found.
    *** I will go ahead with the default configuration.
    *** In all likelihood, this will not work out.
    *** 
    *** See README_SETUP.txt for more information.
    *** 
    *** If the build does fail, just re-run configure.py with the
    *** correct arguments, and then retry. Good luck!
    *************************************************************
    *** HIT Ctrl-C NOW IF THIS IS NOT WHAT YOU WANT
    *************************************************************
    Continuing in 1 seconds...    
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-b5tfve/pycuda/setup.py", line 216, in <module>
        main()
      File "/tmp/pip-build-b5tfve/pycuda/setup.py", line 88, in main
        conf["CUDA_INC_DIR"] = [join(conf["CUDA_ROOT"], "include")]
      File "/usr/lib/python2.7/posixpath.py", line 77, in join
        elif path == '' or path.endswith('/'):
    AttributeError: 'NoneType' object has no attribute 'endswith'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b5tfve/pycuda
make: *** [deps_install] Error 1
(.venv)ubgpu@ubgpu:~/github/neon$

**Comment by scttl** [comment]
Hi Andy,

A couple of points that may help get you unstuck:
* with the virtualenv based install, assuming user `ubgpu` created the `.venv` directory, you should only need to run `make install` not `sudo make install` as the python packages should be installed under that directory.
* The real reported issue looks to me like the CUDA compiler `nvcc` is not being found.  Locating this should already be addressed in our FAQ: http://neon.nervanasys.com/docs/latest/faq.html#installation (and note in particular that you need to ensure certain environment variables are being passed through when run as sudo)

Give those suggestions a try, and let me know if that helps

**Comment by apark263** [comment]
If you put your cuda bin directory in your path and run as non su, nvcc
should get picked up

**Comment by andyyuan78** [comment]
it works well ,thanks apark263 and scttl

**Comment by oleg-trott** [comment]
> assuming user ubgpu created the .venv directory

I found this confusing too. The installation instructions ask you to to do `. .venv/bin/activate` after `make`, so I thought it wasn't necessary to do anything of that sort before the installation, or the instructions would mention it. This leads to "Permission denied". Some users might give up if the installation instructions don't work.
