### ISSUE TITLE
memcpy instead of broadcasting?

### ISSUE THREAD

**Issue by oleg-trott** [NervanaSystems/neon#182]
from neon.backends import gen_backend
    ng = gen_backend(backend='gpu', device_id=0)
    
    y = ng.zeros((2, 1))
    x = ng.zeros((2, 2))
    
    x[:] = y + 0 # OK
    x[:] = y     # cuMemcpyDtoDAsync failed: invalid argument

(I'm still on 1.1.3 by the way)

**Comment by jennifermyers** [comment]
A fix for this will be part of the imminent v1.5.0 neon release.
