### ISSUE TITLE
x[:] = y proceeds with incompatible shapes

### ISSUE THREAD

**Issue by oleg-trott** [NervanaSystems/neon#183]
from neon.backends import gen_backend
    ng = gen_backend(backend='gpu', device_id=0)
    
    x = ng.zeros((2, 3))
    y = ng.zeros((5, 7))
    
    x[:] = y       # no exceptions
    x[:] = y + 0 # raises an error

Perhaps related to https://github.com/NervanaSystems/neon/issues/182

**Comment by jennifermyers** [comment]
A fix for this will be part of the imminent v1.5.0 neon release.
