### ISSUE TITLE
bounds checking in fancy indexing

### ISSUE THREAD

**Issue by oleg-trott** [NervanaSystems/neon#184]
from neon.backends import gen_backend
    import numpy as np
    ng = gen_backend(backend='gpu', device_id=0)
    
    x = ng.zeros((5, 5))
    i = ng.zeros((3, 1), dtype=np.int32); i[:] = 7
    j = ng.zeros((1, 1), dtype=np.int32); j[:] = 7
    
    x[i] = 1 # no errors or apparent changes in x
    x[j] = 1 # no errors, but sets x[0, :] to 1

**Comment by diyessi** [comment]
In deference to performance, the GPU backend does little if any bounds checking.  We will add something to the documentation about this.
