### ISSUE TITLE
'OpTreeNode' object has no attribute 'reshape'

### ISSUE THREAD

**Issue by oleg-trott** [NervanaSystems/neon#185]
Not sure if it's a bug or a feature, but I wish this worked (in more complex expressions, of course *)

    from neon.backends import gen_backend
    ng = gen_backend(backend='gpu', device_id=0)
    
    x = ng.zeros((2, 2))
    y = ng.zeros((4, 1))
    
    x[:] = y.reshape(x.shape) # OK
    x[:] = (y+0).reshape(x.shape) # 'OpTreeNode' object has no attribute 'reshape'

(\*) such as

    x[:] = (y*z).reshape(x.shape).max(axis=0)

**Comment by diyessi** [comment]
It looks like a bug to me.

**Comment by yinyinl** [comment]
The optree currently supports numerical operations and transpose, but not reshape operation. And in your case, (y+0) returns an optree object. It is designed like this, so one can keep adding operations to an optree and hold off the execution. If you have a tensor z, e.g.
z = ng.zeros(y.shape)
z[:] = y+0
It is when you do assignment using [:], the optree gets executed and put results into Tensor structure, after which, you can do a reshape.

**Comment by scott-gray** [comment]
Seems like a nice to have feature, but we'll probably wait till we have a full computational graph for that one.

**Comment by yinyinl** [comment]
Agreed. For now, the way it is supposed to work is that a user uses [:] to execute the optree and assign to another tensor or "y" itself, before a reshape can be done.
