### ISSUE TITLE
Does the framework support stateful RNN?

### ISSUE THREAD

**Issue by panjinbo** [NervanaSystems/neon#189]
I want to know whether the framework support stateful RNN. May I have a example of it?

**Comment by yinyinl** [comment]
The RNN layers in neon are stateful by default, by setting *reset_cell* to False when instantiating the layers. You can see them being used for many of our RNN examples. Setting *reset_cell* to True can make them stateless, which is used in our *image_caption* example.

**Comment by yinyinl** [comment]
Close this issue for now. Let us know if you have more questions!
