### ISSUE TITLE
Python 3.x support

### ISSUE THREAD

**Issue by royalstream** [NervanaSystems/neon#191]
*Disclaimer: I scanned all the docs and the changelog for an answer but I couldn't find anything explicit.*

Apparently Python 3.4 was supported up to version 0.9.0 (there's even a **compat.py** from 2014) but after that it seems like it was silently dropped. There's no mention about it in the changelog (did I miss it?). The new doc pages simply say Python 2.7 and I found new code (late 2015) using the old `print`.

Is this temporary? are compatibility-related contributions welcome or was it dropped for good?

**Comment by scttl** [comment]
Hi,

Yes restoring python 3.x support is definitely something on our radar, but hasn't yet made its way to the top of our TODO pile.  We'd absolutely welcome compatibility related contributions, but would probably want to start with expanding our testing infrastructure to ensure things correctly build, all unit tests pass, and examples run across different python versions.  We were using [tox](https://tox.readthedocs.org/en/latest/) for this in the past, so that would probably be a good starting point.

**Comment by royalstream** [comment]
Got it! Thanks.

**Comment by untom** [comment]
It looks like v1.3.0 has come and gone without Python3 support making it into that release. Is there any time frame for when we can expect a Py3 compatible version of neon?

**Comment by scttl** [comment]
Hi,

Sorry we shuffled priorities around and I never got around to removing this from the v1.3.0 milestone on github (so this shouldn't have been closed).  Since this task is currently on our internal backlog, I can't really provide an updated timeframe until the work is scoped and scheduled.

**Comment by genghis88** [comment]
I was trying to use neon for a project. I ported my network from keras to neon and tried testing, and realized it wasn't working and that python3 is not supported. Supporting python3 is good for neon and for users like me. Can you give us an approximate time frame at least?

**Comment by raymondjplante** [comment]
After encountering Nervana at Boston Deep Learning Summit, I was interested in comparing to Keras + Theano, but lack of Python3 support is a non-starter.  Hope you get a chance to move this up in the queue!

**Comment by ursk** [comment]
We are actively working on python 3 support right now, and it is going to come back soon. Thanks for your patience!

**Comment by jennifermyers** [comment]
Python3 support will be part of the imminent neon 1.5.0 release.
