### ISSUE TITLE
Inference on tree structure

### ISSUE THREAD

**Issue by ozancaglayan** [NervanaSystems/neon#199]
Hi,

In the documentation of containers, it is said that for the Tree container, only the trunk branch is evaluated. Is this still valid? If yes, what is the rationale behind it? I'm planning to try neon for an architecture having N softmax outputs and I need to gather the outputs during inference time as well.

Thanks!

**Comment by yinyinl** [comment]
After our v1.2.0 release, the Tree container outputs results from all branches. So the output will be a list. If you look at the Fast RCNN model in neon examples, you can see how it is being used.

**Comment by ozancaglayan** [comment]
Thank you very much!
