### ISSUE TITLE
model.load_params failing to process 'neon.layers.recurrent.LSTM'

### ISSUE THREAD

**Issue by skeeet** [NervanaSystems/neon#202]
Seems like recurrent layers are using different pattern and hack in neon/layers/container.py:69-70 doesn't really work.
Introduced in c10a2a5774e744efb91e3a62d095dfcef9e8c579 and broken as of 8066f3f945ede9db8b2e96db46ad785c088bb4ce

**Comment by apark263** [comment]
We have a fix that wil be pushed within the next few days

**Comment by scttl** [comment]
This should be fixed as of a4b76c8 which we pushed during the v1.2.2 release yesterday.  Please let us know if you continue to spot problems here.
