### ISSUE TITLE
Using Backend

### ISSUE THREAD

**Issue by pranv** [NervanaSystems/neon#203]
Hi,

We are interested in using Nervana's tensor lib for a custom LSTM/RNN/CWRNN implementations. What is the best way to do it?

Is nervanagpu under active development? Or should we import backends from neon?

**Comment by hanlin-nervana** [comment]
Thanks for your interest! 

If you are creating custom layers for models in neon, then the approach is straightforward. All objects inherit from `NervanaObject` which has a static `be` variable for the backend. 

If you are making custom implementations outside of our neon framework, we expose the backend exactly for this purpose. You can generate a backend via:

```python
from neon.backends import gen_backend
be = gen_backend(backend='gpu') 
```

You can specify either a CPU or a GPU backend. The backend API supports many of the standard tensor operations that you would expect. Let us know if you run into any problems. 

For resources, see:
Backend overview: http://neon.nervanasys.com/docs/latest/backends.html
Backend API: http://neon.nervanasys.com/docs/latest/ml_operational_layer.html
Op-Tree: http://neon.nervanasys.com/docs/latest/optree.html
Auto-diff: http://neon.nervanasys.com/docs/latest/autodiff.html

**Comment by scttl** [comment]
Just to piggyback off of what Hanlin already mentioned, nervanagpu is no longer under development as that code has been integrated directly into neon.

**Comment by pranv** [comment]
Thanks for the quick reply. We will share our progress in the coming weeks :)

**Comment by scttl** [comment]
Keep us posted, and feel free to re-open if you have further questions.
