### ISSUE TITLE
Binary classifier experiment.

### ISSUE THREAD

**Issue by andrewcz** [NervanaSystems/neon#212]
Hi,
Fantastic Library, so clear!
I was just wondering, i am trying to use the library for a binary classifier experiment using the log loss error function to train the model. This is for a university experiment around benchmarking different models. Would you have time to provide an example of how to use the library to achieve the above goal.
Many thanks,
Best,
Andrew

**Comment by scttl** [comment]
You can get most of the way to your goal starting from [examples/mnist_mlp.py](https://github.com/NervanaSystems/neon/blob/master/examples/mnist_mlp.py) so I suggest starting there.  Since this sounds an awful lot like a homework question, I'll leave the modifications as an exercise for the poster.
