### ISSUE TITLE
Reduce recurrent layer CPU overhead

### ISSUE THREAD

**Issue by buriy** [NervanaSystems/neon#217]
Hi devs,

Am I right that at the moment all recurrent layers run consequently by one time step at a time?
At the moment,  when the number of steps is large (I have time steps=250), a lot of time is spent on a lot of small operations, that mostly consume CPU time and GPU is almost not busy. I think the slowdown is a factor of 5-10 for my case.
Do you consider improving it in the nearest future?

**Comment by yinyinl** [comment]
You are right, and we are working on reducing the slowdown due to time unrolling. But we are not able to give you an exact date on when that will be available for the public yet. Thanks.

**Comment by thestew42** [comment]
This CPU overhead issue is resolved for limited cases in our recent v1.5 release. We have implemented persistent RNN and looping GEMM kernels for BiRNN layers when the activation function is Rectlinclip. These kernels should greatly improve performance in the cases where they can be used. If you have a specific case which is not covered by these kernels yet (different activation function or layer type) we can consider adding support to a future release.

**Comment by jennifermyers** [comment]
@buriy, I'm going to close this for now. Please reopen if you still see issues with v1.5.1. Thanks!

**Comment by buriy** [comment]
Cool! Is there any docs on this?
