### ISSUE TITLE
How to use my own dataset 

### ISSUE THREAD

**Issue by lglhuada** [NervanaSystems/neon#22]
I would like to use my own text data to train a model. I have read the information here http://neon.nervanasys.com/docs/latest/datasets.html

(1)Unfortunately I haven't understood how to transform text data into the required format, it seems that the datasets should be available with URL information. My data is in my local disk.
(2) What is the required data format, especially for text data? 

Any help is more than welcome. Thanks.

**Comment by ursk** [comment]
Text, and more generally, temporal sequence datasets are handled a bit differently in neon from image datasets (what the example in the documentation refers to). You can use the Moby Dick dataset as a template, and adapt it to use your own data. To get started, look for `indat = self.read_txt_file(repo_file, 'float32')` in mobydick.py and replace `repo_file` by your own text file. This dataset assumes that all your data is in one long string, and it will break it up into minibatches for you.

**Comment by lglhuada** [comment]
@ursk Thanks for your answers, it is clear now. So all vectors in my text data should have the same dimension.

**Comment by ursk** [comment]
@lglhuada we added a bit more documentation to the RNN about how the data is expected to be laid out, have a look at http://neon.nervanasys.com/docs/latest/generated/neon.models.rnn.RNN.html#neon.models.rnn.RNN

**Comment by lglhuada** [comment]
@ursk WOW, That's great! Thanks for your help.
