### ISSUE TITLE
kernel declaration differs from its actual calling arguments

### ISSUE THREAD

**Issue by ming-wei** [NervanaSystems/neon#220]
From `neon/backends/kernels/ptx/sconv_fprop_K128_N128.ptx`, we can see there is a parameter called `param_CRST`, which I think is supposed to represent `C*R*S*T`. However, in the actual calling code in `neon/backends/convolution.py` line 130, the argument is `K*R*S*T`. 

Is it a typo or something? I believe the ptx declaration (which is generated from `neon/backends/kernel_specs.py`) should be `param_KRST` instead.

**Comment by scott-gray** [comment]
You're right, it should be KRST in kernel_specs.  But as it's coded now,
those params are never actually used by name.  They're just there to
generate the signature.  Then the kernels are called with the driver api
and a packed struct.

In bprop, K and C are swapped so it is correct there.  Anyway, I'll change
it for better consistency.

I'll have a brand new set of more flexible direct conv kernels out soon.
