### ISSUE TITLE
how to use mul gpus on running mnist_mlp.py

### ISSUE THREAD

**Issue by kwangjun14** [NervanaSystems/neon#226]
Hi
I have two GPUs (gtx980) on my box
When I run the mnist_mlp.py, the  programs uses only one gpu to train the model.
I used option -b gpu when I run it
How to make it use two GPUs ?
thx

**Comment by apark263** [comment]
mnist_mlp runs at .68s per epoch.  you need it to run faster?

in all seriousness, we haven't released multi-gpu support for neon.  for now it is a cloud only feature.  things may change in the future.
