### ISSUE TITLE
Multiple inputs / outputs of the neural network in neon

### ISSUE THREAD

**Issue by iaroslav-ai** [NervanaSystems/neon#228]
Assume that I want to define a neural network that is used to detect whether a patient has a cancer.
As inputs for such network I want to have:
* image from MRI scan, 
* description of patients symptoms as a text
* blood test results (fixed size real vector)

As an outputs, I want to have:
* Categorical value which say whether a patient is healthy or the type of suspected cancer.
* Real value, which for ill patients on scale 0.0 -> 1.0 denotes urgency of treatment, and is 0 for healthy patients.

I cannot change or drop inputs, and I cannot have multiple networks for every output.
Can I define a computational graph with such multiple inputs / outputs using high level functions of neon and perform its training?
If not, could you give me a hint what should be done to implement this using neon backend (define custom layers etc?).

**Comment by iaroslav-ai** [comment]
With the last question regarding implementation with neon backend I mostly want to get an idea of how complicated it would be.

**Comment by iaroslav-ai** [comment]
Well, basically I want to know whether it is hard to deal in neon with complex inputs, the example is made up :) I did not found so far a definite answer in the docs

**Comment by mwoodson1** [comment]
You can take a look at `mnist_merge.py` and `mnist_branch.py` in the examples provided. You can have 3 pathways that get merged and then split into multple branches with one for each output you desire. While this may work I can't guarantee how well it will work for what you want to do.

**Comment by iaroslav-ai** [comment]
Thanks for the pointer! I will look into it.
