### ISSUE TITLE
BatchNorm for recurrent layers?

### ISSUE THREAD

**Issue by buriy** [NervanaSystems/neon#229]
http://arxiv.org/abs/1603.09025

Shouldn't be hard to implement, right?

**Comment by yinyinl** [comment]
Seems great techniques for LSTM! If you look at neon LSTM implementation, you can see clear steps of getting the "inputs to hidden" pre-activations, and do the time unrolling for hidden-hidden activations. According the paper, 2 separate BN operations need to be applied on each of the sources. Then there are extra variables to keep track of the BN statistics, and parameters for BN (especially the careful initialization proposed in this paper) needed to be added into the layer. 
Let us know if you run into more questions.

**Comment by jennifermyers** [comment]
Closing this - let us know if you have more questions.
