### ISSUE TITLE
fatal error: cuda.h: No such file or directory

### ISSUE THREAD

**Issue by iaroslav-ai** [NervanaSystems/neon#230]
During execution of `make sysinstall`, I get

```
Building loader.so...
In file included from reader.hpp:31:0,
                 from loader.hpp:28,
                 from loader.cpp:19:
buffer.hpp:18:18: fatal error: cuda.h: No such file or directory
 #include <cuda.h>
                  ^
compilation terminated.
make[1]: *** [loader.so] Error 1
make: [neon/data/loader] Error 2 (ignored)
```

In both PATH and LD_LIBRARY_PATH I have added location to cuda include folder where cuda.h is located, but this did not help.
I need loader.so to be compiled, otherwise I get exception during execution of batch_writer.py.
Help is greatly appreciated :)

**Comment by hanlin-nervana** [comment]
Happy to help. Can you edit the makefile to echo `$CUDA_ROOT` and rerun the `make sysinstall` command? Thanks!

**Comment by iaroslav-ai** [comment]
Sorry I did not respond for so long. I actually reinstalled my whole system shortly after I posted the issue, and now I have no problems with building the loader.so. I think for now it makes sense to close the issue, and maybe reopen it if someone experienced similar issues as I did.
