### ISSUE TITLE
AssertionError assert n == C.shape[1]: how to use the model predict on single data?

### ISSUE THREAD

**Issue by mingwugmail** [NervanaSystems/neon#235]
https://groups.google.com/forum/#!topic/neon-users/QAXdrx5kOfw

Hi,

I continue experimenting the mnist_mlp.py (after read https://groups.google.com/forum/#!searchin/neon-users/fprop/neon-users/Dabuoj6PjRk/ektZ8BrlDAAJ)

I didn't change anything, but only add the following at the end of the code:

be = gen_backend(backend=args.backend,
                 batch_size=1,
                 rng_seed=args.rng_seed,
                 device_id=args.device_id,
                 datatype=args.datatype,
                 stochastic_round=False)

test = be.array(X_test[:1].T.copy())

preds = mlp.fprop(test, inference=True)

but I got:

"/neon/neon/backends/nervanagpu.py", line 1270, in compound_dot
    assert n == C.shape[1]
AssertionError

What's going wrong? Can anyone help me on this?

Thanks.

**Comment by mingwugmail** [comment]
If I use args.batch_size

be = gen_backend(backend=args.backend,
                 batch_size=args.batch_size,
                 rng_seed=args.rng_seed,
                 device_id=args.device_id,
                 datatype=args.datatype,
                 stochastic_round=False)


test = be.array(X_train[:args.batch_size].T.copy())

preds = mlp.fprop(test, inference=True)
print preds.transpose().get()[0]

and run with $mnist_mlp.py -b cpu, it worked.

But with $mnist_mlp.py -b gpu, it errors out:

"neon/neon/backends/nervanagpu.py", line 904, in _set_rand_state_dev
    drv.memcpy_htod(rand_state, state)
pycuda._driver.LogicError: cuMemcpyHtoD failed: an illegal memory access was encountered

So where are two issues:
1) why it doesn't work on gpu?
2) how to call fprop on single data?

**Comment by mingwugmail** [comment]
model have a model.eval(dataset, metric) method, can it also provide a model.predict(data) method?

**Comment by ursk** [comment]
Closing as duplicate. Answer on Google Groups refers to https://github.com/NervanaSystems/meetup/blob/master/cifar_example.ipynb for single image inference example.

**Comment by mingwugmail** [comment]
DataIterator is gone in Neon 1.8, how this code should be changed to?

https://github.com/NervanaSystems/meetup/blob/master/cifar_example.ipynb
inference_set = DataIterator(x_new, None, nclass=nclass, 
                             lshape=(3, 32, 32))

**Comment by hanlin-nervana** [comment]
Hello, that repository is no longer maintained. Please see https://github.com/NervanaSystems/neon_course for notebooks that are updated to use neon v1.8.
