### ISSUE TITLE
provide network layout before training

### ISSUE THREAD

**Issue by mingwugmail** [NervanaSystems/neon#237]
https://groups.google.com/forum/#!topic/neon-users/f0YyWD2yLaE

I called just before mlp.fit() in examples/mnist_mlp.py

print mlp

it errors out:

...
"../neon/neon/layers/layer.py", line 771, in __str__
    self.name, self.nin, self.nout)
AttributeError: 'Linear' object has no attribute 'nin'

call after mlp.fit() works.

But I want to exam the network before the training start to watch for any unexpected numbers; after training it's too late (also considering training typically takes long time).

**Comment by mingwugmail** [comment]
as in Torch7: print network layout, and each layer's shape

nn.Sequential {
  [input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> (11) -> output]
  (1): nn.SpatialConvolutionMM(1 -> 32, 5x5)
  (2): nn.Tanh
  (3): nn.SpatialMaxPooling(3,3,3,3)
  (4): nn.SpatialConvolutionMM(32 -> 64, 5x5)
  (5): nn.Tanh
  (6): nn.SpatialMaxPooling(2,2,2,2)
  (7): nn.Reshape(256)
  (8): nn.Linear(256 -> 200)
  (9): nn.Tanh
  (10): nn.Linear(200 -> 10)
  (11): nn.LogSoftMax
}

**Comment by hanlin-nervana** [comment]
Hello,

In that case, the `-v` verbose flag should meet your needs, as it prints the network layout right before training. Alternatively, you can first initialize the model by calling `mlp.initialize(train_set, cost)`, which will configure all the layer shapes. Then, you can inspect the network via `print mlp`.

Hanlin

**Comment by jennifermyers** [comment]
Hi @mingwugmail - I'm going to close this issue. Please let us know if you have any problems with the suggestions Hanlin outlined!
