### ISSUE TITLE
error on install in new or existing venv

### ISSUE THREAD

**Issue by szeitlin** [NervanaSystems/neon#238]
can't import the package. I installed all the requirements and vis_requirements successfully. 

`import neon` or any variation of that yields this:

```
ERROR: Version information not found.  Ensure you have built the software.
    From the top level dir issue: 'make'
```

Tried several different ways, following the instructions for conda and pip, ran make with no errors, but still getting the same error when I try to actually use it. 

It's not really typical behavior for a python package to expect a makefile to run. From what I can tell of the Makefile contents, it's just looking for a path with the version number. I can see that neon seems to be installed, version 1.4.0. I didn't see this in the FAQ - has anyone else had this problem? I can try hacking the Makefile to just hard-code in the version number and see how that goes, but I'm completely blocked from using the library in the meantime.

**Comment by hanlin-nervana** [comment]
Hello,

That error arises either because the virtual environment was not activated, or `neon/version.py` doesn't exist. That file is created as part of the makefile install. neon isn't a pure python package, and the makefile is required to compile our GPU kernels and our C++ dataloading library.

Can you try a clean virtualenv install by cloning neon, and then issuing `make` from the neon directory? You can test the install by first activating the virtual environment and then running the MNIST example. Here is the sequence of commands:

```
git clone https://www.github.com/NervanaSystems/neon.git
cd neon
make
. .venv/bin/activate
./examples/mnist_mlp.py
```

Thanks!

**Comment by szeitlin** [comment]
No, I can't. I tried that. The default python in my path is python3, which your library doesn't support.

It should be possible to install the dependencies inside an existing venv. Otherwise, I would need to change the makefile so it adds python 2.7 when it creates the venv.

**Comment by hanlin-nervana** [comment]
Good point, we should add some python version checking to the virtual env install. Thanks for your suggestion.

To install within an existing venv, activate the virtual env, then run `make sysinstall`. Neon will install the dependencies in your virtual environment’s python folder.

**Comment by szeitlin** [comment]
Thanks, I tried that. It didn't work. That's why I opened this issue.

**Comment by hanlin-nervana** [comment]
OK to help diagnose the issue, can you modify the makefile to install a python2.7 venv (or use a sysinstall inside a py2.7 virtualenv), and then share the install logs and the stack trace when you run `./examples/mnist_mlp.py`?

**Comment by szeitlin** [comment]
ok, will do.

**Comment by szeitlin** [comment]
fwiw, now I'm trying to walk through the MNist tutorial and I can't proceed. 

```

In [10]:

# setup training set iterator
train_set = ArrayIterator(X_train, y_train, nclass=nclass)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-046ef325b62e> in <module>()
      1 # setup training set iterator
----> 2 train_set = ArrayIterator(X_train, y_train, nclass=nclass)

/Users/szeitlin/mystuff/neon/neon/neon/data/dataiterator.pyc in __init__(self, X, y, nclass, lshape, make_onehot, name)
     76         X = X if isinstance(X, list) else [X]
     77         self.ndata = len(X[0])
---> 78         assert self.ndata >= self.be.bsz
     79         self.start = 0
     80         self.nclass = nclass

AttributeError: 'NoneType' object has no attribute 'bsz'
```

**Comment by hanlin-nervana** [comment]
Great that you were able to get the install working, although if you have the stack trace and install log for the failed `sysinstall` to share, that would be helpful for us to diagnose.

I was unable to reproduce your error with the MNIST tutorial. That error occurs if the backend has not been initialized yet. The backend is generated at this line: `args = parser.parse_args()` in the tutorial (preamble section). After executing that line, you can check that the backend was properly generated via:
```
from neon import NervanaObject
NervanaObject.be
```
You should see [for CPU]: `<neon.backends.nervanacpu.NervanaCPU at 0x1061e3ed0>`

**Comment by jennifermyers** [comment]
Hi @szeitlin, I'm going to close this old issue assuming that Hanlin's suggestion was able to get you past the issue with the MNIST tutorial. Please feel free to reopen if you are still having a problem.
