### ISSUE TITLE
Partial Connections in Implementation of LeNet

### ISSUE THREAD

**Issue by ankitp94** [NervanaSystems/neon#239]
Hi everyone,
I am trying to implement LeNet 5 on neon.
For reference, I am following the slides from Dr. Aarti Singh (CMU). http://www.cs.cmu.edu/~aarti/Class/10701_Spring14/slides/DeepLearning.pdf 
On page 17, It is mentioned that 2nd Convolutional layer(C3) is not connected to every feature map from previous layer(S2).  Each feature map of C3 is connected to only subset of feature maps of S2 (given in Table 1)

![image](https://cloud.githubusercontent.com/assets/4333418/15109661/22b3baea-15fa-11e6-848a-0300b783e101.png)

By default, neon will have connections to every feature map of S2. Extreme of the proposed approach would be if all these subsets were disjoint.

I went through mnist_merge,py but the vertical stacking doesn't seem helpful here.

What steps should I take to implement this in neon ? 
Any example/reference implementation would be really helpful.
Thanks!

**Comment by hanlin-nervana** [comment]
Implementing arbitrary partial connections within neon can be quite tricky and not recommended. From the [LeNet](http://vision.stanford.edu/cs598_spring07/papers/Lecun98.pdf) paper, they motivate their proposed approach via:

```
Why not connect every S3 feature map to every C2 feature map? The reason is twofold. First a noncomplete connection scheme keeps the number of connections within reasonable bounds
More importantly it forces a break of symmetry in the network. Different feature maps are forced to extract different hopefully complementary features because they get different sets of inputs.
```

Modern hardware can run efficiently on the fully connected network, and the second rationale (symmetry-breaking) can be achieved with random weight initialization and/or dropout layers. I would recommend first trying a LeNet implementation without worrying about the partial connections.

**Comment by ankitp94** [comment]
Hi @hanlin-nervana 
Thanks for the feedback. 
What you say makes a lot of sense. 
I was not implementing LeNet for its performance but for its historical significance.
Without partial connections, the implementation is very easy and straight-forward with neon (Great work by the team! Cheers).

I want to try/propose new type of architectures  for academic research purposes and that would require flexibility in terms of  layers connections (example [Semi-Supervised Learning with Ladder Networks](http://arxiv.org/abs/1507.02672) ) , different cost functions ([Bridge Correlational Neural Networks for Multilingual Multimodal Representation Learning](http://arxiv.org/abs/1510.03519) uses correlation of minibatch in cost ) etc.
Would you suggest using a different library for trying new flexible architectures ?

**Comment by hanlin-nervana** [comment]
neon exposes a backend API of numpy-like calls that can be used to define custom layers/costs relatively easily, so I would certainly recommend you give the library a try. We also have containers to build flexible tree/merge architectures. Please let us know if you run into any issues.
