### ISSUE TITLE
Add Docker images

### ISSUE THREAD

**Issue by kylef-lab41** [NervanaSystems/neon#24]
Installation requires several configuration options and dependencies, some of which must be built from separate repos.  Encapsulating neon within a Docker image would help newcomers get started, provide an isolated environment, and enable deployment portability.

**Comment by scttl** [comment]
Hi Kyle,

Per #19 @Kaixhin has already created some docker images for neon which you can find from:
* [base cpu neon](https://registry.hub.docker.com/u/kaixhin/neon/)
* [nervanagpu neon](https://registry.hub.docker.com/u/kaixhin/nervanagpu-neon/)
* [cudanetgpu neon](https://registry.hub.docker.com/u/kaixhin/cudanet-neon/)

**Comment by Kaixhin** [comment]
If my Docker images suffice then I'd be happy to have them referenced somewhere in the readme. If there are any problems I would recommend raising an issue on the [source repo](https://github.com/Kaixhin/dockerfiles) as it might affect other images I provide for the deep learning community.

**Comment by kylef-lab41** [comment]
@Kaixhin @scttl These are great. I searched Docker's registry last week for an existing image - the CUDA version didn't show up (not sure why...maybe I just missed it), so I think it would be very helpful to reference these in the Readme or even include/submodule in neon itself.

**Comment by scttl** [comment]
Thanks for the commits @kylef-lab41 and @Kaixhin!  I've accepted a slightly modified version of #27 so that users can more easily find these images going forward (documented from our main installation page, and linked to in the README and Quickstart pages).

**Comment by Kaixhin** [comment]
Looks good to me :+1:
