### ISSUE TITLE
How to cite winograd kernels?

### ISSUE THREAD

**Issue by hughperkins** [NervanaSystems/neon#242]
Hi,

How to cite winograd kernels?

**Comment by hughperkins** [comment]
Would it be http://arxiv.org/abs/1509.09308 ?

**Comment by scott-gray** [comment]
That's fine.  Or a link to neon if you're talking very specifically about our implementation.

**Comment by hughperkins** [comment]
Ok.  Thanks!

> Or a link to neon if you're talking very specifically about our implementation.

Hmmm.  Well... I'm basically saying something like:

"CUDNN implementation is proprietary, so we cannot reason well on how it works, and what we can learn from it. However, Gray has provided descriptions of how the Winograd kernels work, and the Winograd kernels provide similar, or better, performance to CUDNN.

"Winograd is not written in CUDA, but in low-level assembler.  Gray asserts that the performance of Winograd could not be obtained without using low-level assembler.  It seems plausible that to reach
the same performance on AMD and Intel hardware, we would need a similarly low-level implementation."

**Comment by scott-gray** [comment]
cuDDN v5 has a F(2x2,3x3) implementation now, though it's quite a bit slower than our F(2x2,3x3).  And of course we also have F(4x4,3x3) which cuDNN will also eventually have.  I'm also working on kernels for 5x5 and 7x1 filters.

Anyway, just site both then.

**Comment by hughperkins** [comment]
Cool.  Thanks! :-)

**Comment by hughperkins** [comment]
(hmmmm, seems this comment https://www.reddit.com/r/MachineLearning/comments/4e5g6z/implementing_custom_convolution_kernels/d1xk3tn is a good source for my assertion about your assertion, though not sure I can actually cite that in a paper, but at least my assertion about your assertion is not entirely without evidence :-) )

**Comment by hughperkins** [comment]
Just to confirm, is it the case that:
- Winograd kernels are using direct convolution? (cf im2col, fft, or some other blas-based implementation for example)
- given that cuda-convnet demonstrated that direct convolutions provide excellent performance, on very specific geometries, but generalize poorly to other geometries, is it the case that Winograd provides multiple kernel implementations, each for one or more families of geometries?  Which families of geometries are implemented?  Is it the case that some families of geometries would obtain better performance using im2col+cublas and/or fft+cublas and/or are not currently implemented?

**Comment by hughperkins** [comment]
Hmmm, Scott, skimming through the Lavin and Gray paper, which I confess I havent yet read, and probably should do, it looks like a huge performance gain is algorithmic?  And that using standard CUDA kernels, based on your numbers on https://github.com/NervanaSystems/maxas/wiki/Introduction , the performance might approach around 70-75% of the performance of the current Winograd SASS kernels? And therefore, and I know this is getting a bit speculative, if we assume a performance drop for OpenCL vs CUDA for around 33-50%, we might be able to get convolutional performance on OpenCL approaching around ~30% that of the Winograd kernels, simply by porting the Lavin and Gray algorithms into OpenCL?

**Comment by scott-gray** [comment]
In that reddit post I said this:

> Shader assembly (sass) level programming is essential for this task to get the most performance, and even required for some of the more complicated kernels that are extremely resource tight.

The fastest winograd implementations will be partially or fully fused (transforms + batched gemm).  But you could still get decent speed doing a non-fused version in cuda-c or opencl and just use a basic batch gemm BLAS call.

**Comment by hughperkins** [comment]
Ok.  Concerned that the performance is going to be limited by the BLAS implementation, I hacked around a bit on neon, to find out how/where gemm is being used, on a Maxwell device.  It looks like two kernels take up approximately 50% of the time each:

- sconv_winograd_4x4_3x3_32x32
- xprop_image_trans_4x4

![neondabbling1](https://cloud.githubusercontent.com/assets/123560/15457389/4cf38444-2080-11e6-81d1-02a59f05f444.png)

I instrumented `nervanagpu.compound_dot` and `nervanagpu.batched_dot`, which were the only functions I found using cublas?, to have a `print` statement at the start of each, but these `print` statements were never triggered.

I entirely emptied the `neon/backends/kernels/ptx` directory, renamed `sass` to `sass.disabled` (I know this is only used during `make`, but still), and removed everything from `cubin` directory except for `sconv_winograd_4x4_3x3_32x32_*.cubin`, and everything continued to run ok.

`xprop_image_trans_4x4_kernel` on the other hand seems to be embedded in `winograd_conv.py`

Seems like somewhat plausible that I just need to write an appropriate generator to create appropriate OpenCL for these two kernels, and then OpenCL convolution will run ok?  Or I'm missing a whole bunch of stuff/concepts?  (I still didnt quite read the paper yet I confess...)

**Comment by hughperkins** [comment]
Ah... on Kepler, commenting out `cublas` declaration causes it to fail, so it seems like:
- gemm is still needed?
- on Kepler, you are using cublas for gemm?
- on Maxwell, you've written an entire gemm implementaiton in sass :-O

So, my options, for non-CUDA hardware are:
- use an existing gemm implementation (clblas, viennacl, clblast)
- write my own gemm implementation, dedicated for the needed geometries
- port your sass gemm to opencl (via search and replace??? but seems like 64-bit operations are split across multiple operations... anyway...might take a peek)

Question: thoughts on the extent to which your acceleration is due to:
- algorithm (ie Winograd) ?
- writing gemm in sass?
- other bits being written in sass? (`trans` sounds like it's doing a fair amount of work?)
- other stuff?
