### ISSUE TITLE
doc improvement: ArrayIterator __init__ y

### ISSUE THREAD

**Issue by mingwugmail** [NervanaSystems/neon#244]
http://neon.nervanasys.com/docs/latest/generated/neon.data.dataiterator.ArrayIterator.html?highlight=arrayiterator

currently it reads:
y (ndarray, shape:[# examples, 1], optional) 

better specify the shape in 3 scenarios:

[# examples, 1] for classification problems
[# examples, output feature size] for regression problems
If absent, the input features themselves will be returned as target values (AutoEncoder)

**Comment by jennifermyers** [comment]
Thanks for reporting this! This will be fixed in the documentation for our imminent v1.5.0 release.
