### ISSUE TITLE
provide better wrapper than ArrayIterator for user data

### ISSUE THREAD

**Issue by mingwugmail** [NervanaSystems/neon#250]
This is related to:
https://github.com/NervanaSystems/neon/issues/249

take /neon/examples/timeseries_lstm.py for example:

in DataIteratorSequence:

        self.X_dev = self.be.iobuf((self.nfeatures, time_steps))
        ....
        self.X = self.X.reshape(Xshape).transpose(1, 0, 2, 3)

these code are related to device (GPU) memory implementation detail, the ordinary Neon user (e.g. me) knows nothing about how the GPU memory is organized, that's why I use a library such as Neon. Why should I concerned about this? especially those magic number in .transpose(1, 0, 2, 3), how do I know if I did the correct thing, or made a mistake?

The current ArrayIterator only can hold data in the memory, my data is:
1) dynamically genereted
2) doesn't fit memory

I hope Neon provide better wrapper for user data. This will help many users like me.

Thanks.

**Comment by mingwugmail** [comment]
Related discussion here:

https://groups.google.com/forum/#!topic/neon-users/hMTRAT4Hf4M

￼==================================================================
jdh...@colby.edu 	￼￼Jun 24
￼Hello,

I am developing a network that is trained using reinforcement learning, and I need to input two streams of data into the Model.fprop, which then get merged after a sequence of layers before the output. At each time step, I have an MxM image and an N dimensional state vector. I need to load them separately, so that the image can be run through a sequence of convolutional layers before being merged with the state vector for the fully connected layers. I have checked the mnist_merge.py and mnist_branch.py examples, but they don't address the issue of loading two different data vectors simultaneously. Is there a way to load data like this?

Thank you,
Josh

￼==================================================================
On Friday, June 24, 2016 at 5:04:06 PM UTC-7, han...@nervanasys.com wrote:
Hi Josh,

Thanks for your question. Take a look at our image_caption.py example that demonstrates how to use neon's MergeMultistream container for handling the merging of multiple streams of data.

Hanlin


￼==================================================================
Are you referring to 

https://github.com/NervanaSystems/neon/blob/master/neon/data/imagecaption.py#L217

                prob = model.fprop((x[0], y), inference=True).get()[:, :-self.be.bsz].copy()

It feed a tuple to model.fprop. and y is init-ed to:

        y = self.be.zeros(self.dev_X.shape)


But in Neon doc: http://neon.nervanasys.com/docs/latest/generated/neon.models.model.Model.html?highlight=model.fprop#neon.models.model.Model.fprop

it says:

fprop(x, inference=False)[source]
Forward propagates a minibatch x through the model.

Parameters:	
x (Tensor) – Input minibatch data

and if you click Tensor, it refers to neon.backends.backend.Tensor

I think there are 2 issues here:

1) the Neon doc need to be more accurate; it clearly not only accept Tensor, but also some tuple type, (maybe also other types?)
2) all these self.be.zeros, self.be.iobuf backend device types are difficult for *library user* to master. I guess Neon choose to do it this way for performance reason. But as *library user*, I don't want to know such implementation detail. I just want to prepare my data as (MxM matrix, N vector) in this particular example, and pass it to model.fit() or model.fprop(). I think Neon should provide a better API in this case (maybe via s thin wrapper which I don't care as a *library user*).

**Comment by hanlin-nervana** [comment]
Hello,

Supplying a tuple instead of a tensor is used with multiple input/outputs. We will amend the API to reflect this. Thanks for bringing this to our attention.

If your data is being generated dynamically for each minibatch, then I'm afraid the only route is to write a custom dataset object that will load the generated data into the GPU and provision those buffers to the model. We've developed a notebook [here](https://github.com/NervanaSystems/neon_course/blob/master/03%20Writing%20your%20own%20dataset.ipynb) to guide users through this process.

I am closing this issue for now. Feel free to reopen if you have issues implementing the above.
