### ISSUE TITLE
making neon with cuda on OS X

### ISSUE THREAD

**Issue by glebreutov** [NervanaSystems/neon#253]
I trying to build neon with Cuda support but getting this error:

    ld: warning: directory not found for option '-L/usr/local/cuda/lib64'
    ld: warning: directory not found for option '-L/usr/local/cuda/lib64/stubs'
    ld: warning: directory not found for option '-L/usr/local/cuda/lib64'
    ld: warning: directory not found for option '-L/usr/local/cuda/lib64/stubs'
    ld: file not found: @rpath/CUDA.framework/Versions/A/CUDA for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'clang++' failed with exit status 1
    ----------------------------------------
    Command "/Users/glebreutov/Py/venv/bin/python2.7 -u -c "import setuptools,     tokenize;__file__='/private/var/folders/xp/wzb6ncc17hx60fswc0912szh0000gn/T/pip-build-kwYckp/pycuda/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/xp/wzb6ncc17hx60fswc0912szh0000gn/T/pip-tYX_6o-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/glebreutov/Py/venv/bin/../include/site/python2.7/pycuda" failed with error code 1 in /private/var/folders/xp/wzb6ncc17hx60fswc0912szh0000gn/T/pip-build-kwYckp/pycuda/
make: *** [sysdeps] Error 1`

Seems, that happens because the last version of Cuda  has no lib64 directory. Is there some workaround?

Details: OS X El Capitan, NVIDIA GeForce GT 750M

**Comment by jennifermyers** [comment]
Hi @glebreutov,

Please try building with the CUDA_ROOT set, that is:

`make CUDA_ROOT=/usr/local/cuda`

Then also make sure to include the CUDA directories in your PATH and DYLD_LIBRARY_PATH environment variables as follows:

```
export PATH=/usr/local/cuda/bin:$PATH
export DYLD_LIBRARY_PATH=/usr/local/cuda/lib:$DYLD_LIBRARY_PATH
```

**Comment by jennifermyers** [comment]
A fix to the Makefile will also be made in the next release so the setting of CUDA_ROOT is not necessary.
