### ISSUE TITLE
There is both nervanasystems and nervanasys, kind of confusing :-)

### ISSUE THREAD

**Issue by hughperkins** [NervanaSystems/neon#254]
There is both nervanasystems and nervanasys, kind of confusing :-)

I think you should remove/rename nervanasys, to reduce confusion.

**Comment by jennifermyers** [comment]
Hi Hugh,

Do you mean that there is both http://github.com/nervanasystems/neon and https://github.com/nervanasys/neon ? 

If so, the latter is not the official one and I can talk to the owner (Arjun) about whether to rename or remove it.

Thanks!

**Comment by hughperkins** [comment]
> Do you mean that there is both http://github.com/nervanasystems/neon and https://github.com/nervanasys/neon ? 

yes, exactly :-)

**Comment by jennifermyers** [comment]
OK, great! Arjun has removed his fork of neon, so now we just have http://github.com/nervanasystems/neon :-)

**Comment by hughperkins** [comment]
Cool.  That was quick! :-)
