### ISSUE TITLE
when install on ubuntu 14.04 /usr/bin/ld: cannot find -lippicv

### ISSUE THREAD

**Issue by fucusy** [NervanaSystems/neon#255]
already install all the dependency by apt-get:
`sudo apt-get install libhdf5-dev libyaml-dev libopencv-dev pkg-config`
`sudo apt-get install python python-dev python-pip python-virtualenv`

next,
`git clone https://github.com/NervanaSystems/neon.git`
`cd neon`
`make`
then error occurs:

Finished processing dependencies for neon==1.3.0
######################
Setup complete.  Type:
    . '.venv/bin/activate'
to work interactively
######################

Building loader.so...
/usr/bin/ld: cannot find -lippicv
collect2: error: ld returned 1 exit status
make[1]: *** [loader.so] Error 1
make: [neon/data/loader] Error 2 (ignored)

**Comment by jennifermyers** [comment]
This may be an issue with OpenCV - see https://github.com/opencv/opencv/issues/5852

Can you retry with a more recent version of OpenCV and neon (1.5.3 is latest).

**Comment by Cpruce** [comment]
I solved this by downloading the ippicv lib

https://sourceforge.net/projects/opencvlibrary/files/3rdparty/ippicv/

and copying the appropriate files like so

/usr/local/opencv/libippicv.a
/usr/local/include/opencv/ippicv_types.h
/usr/local/include/opencv/ippicv_redefs.h
/usr/local/share/OpenCV/3rdparty/lib/libippicv.a

I also added the line 

/usr/local/opencv/

to /etc/ld.so.conf.d/opencv.conf (had to create this).

After that, run `sudo ldconfig`. The creates a new location for that static library and tells the linker to look for that in the opencv dir.

Hope this helps!
