### ISSUE TITLE
Why is dim_shuffle so complicated?

### ISSUE THREAD

**Issue by hughperkins** [NervanaSystems/neon#260]
Seems like the dim_shuffle in https://github.com/NervanaSystems/neon/blob/master/neon/backends/convolution.py#L927 is overly complex?  Since its only being used to change eg `CRSTK` into `KRSTC`, we can implicitly reshape the tensor as `CBK`, where `B` == `RST`, and rewrite the kernel as:

https://github.com/hughperkins/neonCl-underconstruction/blob/298822ba6fc25d4a347b3e59ca192fbf43aa32be/winogradcl/backends/kernels/cl/clshuffler.py#L10

```
kernel void dimShuffle(
    global %(type)s* out, global const %(type)s* in,
    int BC, int C,
    int AB, int A)
{
    local %(type)s tile[32][33];
    int tx  = get_local_id(0);
    int ty  = get_local_id(1);
    int gx  = get_group_id(0);
    int gy  = get_group_id(1);
    int b = get_group_id(2);
    int c  = gx * 32 + tx;
    int a  = gy * 32 + ty;
    for (int j = 0; j < 32; j += 8)
    {
        int a_plus_j = a + j;
        if (a_plus_j < A && c < C)
            tile[ty + j][tx] = in[ a_plus_j*BC + b * C + c ];
    }
    barrier(CLK_LOCAL_MEM_FENCE);
    c = gx * 32 + ty;
    a = gy * 32 + tx;
    for (int i = 0; i < 32; i += 8)
    {
        int c_plus_i = c + i;
        if (c_plus_i < C && a < A)
            out[ c_plus_i*AB + b*A + a ] = tile[tx][ty + i];
    }
}
"""
```

What am I missing here?

**Comment by scott-gray** [comment]
When bprop is cast as fprop upside down, you also need to mirror RST.  You could do that inside of the conv kernel but that would add extra logic, where adding it here is just tacking it onto an already bandwidth bound operation at no cost.  Plus in when your stride is 1 you can use the fprop kernel with no changes.  This comes in handy for winograd where the stride has to be 1 and cuts out a whole kernel you need to implement.

**Comment by hughperkins** [comment]
Ah!  Makes sense.  Thanks! :-)
