### ISSUE TITLE
Persistent RNNs

### ISSUE THREAD

**Issue by oleg-trott** [NervanaSystems/neon#262]
[Baidu found a way to get decent throughput in RNNs at very low batch sizes (like 4).](http://jmlr.org/proceedings/papers/v48/diamos16.pdf)

It would be interesting to see that in Neon/NervanaGPU

**Comment by jennifermyers** [comment]
Hi Oleg,

Thanks for the note! We have added support for this internally and it is currently in test. We expect to release it in an upcoming version of neon - possibly not the imminent 1.5 release, but likely by 1.6.

**Comment by oleg-trott** [comment]
That was fast. I thought that paper just came out.

**Comment by thestew42** [comment]
Greg gave a talk at GTC in April on persistent RNN kernels which we have been working to implement.

**Comment by jennifermyers** [comment]
Good news! This is now expected to be part of the imminent v1.5.0 release.
