### ISSUE TITLE
Unable to build in Ubuntu 16.04 using system-installed OpenCV 2.4.9 (aka "2.4v5")

### ISSUE THREAD

**Issue by buriy** [NervanaSystems/neon#265]
Please provide the instructions in the documentation or modify makefiles to not require opencv libs unless it's really necessary.
(OpenCV >=3 is really hard to setup on Ubuntu 16.04 btw)

Building bin/loader.so...
g++ -shared -o bin/loader.so -fPIC -Wall -Wno-deprecated-declarations -O3 -std=c++11 -DHAS_GPU -DHAS_IMGLIB -DHAS_VIDLIB -DHAS_AUDLIB src/loader.cpp -I/usr/local/cuda/include -I/usr/local/include/opencv -I/usr/local/include -L/usr/local/cuda/lib64 -L/usr/local/lib  -lcuda -lcudart -lopencv_cudabgsegm -lopencv_cudaobjdetect -lopencv_cudastereo -lopencv_shape -lopencv_stitching -lopencv_cudafeatures2d -lopencv_superres -lopencv_cudacodec -lopencv_videostab -lopencv_cudaoptflow -lopencv_cudalegacy -lopencv_calib3d -lopencv_features2d -lopencv_objdetect -lopencv_highgui -lopencv_videoio -lopencv_photo -lopencv_imgcodecs -lopencv_cudawarping -lopencv_cudaimgproc -lopencv_cudafilters -lopencv_video -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_cudaarithm -lopencv_core -lopencv_cudev -lavutil -lavformat -lavcodec -lswscale
/usr/bin/ld: cannot find -lopencv_cudabgsegm
/usr/bin/ld: cannot find -lopencv_cudaobjdetect
/usr/bin/ld: cannot find -lopencv_cudastereo
/usr/bin/ld: cannot find -lopencv_shape
/usr/bin/ld: cannot find -lopencv_cudafeatures2d
/usr/bin/ld: cannot find -lopencv_cudacodec
/usr/bin/ld: cannot find -lopencv_cudaoptflow
/usr/bin/ld: cannot find -lopencv_cudalegacy
/usr/bin/ld: cannot find -lopencv_videoio
/usr/bin/ld: cannot find -lopencv_imgcodecs
/usr/bin/ld: cannot find -lopencv_cudawarping
/usr/bin/ld: cannot find -lopencv_cudaimgproc
/usr/bin/ld: cannot find -lopencv_cudafilters
/usr/bin/ld: cannot find -lopencv_cudaarithm
/usr/bin/ld: cannot find -lopencv_cudev
collect2: error: ld returned 1 exit status
Makefile:76: recipe for target 'bin/loader.so' failed
make[1]: *** [bin/loader.so] Error 1

**Comment by hanlin-nervana** [comment]
From the output, looks like your opencv install was not configured with WITHCUDA=ON, leading the makefile not being able to find the cuda-related components of opencv.

To disable the loader makefile from compiling with -DHAS_GPU, comment out lines 46-59
in https://github.com/NervanaSystems/neon/blob/master/loader/Makefile

Alternatively, to skip the loader compilation completely (only necessary for macrobatching loading),  comment out lines 29-40 in the file above.

**Comment by buriy** [comment]
Thanks,
I would like though if you could correct your documentation because right now you have the following in the docs:
"OpenCV is also a required package. We recommend installing with a package manager (e.g. apt-get or homebrew)." at http://neon.nervanasys.com/docs/latest/installation.html , 
and I'm describing you what do you have if you install it with the package manager.
There is no way at the moment to install OpenCV binaries with Cuda support in Debian and Ubuntu .

**Comment by hanlin-nervana** [comment]
Revisiting this issue, opencv with Cuda support is actually not required for neon to operate. We try to link with all the libraries specified in `opencv.pc`, so perhaps your `opencv.pc` contained references to the cuda libs that aren't really installed. On Ubuntu 14.04, the normal package install route for opencv is compatible with neon. 

In the upcoming release, opencv will now be an optional install that is only needed to enable neon's dataloader capabilities.

**Comment by vg123** [comment]
How do you fix the above error , asked in the first post. please explain in detail.

**Comment by vg123** [comment]
Ok, I got the solution I just removed all those dependencies from `Makefile` which were not found when I run `make` command. and Yes those `opencv` libraries  were depending on `cuda` which is not installed on my system.
