### ISSUE TITLE
why did  i use 'gpu' modern got wrong answers compared with 'cpu', 'cpu' works well. 

### ISSUE THREAD

**Issue by zengjichen** [NervanaSystems/neon#269]

**Comment by hanlin-nervana** [comment]
Can you provide more information on the command you used and the error message you received? Thanks!

**Comment by zengjichen** [comment]
for example, when i run the file examples/mnist_mlp.py  choose 'gpu',the result on each epoch are error 90.2% and costs never decline,but run in  'cpu',it works well ,and get the good answer, could you give some guide on use 'gpu' ,the tutorials may not introduce completely.. thank you , best wish

**Comment by hanlin-nervana** [comment]
There is likely something wrong with your GPU setup, as we are unable to reproduce your error. What GPU do you have and what operating system are you using?

**Comment by zengjichen** [comment]
thanks for your replay,I solved it by recompiled the neon,and it works well .
