### ISSUE TITLE
make requires specification of Makefile

### ISSUE THREAD

**Issue by ticoneva** [NervanaSystems/neon#272]
In all installation instructions only "make" is mentioned, when "make -f Makefile" or "make sysinstall -f Makefile" would actually be need.

**Comment by jennifermyers** [comment]
Hi ticoneva, 

That is surprising. I am not aware of a make implementation that doesn't look for a file named Makefile by default.

Can you tell me what OS you are on and what version of make (make -v)?

Thanks!
Jennifer

**Comment by ticoneva** [comment]
I am using Ubuntu 15.10 with Anaconda. It was not working the first time, but I just deleted everything and tried again and make does work as stated. Sorry for the false alarm---I have no idea why it did not work the first time.

**Comment by jennifermyers** [comment]
OK - glad to hear it is working now!
