### ISSUE TITLE
Want to get the cubin of the sass kernels

### ISSUE THREAD

**Issue by nomi-wei** [NervanaSystems/neon#273]
AFAIK, the maxas can't build the sass code into cubin directly.
And it seems that neon would generate some ptx files and build them into cubins with the official NV pipeline, then use maxas to make the fine-tuning kernels.

And those fine-tuning kernels are what i want.
I built neon in ubuntu 16.04, following this guidance -http://neon.nervanasys.com/docs/latest/installation.html.
But I didn't find these cubins, after built neon successfully.
So I wonder if you could give me some helps or tips? 
Thanks in advance!

**Comment by thestew42** [comment]
As you said, maxas will use the NV tools to build a basic shell cubin where it can then insert the assembled sass. In the past few months we changed to a system that assembles kernels on the fly which is probably why you can't find them after installing neon. They are no longer built as part of the install process.

If you want to get the cubin files that neon compiles at runtime, you should be able to control the cache where these files are saved with the NEON_CACHE_DIR environment variable. If you want to build a cubin from the sass kernels yourself, you can use maxas directly which is documented here: https://github.com/NervanaSystems/maxas.

**Comment by nomi-wei** [comment]
Hi @thestew42, thanks for your quick reply.

Finally, I did some workaround stuff to get those kernels:
The function `get_kernel` in `kernel_specs.py` should be the entry of building kernels process.
So I wrote a tiny script to call this function with the names of kernels I want.
And yep, that seems work, and I can get the built cubin and dump_sass in the cache dir.

Thanks again! Please help me to close this issues, @thestew42 
And I hope this thread could help other guys who need it.

**Comment by thestew42** [comment]
@jennifermyers can you close this?
