### ISSUE TITLE
Grid LSTM in Neon

### ISSUE THREAD

**Issue by deeplearning-ai-research** [NervanaSystems/neon#274]
Hi,

Just wondering if Multi-dimensionnal Tensor for LSTM ( size= (100,4,6,3)) is available in Neon
(this is the input tensor) as a template and it can be done (multi-dimensionnal cell memory can cause issues).

Those ones are available in TensorFlow and Torch:

https://github.com/coreylynch/grid-lstm

https://github.com/tensorflow/tensorflow/issues/2560

Original papers:
https://arxiv.org/abs/1507.01526

Thanks

**Comment by yinyinl** [comment]
We currently don't support LSTM that takes multi-dimensional tensors like Grid LSTM. The various RNN layers in neon use this [data layout](http://neon.nervanasys.com/index.html/design.html#data-layout). 
Our backends supports multi-dimensional tensors that you can do numerical operations on. So if you decides to construct your own layer type, you can write out the forward and backward processes to handle those multi-dimensional tensors.
