### ISSUE TITLE
What happens to Neon post-Intel?

### ISSUE THREAD

**Issue by campbx** [NervanaSystems/neon#279]
Congratulations guys!  We are looking forward to faster Intel DL solutions now.

I am wondering what will happen to Neon now.  Is it going to be an Intel-backed framework, or is the project going to stop?

Thanks!

**Comment by bhack** [comment]
I think that the strategy it is in the roadmap of open sourcing the DNN part of MKL-DNN soon. But I don't know if all the potentially interesting kernels will be developed proprietary behind MKL (no more Nvidia assembly of course) . Will part of the work a near the metal proprietary cudnn alternative for Xeon/Phi?

**Comment by ursk** [comment]
Nervana intends to continue all existing development efforts including the Nervana Neon deep learning framework, and it is going to stay open source. See our blog post https://www.nervanasys.com/intel-nervana for more details.

**Comment by bhack** [comment]
So What will be your Nvidia assembly strategy?

**Comment by campbx** [comment]
@bhack Nervana is building FPGA accelerator chips which can do 55 TOPS, while NVidia's $10,000 Tesla chip does 44 TOPS.  NVidia is going to feel the heat in Q1 2017 as long as Nervana price it under $5K.

@ursk thanks!

**Comment by bhack** [comment]
Ok but this still doesn't solve maintenance of Nvidia assembly kernels in Neon.
