### ISSUE TITLE
Extracting fc6 activations (video-c3d example)

### ISSUE THREAD

**Issue by saurav111** [NervanaSystems/neon#280]
Can you please guide me on how to get the 2048 dimensional output from the first affine layer in the video-c3d example for a single video file, i.e. batch size 1 during inference?

**Comment by saurav111** [comment]
I'll ask a simpler question. Is there a good way of accessing the activation layer of a hidden layer from any model?

**Comment by hanlin-nervana** [comment]
To access the activation of any hidden layer in the model, call `model.layers`. In our `mnist_mlp.py` example:

```
ipdb> mlp.layers.layers
[<neon.layers.layer.Linear object at 0x7f25e39f5110>, <neon.layers.layer.Activation object at 0x7f25e39f5150>, <neon.layers.layer.Linear object at 0x7f25e39f51d0>, <neon.layers.layer.Activation object at 0x7f25e39f5210>]
```

The above call returns a list of layers of the model. Each layer has the `outputs` attribute which contains the activations. For example, `mlp.layers.layers[0].outputs` returns a `GPUTensor` with the activation of the first hidden linear layer (pre-ReLu).

```
ipdb> mlp.layers.layers[0].outputs
GPUTensor(base 0x902c89e00) name:None shape:(100, 128) dtype:float32 strides:(128, 1) is_trans:False is_contiguous:True
```

**Comment by saurav111** [comment]
Thanks. I want to access the activations for a particular batch at test time. Will it be correct to call `outputs` on the layer I want to look at, after calling `fprop` with that batch?

**Comment by hanlin-nervana** [comment]
That should work. Please let us know if you run into any issues.

**Comment by saurav111** [comment]
Great. Thanks a lot.
