### ISSUE TITLE
Multi-Dimensionnal Tensor Input in Neon RNN

### ISSUE THREAD

**Issue by arita37** [NervanaSystems/neon#281]
Hi,

I would like to know if we can input multi-dimensional
Tensor in Nein RNN  API:
I tried to find/test but could not....

Each sample i
Input Data:  
     Xi   Size= (26 (NbChar)  x 100 (Seq_Len)  x 3 (nb_type) )

Output Data (one character ahead):   
    Yi   Size= (26 (NbChar  x 1 (Seq_Len)  x 3(nb_type) )

Thanks, regards
Brook

**Comment by yinyinl** [comment]
neon RNN layers uses this [data layout](http://neon.nervanasys.com/index.html/design.html#data-layout). What you described looks similar to a character RNN model. Please look at [this example](https://github.com/NervanaSystems/neon/blob/master/examples/char_rnn.py) to see how this type of input-output is being handled in neon.
