### ISSUE TITLE
video-c3d example: Issue loading data from memory

### ISSUE THREAD

**Issue by saurav111** [NervanaSystems/neon#286]
I wish to obtain c3d features for a video stream.

I thus wanted to test whether the underlying numpy array created using `ArrayIterator` and the one created loading data from disk using `VideoParams` are the same.   

I obtained the class probabilities for a video from the UCF-101 dataset (belonging to class 40) using the following code.

```python
from builtins import map, zip
import cv2
import numpy as np
import os
from neon.backends import gen_backend
from neon.data import DataLoader, VideoParams, ImageParams, ArrayIterator
from neon.util.argparser import NeonArgparser, extract_valid_args
from network import create_network

shape = dict(channel_count=3, height=112, width=112, scale_min=128, scale_max=128)

testParams = VideoParams(frame_params=ImageParams(center=True, flip=False, **shape),
                         frames_per_clip=16)

common = dict(target_size=1, nclasses=101, datum_dtype=np.uint8)

be  = gen_backend(backend='cpu',batch_size=1)

videos = DataLoader(set_name='val', repo_dir="~/neon/ucf_preprocessed/only_1", media_params=testParams,shuffle=False, **common)

model = create_network()
model.load_params("UCF101-C3D.p")
model.initialize(dataset=videos)

for video, label in videos:
    probs_mb = model.fprop(x=video, inference=True).get()
    break

print np.argmax(probs_mb)
#prints 40
```

When I read in the frames using opencv and pass them as a numpy array to `ArrayIterator`, the result is different 

```python
file_name = "/home/saurav/neon/ucf_preprocessed/only_1/HorseRace/v_HorseRace_g07_c05_13.avi"
file_buffer = cv2.VideoCapture(file_name)

list_of_frames = []

while True:
    ret,frame = file_buffer.read()
    if frame is not None:
        frame = frame[29:141,8:120,:] #center crop
        list_of_frames.append(frame)
    else:
        break

frame_array = np.array(list_of_frames)
frame_array = frame_array.reshape(3,16,112,112)
frame_array = np.reshape(frame_array,(1,3*16*112*112))

y_dummy = np.random.randint(0,101,1)

videos_cv2 = ArrayIterator(X=frame_array,y=y_dummy,nclass=101,lshape=(3,16,112,112))

for video,label in videos_cv2:
    probs_cv2 = model.fprop(x=video,inference=True).get()
    break

print np.argmax(probs_cv2)
# prints 50
```

I also looked at the `video.asnumpyarray()` result in both the cases and they are different.
Is there a good way to get the same numpy array loading video from disk using `VideoParams` versus reading it in frame by frame and passing it to `ArrayIterator`?

**Comment by hanlin-nervana** [comment]
When `ImageParams` uses the settings `shape = dict(channel_count=3, height=112, width=112, scale_min=128, scale_max=128)`, the data loader will _first_ scale the frame such that the short side is 128 pixels, and then take a center crop of 122x122. Try implementing the scaling operation in your generation of the `frame_array`.

**Comment by saurav111** [comment]
The size of frame in this case is `(128,171)`. So, there is no need to scale.

**Comment by anlthms** [comment]
Two things:

1) The data returned by the DataLoader is in CHW format. OpenCV returns the video frames in HWC format. In order to have the color channels as the first dimension, you can do this in your code:

` frame = np.transpose(frame, axes=[2, 0, 1])`

2) The DataLoader performs mean subtraction by default. You can turn it off by setting subtract_mean to False within ImageParams.

With these changes, you should see the data from both sources match exactly.

**Comment by saurav111** [comment]
@anlthms Thank you :)
