### ISSUE TITLE
[Fast-RCNN example] How to try out with only one file?

### ISSUE THREAD

**Issue by hartator** [NervanaSystems/neon#295]
Thanks for this awesome framework, it's a lot of fun to play with it

I am wondering what will be the easiest and fastest way to try out my `frcn_vgg.pkl` model (fast-rcnn example) with a single image. Is there a way to just supply an arbitrary image and get the outputs or do I have to make my custom implementation of `PASCALVOCInference` that is taking only one image and not a set?

**Comment by yinyinl** [comment]
You can run the model with one single image, but you do need to implement the image preprocessing steps before feeding it. You can look at steps in the PASCALInference for reference. Also fast RCNN needs precomputed bounding box proposals from selective search as inputs besides image, so you will need that precomputed from any open source selective search package. Also look at fast RCNN test.py for how to process the model output. 

We are planning to add Faster RCNN to neon soon, which doesn't require selective search to provide bounding boxes. It will provide a more end-to-end solution to process an arbitrary image.

**Comment by jennifermyers** [comment]
Faster RCNN will be available in 1.6.0.

**Comment by jennifermyers** [comment]
Marking this issue as closed - please take a look at Faster RCNN in 1.6.0.
