### ISSUE TITLE
Propagate/Concatenate Input in ConvNets

### ISSUE THREAD

**Issue by EnriqueSMarquez** [NervanaSystems/neon#298]
Hello,

I am trying to concatenate the input image with the feature maps of a convolutional layers with padding. This is possible since the dimensionality is preserved after the convolution. Is there any way of defining the input and concatenate it when is required?

I am trying to do something similar to:

```
merge = MergeConcat([Sequential(layers=[Conv(**params)]),Sequential(layers=[input])])

layers = [merge,
          Affine(nout=500),
          Affine(nout=10)]
```

Cheers,
Enrique Marquez

**Comment by hanlin-nervana** [comment]
If I understand correctly, you will want to use our `MergeMultistream` container to stack features along the non-batch dimension. See our [mnist_merge.py](https://github.com/NervanaSystems/neon/blob/master/examples/mnist_merge.py) for example usage. 

To pass the image input directly, you will have to patch our `SkipNode` layer slightly:
```
diff --git a/neon/layers/layer.py b/neon/layers/layer.py
index cb131d1..9bd6561 100644
--- a/neon/layers/layer.py
+++ b/neon/layers/layer.py
@@ -413,7 +413,9 @@ class SkipNode(Layer):
         Returns:
             Tensor: deltas to propagate to the adjacent lower layer
         """
-        self.deltas[:] = self.deltas * beta + alpha * error
+        if self.deltas is not None:
+            self.deltas[:] = self.deltas * beta + alpha * error
+
         return self.deltas
```

Then, you can use the `SkipNode` layer in this way:

```
path1 = Sequential(layers=[SkipNode()])
path2 = Sequential(layers=[Conv(**params)])

layers = [MergeMultistream(layers=[path1, path2], merge="stack"),
               Affine(nout=500),
               Affine(nout=10)]
```

Please let us know if this solution works for you.

**Comment by EnriqueSMarquez** [comment]
Thanks Hanlin for your reply. It worked indeed. I changed the Multistream with a Merge Broadcast, since the input is the same.

Cheers,
Enrique Marquez
