### ISSUE TITLE
installation problem for neon

### ISSUE THREAD

**Issue by pchankh** [NervanaSystems/neon#302]
We are trying to install neon on mac el capitan to try out for a Kaggle competition.
See https://github.com/anlthms/sp-2016
Encountered the following error 
I have the following error after installing all the prerequisites. Appreciate if you can help

(.venv2) Patricks-iMac:sp-2016-master patrickchan$ sh run.sh ../input/data/
++ seq 1 3

for subj in 'seq 1 3'
train_dir=../input/data//train_1/
'[' '!' -e ../input/data//train_1/ ']'
echo Processing subject 1... Processing subject 1...
./model.py -e 16 -w ../input/data//train_1/ -r 0 -z 64 -v --no_progress_bar -elec 0 2016-09-19 13:10:06,199 - neon.backends.nervanacpu - WARNING - Problems inferring BLAS info, CPU performance may be suboptimal 2016-09-19 13:10:06,199 - neon.backends.nervanacpu - INFO - Initialized NervanaCPU 2016-09-19 13:10:06,199 - neon.backends - INFO - Backend: cpu, RNG seed: 0 2016-09-19 13:10:06,199 - neon.util.argparser - INFO - Command Line Args: -e 16 -w ../input/data//train_1/ -r 0 -z 64 -v --no_progress_bar -elec 0 Defaults: --serialize: 0 --history: 1 --backend: cpu --device_id: 0 --max_devices: 0 --rounding: False --datatype: f32
Exception at src/api.hpp:51 Audio support not built-in. Please install the pre-requisites and re-run the installer.
Traceback (most recent call last):
File "./model.py", line 74, in 
repo_dir=data_dir, shuffle=True, **common)
File "/Users/patrickchan/Downloads/neon-1.5.4/neon/data/dataloader.py", line 160, in init
self.start()
File "/Users/patrickchan/Downloads/neon-1.5.4/neon/data/dataloader.py", line 240, in start
raise RuntimeError('Failed to start data loader.')
RuntimeError: Failed to start data loader.

for subj in 'seq 1 3'
train_dir=../input/data//train_2/
'[' '!' -e ../input/data//train_2/ ']'
echo Processing subject 2... Processing subject 2...
./model.py -e 16 -w ../input/data//train_2/ -r 0 -z 64 -v --no_progress_bar -elec 0 2016-09-19 13:10:06,765 - neon.backends.nervanacpu - WARNING - Problems inferring BLAS info, CPU performance may be suboptimal 2016-09-19 13:10:06,765 - neon.backends.nervanacpu - INFO - Initialized NervanaCPU 2016-09-19 13:10:06,765 - neon.backends - INFO - Backend: cpu, RNG seed: 0 2016-09-19 13:10:06,766 - neon.util.argparser - INFO - Command Line Args: -e 16 -w ../input/data//train_2/ -r 0 -z 64 -v --no_progress_bar -elec 0 Defaults: --serialize: 0 --history: 1 --backend: cpu --device_id: 0 --max_devices: 0 --rounding: False --datatype: f32
Thanks
Patrick

**Comment by anlthms** [comment]
Please try this after installing Homebrew.
```
brew install ffmpeg
cd neon
make -C loader clean
make
```
This should rebuild the neon data loader library with support for audio decoding.

**Comment by pchankh** [comment]
Thanks for the help. That solves the problem.  Maybe we should put that installation instructions into the installation step too. Thanks.
Patrick

**Comment by anlthms** [comment]
@pchankh, good to know that fixed the problem. We will add these steps to our documentation. Meanwhile, you might want to do a `git pull` on the sp-2016 repo. I committed a bugfix earlier today.
