### ISSUE TITLE
Compiling neon with GPU capability in MAC el capitan

### ISSUE THREAD

**Issue by pchankh** [NervanaSystems/neon#303]
Can someone help advise how to compile neon with GPU capability under MAC OS 10.11.6?
Is there any installation instruction that made this clear?  

Thanks.
Patrick

**Comment by hanlin-nervana** [comment]
In general, we can install on OSX with GPU by:
1. installing CUDA
2. installing the required packages from this [list](http://neon.nervanasys.com/index.html/installation.html) using [homebrew](http://brew.sh/).
3. for the dataloader, installing opencv and ffmpeg using homebrew.

Please let us know any issues you are encountering so we can help!
