### ISSUE TITLE
PKL file for inference of faster r-cnn code

### ISSUE THREAD

**Issue by karthikmswamy** [NervanaSystems/neon#307]
Dear Neon team, thanks for releasing the Fast RCNN and Faster RCNN code. Are there any plans to release the pkl files for testing the code? It would be very useful to benchmark trained models against your pkl files. Thanks.

**Comment by hanlin-nervana** [comment]
I've just uploaded a model file from one of our training runs here: https://s3-us-west-1.amazonaws.com/nervana-modelzoo/Faster_RCNN/frcn_pascalvoc.prm

This model was obtained by training the Faster-RCNN model for 7 epochs on the PASCALVOC dataset. To test the model, use the inference.py script:
```
python inference.py --model_file frcn_pascalvoc.prm -w <path/to/data/folder>
```

This particular model should obtain an MAP of 69.2% (similar to the pycaffe implementation)

**Comment by karthikmswamy** [comment]
Thank you @hanlin-nervana for the quick update with the model file. I'm downloading it.
Can you share some timing information about this model? Thanks in advance.

**Comment by karthikmswamy** [comment]
Thanks a lot for the quick updates, @hanlin-nervana. This should help with our benchmarks.
