### ISSUE TITLE
A Potential Error in sconv_bprop_C1_N64 Kernel

### ISSUE THREAD

**Issue by Jokeren** [NervanaSystems/neon#309]
In this kernel, every thread reads 4 contigous elements by tidX:

    // tidX  = (tid & 7) << 2
    // k     = tid >> 3

It checks the bound by `P1` predicate:

    ISETP.LT.AND P1, PT, crst, param_CRST, PT;

However, it is possible that the last valid thread accesses undeclared memory, as it has not checked out `crst + 1`, `crst + 2`, and `crst + 3`. As far as I understand, you use a fixed size memory, which is greater than the actual `filter` size, to hold the transposed `filter` in the backend, but errors might still happen. 

Thank you very much, I hope some of you could answer me the question!

@scttl @jennifermyers @scott-gray

**Comment by scott-gray** [comment]
You are right in that the code is technically incorrect in that it could try to fetch data out of bounds.  In practice this rarely generates an error.   Given how out of bounds detection works on the gpu it would take an extreme set of circumstances for this to be a problem.  The output predicates are accurate so any invalid data that may have been computed is thrown away.

But assumptions can sometimes be wrong, and it's generally better to be on the safe side and properly predicate every memory access.  I think I wrote this kernel prior to discovering the utility of the predicate spilling instructions (R2P, P2R).  I no longer take this shortcut in more recent kernels.

**Comment by Jokeren** [comment]
Hi, @scott-gray , thanks for the reply!

I think the following codes might be correct:

    ISETP.LT.AND P4, PT, crst, param_CRST, PT; 
    ISETP.LT.AND P5, PT, crst1, param_CRST, PT; 
    ISETP.LT.AND P6, PT, crst2, param_CRST, PT; 
    ISETP.LT.AND P1, PT, crst3, param_CRST, PT; 
    
    @P4 LD.E.CI load0F0, [track0F + 4x<0>];
    @P5 LD.E.CI load0F1, [track0F + 4x<1>];
    @P6 LD.E.CI load0F2, [track0F + 4x<2>];
    @P1 LD.E.CI load0F3, [track0F + 4x<3>];
    @!P4 LDS.32 load0F0, [RZ + addr_zero];
    @!P5 LDS.32 load0F1, [RZ + addr_zero];
    @!P6 LDS.32 load0F2, [RZ + addr_zero];
    @!P1 LDS.32 load0F3, [RZ + addr_zero];
    
    @P4 LD.E.CI load4F0, [track4F + 4x<0>];
    @P5 LD.E.CI load4F1, [track4F + 4x<1>];
    @P6 LD.E.CI load4F2, [track4F + 4x<2>];
    @P1 LD.E.CI load4F3, [track4F + 4x<3>];
    @!P4 LDS.32 load4F0, [RZ + addr_zero];
    @!P5 LDS.32 load4F1, [RZ + addr_zero];
    @!P6 LDS.32 load4F2, [RZ + addr_zero];
    @!P1 LDS.32 load4F3, [RZ + addr_zero];

Could you tell me a lit bit more about the (R2P, P2R) instructions, and how you use them to handle the boundary conditions?

**Comment by scott-gray** [comment]
Here's some code that demonstrates their use:

```
// Calc and store some predicates in a register:
--:-:-:-:1      IADD   txb1, txb, 1;
--:-:-:-:1      IADD   txb2, txb, 2;
--:-:-:-:1      IADD   txb3, txb, 3;
--:-:-:-:1      ISETP.LT.AND P2, PT, txb,  param_n, PT;
--:-:-:-:1      ISETP.LT.AND P3, PT, txb1, param_n, PT;
--:-:-:-:1      ISETP.LT.AND P4, PT, txb2, param_n, PT;
--:-:-:-:1      ISETP.LT.AND P6, PT, txb3, param_n, PT;
// 0x5c is the bitmask for preds 2,3,4,6
--:-:-:-:1      P2R predsB, PR, RZ, 0x5c;
```

```
// Load and use the stored predicates:
--:-:-:-:1      ISETP.GE.AND P2, PT, k, 8, PT;
--:-:-:-:1 @!P2 R2P PR, RZ,     0x5c;
--:-:-:-:1  @P2 R2P PR, predsB, 0x5c;
// let 13 clocks pass
08:-:-:-:1  @P2 LDG.E.CI.$dtype loadB0, [trackB + ${dsize}x<0>];
--:-:-:-:1  @P3 LDG.E.CI.$dtype loadB1, [trackB + ${dsize}x<1>];
--:-:-:-:1  @P4 LDG.E.CI.$dtype loadB2, [trackB + ${dsize}x<2>];
--:-:4:-:1  @P6 LDG.E.CI.$dtype loadB3, [trackB + ${dsize}x<3>];
```

But what you have is fine.  Just look out for all the places P1 is updated after K is modifed.  4,5,6 would also have to be updated.  
```
--:-:-:-:0      ISETP.GT.AND P1, PT, K, RZ, P1;
```
With predicate un-spilling it only takes 3 instructions instead of 4.
