### ISSUE TITLE
data dimension question in timeseries_lstm example

### ISSUE THREAD

**Issue by loofahcus** [NervanaSystems/neon#311]
A data dimension question really confuses me in the timeseries_lstm example.

In [timeseries_lstm.py#L200](https://github.com/NervanaSystems/neon/blob/master/examples/timeseries_lstm.py#L200), I think the X_batch's shape is (nfeatures, batch_size \* time_steps), but when the data goes into the LSTM layer, in [recurrent.py#L175](https://github.com/NervanaSystems/neon/blob/master/neon/layers/recurrent.py#L175), the input's shape is considered to be  (nfeatures, time_steps \* batch_size).  The unmatched shapes seem to cause `get_steps` to slice by mistake.

Do I miss something or the shapes really don't match correctly? 
Any suggestions are welcome! Thanks!

**Comment by loofahcus** [comment]
Now I think it's a bug in [timeseries_lstm.py](https://github.com/NervanaSystems/neon/blob/master/examples/timeseries_lstm.py). 
In [timeseries_lstm.py#L200](https://github.com/NervanaSystems/neon/blob/master/examples/timeseries_lstm.py#L200), it should be modified from:
```
X_batch = self.X[:, self.batch_index].reshape(
    self.X_dev.shape[::-1]).T.copy()
y_batch = self.y[:, self.batch_index].reshape(
    self.y_dev.shape[::-1]).T.copy()
```
to:
```
X_batch = self.X[:, self.batch_index].T.reshape(
    self.X_dev.shape).copy()
y_batch = self.y[:, self.batch_index].T.reshape(
    self.y_dev.shape).copy()
```

When the batch_size is 1, it does not matter, but otherwise it hurts.

**Comment by yinyinl** [comment]
You are correct. We will include your fix right away. Thanks for looking into this!
