### ISSUE TITLE
Incorrect documentation on Affline compound layer

### ISSUE THREAD

**Issue by ticoneva** [NervanaSystems/neon#314]
Documentation says that the 'init' argument specifies the initializer for layer weights and bias:

> init (Initializer, optional): Initializer object to use for initializing layer weights and bias

But as far as I can tell from the source code, Affline only adds a Bias layer if the 'bias' argument is specified.

**Comment by jennifermyers** [comment]
Hi @ticoneva - thanks for spotting that! We'll correct the docs in the next release.
