### ISSUE TITLE
example/whale_calls.py  error: Failed to start data loader

### ISSUE THREAD

**Issue by a62153232** [NervanaSystems/neon#320]
I'm trying to run the example about the Kaggle competition:whale-detection-challenge, and i have downloaded the dataset from https://www.kaggle.com/c/whale-detection-challenge  . The audio files are AIFF formats.

error ： Exception at src/api.hpp:51 Audio support not built-in. Please install the pre-requisites and re-run the installer.

Is AIFF an unsupported format of data loader？

**Comment by anlthms** [comment]
Yes, AIFF is supported. However, you'll need to have ffmpeg installed. Reinstall neon after you have all the prerequisites.

**Comment by a62153232** [comment]
@anlthms ,thank you very much for your answer. The DataLoader works perfectly after i have installed ffmpeg.

**Comment by swapnilsj** [comment]
I too encountered above issue & installed `ffmpeg` on my MacBook Pro and `make sysinstall` on Neon ...still getting the same issue. What could be wrong?
