### ISSUE TITLE
Cannot save model every epoch

### ISSUE THREAD

**Issue by L-CY** [NervanaSystems/neon#325]
There is a SerializeModelCallback, I tried but it seems to overwrite model again and again. And when training is done I get the finally model. But what I want is to get a few models (XXX-epoch01.p, XXX-epoch02.p XXX-epoch03.p ........) How can I do that?

**Comment by hanlin-nervana** [comment]
You can use the `-H` flag to store model history. For example the command `-s mymodel.p -H 60` will retain the 60 most recent model files, saved as `mymodel_0.p`, `mymodel_1.p`, and so forth.

**Comment by L-CY** [comment]
Great. That's what I want. Thanks.
