### ISSUE TITLE
Import caffe / torch model?

### ISSUE THREAD

**Issue by L-CY** [NervanaSystems/neon#326]
Is that a way to import caffe / torch pretrained model? Can you show me how to do that?

**Comment by hanlin-nervana** [comment]
We have a `caffe2neon` utility (https://github.com/NervanaSystems/caffe2neon) for converting caffe models using the protobuf formatted Caffe model definition file and a binary protobuf model parameter file. For more information, see the instructions in that repository.

**Comment by L-CY** [comment]
I'll see how it works. Thanks.
