### ISSUE TITLE
Does Neon support Jetson TX1 platform? 

### ISSUE THREAD

**Issue by swapnilsj** [NervanaSystems/neon#327]
If yes, is there any tutorial on installing and using neon on TX1?

**Comment by binarybana** [comment]
We have used one successfully in the past. Not sure about available documentation, if I find any I'll let you know.

**Comment by binarybana** [comment]
@swapnilsj I pulled up a few pointers from another engineer, hope this helps:
```
Install JetPack
apt-get install git python-virtualenv python-dev libyaml-dev libhdf5-dev
pycuda
apt-get install libboost-all-dev
follow configure, make, and install instructions on website
git clone https://github.com/NervanaSystems/neon
make sysinstall
2 ** 31 -2 in nervanagpu.py instead of 2**32-1
```

**Comment by swapnilsj** [comment]
@binarybana Thanks. Let me give it a try...I will get back to you with the results/issues if any.

**Comment by atlury** [comment]
Thanks from my side too ...shall try it out
