### ISSUE TITLE
Dataloader error while running whale_calls.py | ffmpeg issue

### ISSUE THREAD

**Issue by swapnilsj** [NervanaSystems/neon#328]
I am getting error related to dataloader while running whale_calls.py and I can see that its related to `ffmpeg` installation. I installed it by following instructions from: https://trac.ffmpeg.org/wiki/CompilationGuide/MacOSX 
`brew install ffmpeg`
`source activate neon`
`cd neon && make sysinstall`

It seems `make` is not able to locate the ffmpeg libs. What could be the issue ?

**Error:**
------------------------------------------------
<div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%"><span style="color: #333333">(</span>neon<span style="color: #333333">)</span> MacBook-Pro:neon<span style="color: #996633">$ </span>python examples/whale_calls.py -e 1 -r 0
2016-11-21 11:29:55,146 - neon.backends.nervanacpu - WARNING - Problems inferring BLAS info, CPU performance may be suboptimal

args.data_dir:  /Users/SwapAnu/nervana/data
Exception at src/api.hpp:51 Audio support not built-in. Please install the pre-requisites and re-run the installer.
Traceback <span style="color: #333333">(</span>most recent call last<span style="color: #333333">)</span>:
  File <span style="background-color: #fff0f0">&quot;examples/whale_calls.py&quot;</span>, line 118, in &lt;module&gt;
    <span style="color: #996633">index_file</span><span style="color: #333333">=</span>train_idx, **common<span style="color: #333333">)</span>
  File <span style="background-color: #fff0f0">&quot;/Users/SwapAnu/Desktop/msproject/anaconda/envs/neon/lib/python3.5/site-packages/neon-1.6.0-py3.5.egg/neon/data/dataloader.py&quot;</span>, line 170, in __init__
    self.start<span style="color: #333333">()</span>
  File <span style="background-color: #fff0f0">&quot;/Users/SwapAnu/Desktop/msproject/anaconda/envs/neon/lib/python3.5/site-packages/neon-1.6.0-py3.5.egg/neon/data/dataloader.py&quot;</span>, line 250, in start
    raise RuntimeError<span style="color: #333333">(</span><span style="background-color: #fff0f0">&#39;Failed to start data loader.&#39;</span><span style="color: #333333">)</span>
RuntimeError: Failed to start data loader.
</pre></div>

**Comment by rkimballn1** [comment]
Neon 1.7 was recently released and you may want to give it a try. Go through all of the prerequisites for the new install.
