### ISSUE TITLE
ValueError: 3D Convolution not supported by CUDA C kernels and pre-Maxwell GPUs while running  python examples/video-c3d/train.py

### ISSUE THREAD

**Issue by devareddy** [NervanaSystems/neon#332]
While running python examples/video-c3d/train.py am getting ValueError: 3D Convolution not supported by CUDA C kernels and pre-Maxwell GPUs

**Comment by ursk** [comment]
There are two sets of GPU kernels in neon. One has special assembly level optimizations for Maxwell and Pascal generation cards (e.g. GTX980, GTX1080, most cards from 2015 and newer) and supports 3D convolution. The other set is using less optimized CUDA C, supports older GPUs, and no 3D convolution. 

Unless you actually have a Maxwell GPU, and it is erroneously detected as an oder GPU, this example is not expected to work. Can you clarify which GPU you have?

**Comment by devareddy** [comment]
We are using Tesla K80

**Comment by ursk** [comment]
The K series cards are Kepler architecture, so you won't be able to use 3D convolution. It should not be hard to add that functionality to our CUDA C kernels though, and we welcome community contributions if you would like to add it yourself.
