### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by jacob1017** [NervanaSystems/neon#333]
Hi dev,

Recently I want to use neon library to accelerated my DL Framework, but i can not make & install neon successfully.  Always numpy for python can not be found, though I have yum install many times, please help me. 
ps: POWER8 and P100 nvidia card

**Comment by ursk** [comment]
Hi,

I think you are the first to try neon on a POWER8 system, so you are going to be a bit of a guinea pig for installing neon on this architecture. That being said, there is nothing x86 specific in neon and it runs out of the box on ARM with Ubuntu. 

To help you debugging, could you give more details of they system you are using (operating system etc.), what version of Python and Numpy are installed, attach a copy of the full error message, and let us know if python and numpy are working normally outside of neon.
