### ISSUE TITLE
How sass files generated?

### ISSUE THREAD

**Issue by qianglan** [NervanaSystems/neon#334]
A simple question? how all those sass files generated?  Are they wrote manually or generated by maxas.pl ?
if they are generated by maxas.pl, any based source files? Thanks

**Comment by oleg-trott** [comment]
Some kind of superhuman intelligence may have been involved.

**Comment by thestew42** [comment]
The sass files are hand-written, but also contain blocks of perl code used to generate specific parts of the kernels (such as the main loop of GEMM). Some information on maxas and writing kernels for maxas can be found here: https://github.com/NervanaSystems/maxas. The instructions are in SASS which is a level below PTX, but many of the instructions have similar functionality to PTX so you can start there if you're interested in what the kernels are doing.
