### ISSUE TITLE
Utilisation of all GPUs by neon

### ISSUE THREAD

**Issue by risav1994** [NervanaSystems/neon#346]
I am running neon deep speech on aws p2.16x instance, but it is not utilising all the 16 GPUS and just using one of them. How to make it utilise all the GPUS. What additional input do I need to specify to run in parallel on all 16 GPUS?

**Comment by ursk** [comment]
Multi-GPU support is a premium feature only included with Nervana Cloud. It's not available in the open source release of neon. Please contact us directly for a demo of the Nervana Cloud.
