### ISSUE TITLE
Neon birnn layer the split_input parameter is what is the use of?

### ISSUE THREAD

**Issue by guoying1030** [NervanaSystems/neon#349]
Neon birnn layer the split_input parameter is what is the use of?

**Comment by yinyinl** [comment]
In the code, we added some description 
`        split_inputs (bool): to expect the input coming from the same source of separate sources`

Models like Deep Speech (mentioned in this [issue](https://github.com/NervanaSystems/deepspeech/issues/12) ) stack up multiple BiRNN layers. In neon, we use [`DeepBiRNN`](https://neon.nervanasys.com/index.html/generated/neon.layers.recurrent.DeepBiRNN.html) to easily construct this. For first BiRNN layer, the inputs do NOT need to be split (`split_input=False`). But after processing it through 2 directions, the outputs are concatenated before going to the next layer. So for following BiRNN layers, their inputs need to be split (`split_input=True`). 

Hope that helps!
