### ISSUE TITLE
batch_writer.py is gone?

### ISSUE THREAD

**Issue by mingwugmail** [NervanaSystems/neon#354]
Maybe should be mentioned in the the change log.

Also, can I still use batch_writer.py from old version, and ImageLoader of the current version to read?

**Comment by hanlin-nervana** [comment]
batch_writer and ImageLoader will be removed in future releases. We recommend you switch to our dataloader module, [aeon](http://aeon.nervanasys.com/index.html/). aeon removes the need for a separate batch_writer script, and also includes more functionality and easier use.
