### ISSUE TITLE
Multiple GPU usage

### ISSUE THREAD

**Issue by CAWEHbKA** [NervanaSystems/neon#36]
I would like to understand if NEON supports data parallelization on multiple GPUs?
I want to use multiple GPUs in order to increase mini-batch size...

The second question if MPI parallelization can be used with -gpu option?

**Comment by apark263** [comment]
Hi,

We do not support data parallelization yet but it is in progress.

-Alex

**Comment by scttl** [comment]
With the 0.9.0 release we now support multi GPU data and model parallelization provided you are using the nervanagpu backend (Tesla based cards).

Note that this release drops support of MPI based parallelization, and will not work across all models/datasets when using the cudanet backend (Kepler based cards).

**Comment by nervanasys** [comment]
Following neon v1.0, multi-GPU & multi-node support is on the Nervana Cloud only. These have been optimized for our Cloud HW setup.

**Comment by MaratZakirov** [comment]
Following neon v1.0, multi-GPU & multi-node support is on the Nervana Cloud only.

So I can't use multiple GPUs locally?
