### ISSUE TITLE
loader/src/util.hpp:24:10: fatal error: 'sox.h' file not found

### ISSUE THREAD

**Issue by Bonsen** [NervanaSystems/neon#367]
run:
git clone https://github.com/NervanaSystems/neon.git
cd neon && make sysinstall

get:
    In file included from loader/src/block_iterator_shuffled.cpp:20:
    loader/src/util.hpp:24:10: fatal error: 'sox.h' file not found
    #include <sox.h>
             ^
    clang++ -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wno-deprecated-declarations -std=c++11 -DHAS_IMGLIB -fPIC -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -I/usr/local/include/opencv -I/usr/local/include -I/usr/include/python2.7 -c loader/src/etl_image.cpp -o build/temp.linux-x86_64-2.7/loader/src/etl_image.o -Wno-deprecated-declarations -std=c++11 -DHAS_IMGLIB

**Comment by apark263** [comment]
Try installing the system requirements for aeon listed here:  

https://github.com/NervanaSystems/aeon/blob/master/README.md

On ubuntu, that is: libcurl4-openssl-dev clang libopencv-dev libsox-dev

**Comment by Bonsen** [comment]
@apark263 
It works.

THANKS
