### ISSUE TITLE
how to enable GPU backend while GPU is only available on a Sun grid?

### ISSUE THREAD

**Issue by galactica147** [NervanaSystems/neon#368]
Hi All,

I have an operational question: on my local machine without GPU support, if I install neon there i can only has a NervanaCPU backend, is that correct? However, the idea is to develop stuff on my local machine and then submit it as a grid job to a Sun grid where GPU is available. 

The submit code might look like:

`qsub -V -b yes -cwd -l h_vmem=20G -l gpu=true,gpu.num=1 -N train -o /tmp/train.log -j yes 'python train.py'`

Is there some configuration that I'm missing? 
Ideally, we should avoid changing anything in the grid environment. 
Please advise. Thanks!

**Comment by thestew42** [comment]
If the Sun grid has CUDA installed, it should be possible. If you are using one of the example scripts or a script with the argparser, you should select `-b gpu` to use the GPU backend. Otherwise you would need to specify the backend type in your script (probably with the gen_backend call).

**Comment by galactica147** [comment]
Thanks! but i got some errors passing the '`-b gpu`' option: 

`Usage:
    python examples/cifar10_conv.py
: error: argument -b/--backend: invalid choice: 'gpu' (choose from 'cpu')`

could you please demonstrate a bit more on how to specify the backend with `gen_backend`?

**Comment by ursk** [comment]
The neon installer checks for the presence of the `nvcc` compiler to decided if the GPU backend should be installed or not. In this case it looks like you are doing the installation on a different machine from where the code will be running on, and this machine does not have a GPU. To force the GPU backend to be installed anyway, edit the `Makefile` in the neon root directory and set the variable `HAS_GPU` to be `true`.

**Comment by galactica147** [comment]
Thanks @ursk! that calls for installing packages in `gpu_requirement`.txt and i got lots of errors when installing `pycuda`, which depends on `cuda `libararies to begin with. Is there any easy way to get around this?

**Comment by ursk** [comment]
There is probably no easy way, see if you can install CUDA locally (it should be possible to install without having a GPU) to get `pycuda` installed. If you know which version of cuda runs on the cluster, and where it is installed, you can try to mimic that setup locally. Pycuda will link against cuda libraries at install time, and if you run under a different environment, it may complain that it can't find cuda libraries in the expected path.

**Comment by galactica147** [comment]
@ursk Thanks! I'll see if that's doable at my env. closing ticket for now.
