### ISSUE TITLE
`sudo make install` doesn't work on ubuntu with GPU enabled

### ISSUE THREAD

**Issue by rongou** [NervanaSystems/neon#37]
sudo on ubuntu resets the $PATH, so even if you have cuda installed and /usr/local/cuda/bin in your PATH, the makefile can't find nvcc.

**Comment by ursk** [comment]
Hi rongou, 
I don't think it's safe to assume that nvcc will always be in the location `/usr/local/cuda/bin/nvcc`. You can try to use `sudo -E`  to preserve the environment variables, or just explicitly include the path in your sudo call.

**Comment by rongou** [comment]
At least on my system, sudo -E doesn't work. The only way to make it work is do `sudo env PATH=$PATH make install`. Maybe just need to document this.

**Comment by scttl** [comment]
Hi @rongou this is actually already documented in our FAQ: http://neon.nervanasys.com/docs/latest/faq.html#installation  (see the last bullet point under installation)
