### ISSUE TITLE
What 'N' means in LRN document ?

### ISSUE THREAD

**Issue by guoxuesong** [NervanaSystems/neon#389]
The [LRN document](http://neon.nervanasys.com/docs/latest/generated/neon.layers.layer.LRN.html#neon-layers-layer-lrn) mentions 'ascale/N' but what 'N' means ?

The default value of ascale is 1.0, while the corresponding value in Lasagne is 1e-4, I need known how to convert from each other.

**Comment by wei-v-wang** [comment]
N should be the minibatch size according to the API on the LRN document page: 

set_batch_size(N) | Set minibatch size.
