### ISSUE TITLE
Speed check fails with nervanagpu because rectleaky isn't implemented

### ISSUE THREAD

**Issue by kuprel** [NervanaSystems/neon#39]
either rectleaky should be implemented here https://github.com/NervanaSystems/neon/blob/master/neon/backends/gpu.py

or the rectleaky transform shouldn't be included here
https://github.com/NervanaSystems/neon/blob/master/examples/convnet/synthetic-sanity_check.yaml

**Comment by scttl** [comment]
Thanks for raising this.  Commit 541b6f9 addresses this by implementing Leaky ReLU's for the nervanagpu backend

**Comment by kuprel** [comment]
Awesome.  This might be specific to me but I get 1.9s with cudanet and 4.7s with nervanagpu.  I have a Titan X
