### ISSUE TITLE
Duplicate directory name running ingest_pascalvoc.py

### ISSUE THREAD

**Issue by abatkins** [NervanaSystems/neon#401]
Running faster-rcnn/ingest_pascalvoc.py on the PascalVOC 2007 dataset described in the tutorial results in the following error:

> File "faster_rcnn/ingest_pascalvoc.py", line 118, in <module>
>     ingest_pascal(args.input_dir, args.output_dir, overwrite=args.overwrite)
>   File "faster_rcnn/ingest_pascalvoc.py", line 60, in ingest_pascal
>     convert_xml_to_json(input_path, annot_path, difficult=False)
>   File "faster_rcnn/convert_xml_to_json.py", line 76, in convert_xml_to_json
>     trimmed = parse_single_file(join(input_path, file), difficult)
>   File "faster_rcnn/convert_xml_to_json.py", line 86, in parse_single_file
>     tree = et.parse(path)
>   File "anaconda3/envs/neon/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
>     tree.parse(source, parser)
>   File "anaconda3/envs/neon/lib/python3.6/xml/etree/ElementTree.py", line 586, in parse
>     source = open(source, "rb")
> FileNotFoundError: [Errno 2] No such file or directory: 'voctrain/VOCdevkit/VOC2007/Annotations/voctrain/VOCdevkit/VOC2007/Annotations/000001.xml

Simple fix is in "neon/examples/faster-rcnn/covert_xml_to_json.py". Replace line 73:

`trimmed = parse_single_file(join(input_path, file), difficult)`

with 

`trimmed = parse_single_file(file, difficult)`

**Comment by wei-v-wang** [comment]
Thank you for reporting the fix and providing a fix, this PR has been cherry-picked into internal for review and testing.

**Comment by wei-v-wang** [comment]
Hi @abatkins Can you please provide your command used to run ingest_pascalvoc? 

I tried our ingestion code and did not encounter the error: 

~/git/private-neon/examples/faster-rcnn$ python ingest_pascalvoc.py  --input_dir ~/VOC-Tar/ --output_dir ~/faster-rcnn-VOC
Wrote config file to: /home/weiwang/git/private-neon/examples/faster-rcnn/pascalvoc.cfg
Extracting /home/weiwang/VOC-Tar/VOCtrainval_06-Nov-2007.tar to /home/weiwang/faster-rcnn-VOC
Extracting /home/weiwang/VOC-Tar/VOCtest_06-Nov-2007.tar to /home/weiwang/faster-rcnn-VOC
Reading PASCAL XML files from /home/weiwang/faster-rcnn-VOC/VOCdevkit/VOC2007/Annotations
Converting XML files to json format, writing to: /home/weiwang/faster-rcnn-VOC/VOCdevkit/VOC2007/Annotations-json
Converting XML files to json format (including objects with difficult flag),
writing to: /home/weiwang/faster-rcnn-VOC/VOCdevkit/VOC2007/Annotations-json-difficult

**Comment by wei-v-wang** [comment]
Please re-open with detailed instructions -- we were unable to reproduce. Thank you anyway!
