### ISSUE TITLE
cannot import aeon Dataloader since update to aeon 1.0.0

### ISSUE THREAD

**Issue by Drea1989** [NervanaSystems/neon#404]
hello,
since i have updated to neon 2.2 and aeon 1.0 i can't import the dataloader class, _error import failed._
system: ubuntu 16.04 CUDA 8.0 GTX1080
i am using Anaconda environments.
i tried installing neon in a new environment both in python 3.5 and 2.7 and failing with same error.
i tried checking out the tag v1.7.0 but now even this seems to not work anymore.
do you have any suggestion?
thanks

**Comment by ldurka** [comment]
Hi,
To reproduce Your issue I've used clean docker image and Ubuntu:16.04
I've installed anacoda and all required packages
```
apt-get update && apt-get install -y bzip2 git cmake clang pkg-config sox lib-sox libopencv-dev python-opencv libcurl4-openssl-dev
wget https://repo.continuum.io/archive/Anaconda2-5.0.0.1-Linux-x86_64.sh
bash Anaconda2-5.0.0.1-Linux-x86_64.sh
source ~/.bashrc
conda list
git clone https://github.com/NervanaSystems/neon.git
cd neon && make -j
.venv/bin/python -c "from aeon import DataLoader as AeonLoader"
```
I've got error like
```
raceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /anaconda2/lib/./libpng16.so.16)
```

Could you try to run and send us otput 
```
PATH_TO_YOUR_VIRTUALNEV_WITH_NEON/bin/python -c "from aeon import DataLoader as AeonLoader"
```

**Comment by kbinias** [comment]
Could you also attach output log from build process ?
Do you run Neon training process ?

**Comment by Drea1989** [comment]
i have deleted the anaconda environments, deleted and reinstalled CUDA-8.0 recloned neon in a new folder, run the make sysinstall in a new anaconda environment and this time it worked with neon 2.2 and aeon 1.0 thanks for the support

**Comment by kbinias** [comment]
@Drea1989 close this issue please.
