### ISSUE TITLE
keras support?

### ISSUE THREAD

**Issue by h5rdly** [NervanaSystems/neon#405]
Hi,

First of all, thank you for this framework, how I haven't heard of it sooner I know not. 

As the title suggests, I was wondering about possible keras support. IMO, if anything can add traction to neon, it's a compatibility layer via keras. 

Googling suggested that you actually refuse to collaborate with the keras author - 
https://www.quora.com/Is-Neon-support-planned-in-Keras

How so? Could you share your considerations over this?

Thanks,
Eli

**Comment by nervanasys** [comment]
Thanks for your question and the pointer to quora.

I just responded to this question on [quora](https://www.quora.com/Is-Neon-support-planned-in-Keras/answer/Arjun-Bansal-31?srid=3y3Fc).
