### ISSUE TITLE
deep_dream example assert len(pdict['config']['layers']) == len(self.layers)

### ISSUE THREAD

**Issue by riccitensor** [NervanaSystems/neon#410]
I have `assert len(pdict['config']['layers']) == len(self.layers)` when running 
`(.venv2) gamer@gamer:~/Documents/neon$ python examples/deep_dream.py ../genie.jpg --output genie2.jpg` on Ubuntu 16.4 with Neon 2.3.0+9eb09d7

**Comment by wei-v-wang** [comment]
Thanks @riccitensor for reporting. Issue acknowledged, working on a fix.

**Comment by wei-v-wang** [comment]
Hi @riccitensor In the latest neon commits, we added fixes to deep_dream. 
Could you please try the tip of neon master branch and verify? 

Thank you!

**Comment by riccitensor** [comment]
Hey @wei-v-wang Works for me now. Thanks a lot!

**Comment by wei-v-wang** [comment]
Ok, thanks @riccitensor for confirming.

**Comment by griffonn** [comment]
Hi, the same assertion error appears when using deepspeech with neon 2.3:
```
python evaluate.py --manifest val:/home/user/librispeech/dev-clean.manifest.csv --model_file /home/user/deepspeech/speech/librispeech_16_epochs.prm
```

```
File "/home/user/neon/neon/layers/container.py", line 200, in load_weights
    assert len(pdict['config']['layers']) == len(self.layers)
AssertionError
```

**Comment by wei-v-wang** [comment]
Hello @griffonn Could you please follow the discussion in https://github.com/NervanaSystems/neon/issues/415 and see if you can convert the model weights? 
If not, I can do the conversion for you.
