### ISSUE TITLE
Getting "floating point exception" with CUDA 9.0

### ISSUE THREAD

**Issue by shaofushih** [NervanaSystems/neon#416]
Hi all,

I just ran into an issue with python examples/mnist_mlp.py -b gpu while using neon 2.3.0

RuntimeError(136);
ptxas -v -arch sm_61 -o /home/midearoot/.cache/neon/kernels/cubin/sgemm_nn_128x128_vec.cubin /home/midearoot/.cache/neon/kernels/ptx/sgemm_nn_128x128_vec.ptx
Floating point exception (core dumped)

Did anyone have the same problem after upgrading to neon 2.3.0

**Comment by shaofushih** [comment]
We changed the make file to support sm_61 and that worked

**Comment by wei-v-wang** [comment]
@shaofushih Can you please provide your changes so that issue#415 could benefit and be resolved? 
Thanks!

**Comment by wei-v-wang** [comment]
https://github.com/xingjinglu/PerfAILibs/blob/master/README.md seems to already get the workaround by @xingjinglu.
