### ISSUE TITLE
make  neon error

### ISSUE THREAD

**Issue by yangyang-zhang** [NervanaSystems/neon#428]
```
$make HAS_GPU=true
Building MKL Engine...
which: no icc in (/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
using GNU compiler...
basename: missing operand
Try 'basename --help' for more information.
mkl root: /opt/neon/
make[1]: Entering directory `/opt/neon/neon/backends/mklEngine'
make[1]: Leaving directory `/opt/neon/neon/backends/mklEngine'
make[1]: Entering directory `/opt/neon/neon/backends/mklEngine'
Building mklEngine.so...
gcc src/conv.c src/pooling.c src/relu.c src/batchNorm.c src/concat.c src/softmax.c src/MKLDNN.h -shared -o mklEngine.so -std=c99 -O3 -I/opt/neon//include -L/opt/neon//lib -Wl,-rpath=/opt/neon//lib -fopenmp -lmklml_gnu -fPIC -march=native -g -liomp5
In file included from src/conv.c:15:0:
src/MKLDNN.h:23:21: fatal error: mkl_dnn.h: No such file or directory
 #include <mkl_dnn.h>
                     ^
compilation terminated.
In file included from src/pooling.c:15:0:
src/MKLDNN.h:23:21: fatal error: mkl_dnn.h: No such file or directory
 #include <mkl_dnn.h>
                     ^
compilation terminated.
In file included from src/relu.c:15:0:
src/MKLDNN.h:23:21: fatal error: mkl_dnn.h: No such file or directory
 #include <mkl_dnn.h>
                     ^

$ bash prepare_mkl.sh

Checking MKLML dependencies...
Downloading required MKLML version mklml_lnx_2018.0.1.20171007 ...
MKLML dependencies installed: MKLROOT=/opt/neon/
basename: missing operand
Try 'basename --help' for more information.
/opt/neon/ 1
```
I need help,thanks

**Comment by baojun-nervana** [comment]
would you try 
make clean
rm -rf mklml_lnx_* build 

We are working on to update the "make clean" to clean up mkl artifacts.

**Comment by wei-v-wang** [comment]
@yangyang-zhang please tell a look at this closed issue: 

https://github.com/NervanaSystems/neon/issues/414

**Comment by armando-fandango** [comment]
@wei-v-wang in my case the file is getting downloaded automatically, and also has the mkl_dnn.h:

ls *
license.txt

include:
i_malloc.h  mkl_cblas.h  mkl_dnn_types.h  mkl_lapack.h   mkl_trans.h  mkl_version.h      mkl_vml_functions.h  mkl_vml_types.h    mkl_vsl_functions.h  mkl_vsl_types.h
mkl_blas.h  mkl_dnn.h    mkl_lapacke.h    mkl_service.h  mkl_types.h  mkl_vml_defines.h  mkl_vml.h            mkl_vsl_defines.h  mkl_vsl.h

lib:
libiomp5.so  libmklml_gnu.so  libmklml_intel.so

**Comment by armando-fandango** [comment]
@baojun-nervana The make clean doesnt work for me so I am doing make sysclean and removing the mkl folders manually, and then running make sysinstall_python3.

The mkl is downloaded and unarchived but then the build engine fails.

**Comment by baojun-nervana** [comment]
did you try to delete the build folder as well?
rm -rf mklml_lnx_* build

**Comment by armando-fandango** [comment]
ok after deleting it couple of times it worked finally and no mkl engine build errors. thanks.

**Comment by baojun-nervana** [comment]
We will update "make clean" to remove the mkl artifacts for next release. Thanks.

**Comment by armando-fandango** [comment]
@baojun-nervana please also incorporate my patch if you can, specially for system install it keeps asking for venv and also for python3 install the current doesnt work properly.

**Comment by baojun-nervana** [comment]
thanks. We will look into it.

**Comment by yangyang-zhang** [comment]
Thank you, I've already solved it.
