### ISSUE TITLE
Support RMSProp

### ISSUE THREAD

**Issue by llllaaaa** [NervanaSystems/neon#43]
Hi, would you please support RMSProp as learning rule?

**Comment by scttl** [comment]
Hi we've just merged an implementation of RMSProp, supported across all backends.  There are a couple of examples that you can try out by setting `lrule_init = *rms` for one or both of the layers in either `examples/mlp/mnist-small.yaml` or `examples/mlp/mnist-tuned.yaml`.

**Comment by llllaaaa** [comment]
Great! Thanks a lot.
