### ISSUE TITLE
libmklml_intel.so not found

### ISSUE THREAD

**Issue by mas-dse-greina** [NervanaSystems/neon#438]
I just built neon on a CentOS 7 (3.10.0-693.11.6.el7.x86_64) within a conda (Python 2.7) environment. The build appeared to be successful, but when I try to run the mnist_mlp.py example, I get:

> (neon) [bduser@node15 examples]$ python mnist_mlp.py
> Traceback (most recent call last):
>   File "mnist_mlp.py", line 59, in <module>
>     args = parser.parse_args()
>   File "/home/bduser/miniconda2/envs/neon/lib/python2.7/site-packages/nervananeon-2.6.0-py2.7.egg/neon/util/argparser.py", line 366, in parse_args
>     compat_mode=args.compat_mode)
>   File "/home/bduser/miniconda2/envs/neon/lib/python2.7/site-packages/nervananeon-2.6.0-py2.7.egg/neon/backends/__init__.py", line 113, in gen_backend
>     deterministic=deterministic)
>   File "/home/bduser/miniconda2/envs/neon/lib/python2.7/site-packages/nervananeon-2.6.0-py2.7.egg/neon/backends/backend.py", line 468, in allocate_backend
>     return Backend.backends[name](**kargs)
>   File "/home/bduser/miniconda2/envs/neon/lib/python2.7/site-packages/nervananeon-2.6.0-py2.7.egg/neon/backends/nervanamkl.py", line 213, in __init__
>     self.mklEngine = ctypes.cdll.LoadLibrary(mkl_engine_path)
>   File "/home/bduser/miniconda2/envs/neon/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
>     return self._dlltype(name)
>   File "/home/bduser/miniconda2/envs/neon/lib/python2.7/ctypes/__init__.py", line 366, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: libmklml_gnu.so: cannot open shared object file: No such file or directory

I found this online and am trying the suggestion at the end to rebuild mkl-dnn from source (https://github.com/tensorflow/tensorflow/issues/13711).

**Comment by mas-dse-greina** [comment]
It looks like this works:

> git clone https://github.com/01org/mkl-dnn.git
> cd mkl-dnn/scripts && ./prepare_mkl.sh && cd ..
> mkdir -p build && cd build && cmake .. && make
> sudo make install
> 
> # if using bash then
> echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib' >> ~/.bashrc

Maybe the .tar.gz file that is being included with neon needs to be updated??

**Comment by baojun-nervana** [comment]
@mas-dse-greina It is good you can fix the issue by setting the library path. 
Sometimes it may need to clean up before built. You may run

make clean   => this will clean up all the mkl artifacts
make install  => it will download mkl and do a fresh install.

**Comment by wei-v-wang** [comment]
Thanks for reporting. Looks like there is a URL change for the tar.gz. 
Your approach using latest mkl-dnn (open-source) was able to avoid calling buggy URL.

**Comment by wei-v-wang** [comment]
We'll fix our code on the URL

**Comment by mas-dse-greina** [comment]
Thanks!

-Tony

**Comment by wei-v-wang** [comment]
Reopen till URL is changed. Sorry for the confusion...

**Comment by wei-v-wang** [comment]
https://github.com/NervanaSystems/neon/commit/f43cfa2e26f9c84b0f42fcda50b6b83104623223 closes this issue. Thanks again for reporting!
