### ISSUE TITLE
Question with "Adding a new type of Dataset"

### ISSUE THREAD

**Issue by Jokeren** [NervanaSystems/neon#44]
I am thinking of adding new types of Dataset.

I follow the step described in the following link:

http://neon.nervanasys.com/docs/latest/datasets.html#adding-a-new-type-of-dataset

I also write a corresponding yaml file, which is "nb.yaml"

After running `neon nb.yaml`, it shows that:

`AttributeError: 'module' object has no attribute 'NB'`(my subclass is named NB)

What should I do next?

**Comment by scttl** [comment]
Hi,

Could you post your yaml file as well as the contents of your new NB class?

Are you importing NB directly into the dataset namespace?  See: neon/datasets/__init__.py

**Comment by Jokeren** [comment]
Hi,

I find that the issue might be related with the search path. I go into the directory `neon` and then try to `make install`, then the `~/neon/bin/neon` program will invoke the python files under `.local/lib/python2.7/site-packages/neon/datasets`. If I modify the file under that directory, it works.

I do not know whether my operation is right: Modify the file, and then `make install` each time?

**Comment by apark263** [comment]
You can set your PYTHONPATH to point to your home directory neon which will
avoid the need to keep installing while making frequent changes.

**Comment by Jokeren** [comment]
@apark263 , @scttl 
Thank you for your replies! :+1: 

Additionally, I suggest to add those instructions in your document:

http://neon.nervanasys.com/docs/latest/datasets.html#adding-a-new-type-of-dataset

**Comment by scttl** [comment]
Another alternative would be to install neon in [developer mode](https://pythonhosted.org/setuptools/setuptools.html#development-mode) which you can accomplish via:

    make develop

As the link indicates this will build symlinks allowing you to edit files in your current working directory without having to do a full `make install` each time (you only need to call `make develop` once).

This is briefly mentioned at the top of the [install docs](http://neon.nervanasys.com/docs/latest/installation.html)
