### ISSUE TITLE
Add sentiment analysis example to neon

### ISSUE THREAD

**Issue by nervanasys** [NervanaSystems/neon#45]
email from a user:

I am trying to get involved with text classification. I would like to start with the classical example of movie recomendations since there are a lot of examples using different kind of software
 to illustrate And solve the problem.

Vowpal wobbit, scikit learn, stanford nlp etc...

https://www.kaggle.com/c/sentiment-analysis-on-movie-reviews

I would also like to classify the typical sentiment140 dataset which contains tweet text
Which can be noisy sometimes.

http://help.sentiment140.com/for-students/

**Comment by japerez20** [comment]
Hello guys:
I am looking forward to learning more about neon. 
Do u have tutorial or slides where u show basic ideas of neon? Something like neon for dummies? 
Could you suggest me a link to understand better the  Moby  Dick example that you include with the first release of neon?

Thank, you,
ja

**Comment by scttl** [comment]
Hi Ja,

Though we don't yet have a slide deck or screencast to share, I think the easiest way to get to grips with using neon is to start by skimming through the: [quick start](http://neon.nervanasys.com/docs/latest/quick_start.html) then following that up by looking at:
* [neon/examples/mlp/mnist-small-noyaml.py](https://github.com/NervanaSystems/neon/blob/master/examples/mlp/mnist-small-noyaml.py) to get a feel for the main objects and how they fit together
* [neon/examples/ANNOTATED_EXAMPLE.yaml](https://github.com/NervanaSystems/neon/blob/master/examples/ANNOTATED_EXAMPLE.yaml) to understand how these pieces can be configured

As for the Moby Dick example, I'd suggest reading through the [RNN docs](http://neon.nervanasys.com/docs/latest/generated/neon.models.rnn.RNN.html) as there's some detail in there describing how the data is laid out and so forth.

**Comment by yinyinl** [comment]
We have added the sentiment analysis example using movie review data. The example can be found at:
* [neon/examples/imdb_lstm.py] after this commit #339511a5f710b992a41fd0a47f4eed4a7f27445c
Along with the example script, we have added several layer components for word embeddings, processing recurrent layer outputs. Also some text preprocessing methods.
