### ISSUE TITLE
has Neon Framework development stopped? Last commit is on 9th feb.

### ISSUE THREAD

**Issue by divyanshj16** [NervanaSystems/neon#452]

**Comment by wei-v-wang** [comment]
https://github.com/NervanaSystems/ngraph is the continuation and evolved version of neon. Please have a try, ngraph is compatible with neon models. Please file issues at https://github.com/NervanaSystems/ngraph if you encounter neon issues while using ngraph. Thanks!

**Comment by divyanshj16** [comment]
@wei-v-wang Thankyou for the information. But it still doesn't answer my question.
I asked whether neon will be continued or not?
