### ISSUE TITLE
Where is Aeon?

### ISSUE THREAD

**Issue by TrishaMittal** [NervanaSystems/neon#463]
I am not able to install Aeon as the links for Aeon are broken and there is nothing there. Can you resolve this issue? Thanks !

**Comment by ryan-nervana** [comment]
Hi @TrishaMittal. We restored aeon. It was archived by mistake. Please try again. 
Thanks, 

Ryan

**Comment by rh01** [comment]
can you provide the aeon of previous version or release version before.
