### ISSUE TITLE
The batch_size cannot be set to 1?

### ISSUE THREAD

**Issue by Jokeren** [NervanaSystems/neon#47]
I only modify the file `neon/examples/convnet/mnist-small.yaml`, setting `batch_size: &bs 1`. The log reports that:

        ValueError: shapes (400,1) and (32,1) not aligned: 1 (dim 1) != 32 (dim 0)

**Comment by scttl** [comment]
Confirmed that this is a CPU backend specific bug (eslice not being transposed correctly during convolutional update step when it is a 1D vector).  

We'll set about fixing this, however one should note that using such small batch sizes may result in suboptimal runtimes, and require additional parameter tuning.

Thanks for catching this!

**Comment by Jokeren** [comment]
@scttl 

I got it. 

By the way, I set the parameter to 1 because my dataset only contains 1 picture. Instead of training the whole picture, my aim is to train for each pixel by its peripheral pixels.
