### ISSUE TITLE
No CUDA capable GPU installed.  Forcing GPU=0

### ISSUE THREAD

**Issue by duyhtq** [NervanaSystems/neon#48]
i had this error when i ran 'make install'. i have a titan x that is working fine.  below is my setup.cfg.  any help is much appreciated.

sudo make install
No CUDA capable GPU installed.  Forcing GPU=0

[neon]
CPU = 1
GPU = nervanagpu 
DIST = 0
DEV = 0

**Comment by scttl** [comment]
Hi, 

This error will come about if `nvcc` (CUDA C compiler) can't be located by the user running the command.  Does `nvcc --version` work ok for you?

Since you're doing this as the super user, you may also need to adjust your `PATH` and or `LD_LIBRARY_PATH` variables as part of the command call.  This is described in the [FAQ](http://neon.nervanasys.com/docs/latest/faq.html#installation):

    sudo env “PATH=$PATH” env “LD_LIBRARY_PATH=$LD_LIBRARY_PATH” make install

Try that and let us know if that gets you unstuck.

**Comment by duyhtq** [comment]
hi scott, yes, i have cuda 7 installed and nvcc works fine with my other cuda code.  

d@3:~/code/neon$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_22:59:02_CST_2015
Cuda compilation tools, release 7.0, V7.0.27

d@3:~/code/neon$ sudo env “PATH=$PATH” env “LD_LIBRARY_PATH=$LD_LIBRARY_PATH” make install
No CUDA capable GPU installed.  Forcing GPU=0
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.1 in /home/d/.local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.11 in /home/d/.local/lib/python2.7/site-packages
Cleaning up...
Running install(DEV=0 CPU=1 GPU=0 DIST=0)...
Unpacking /home/d/code/neon
  Running setup.py (path:/tmp/pip-ND4we5-build/setup.py) egg_info for package from file:///home/d/code/neon
    
    no previously-included directories found matching 'doc/build'
  Requirement already satisfied (use --upgrade to upgrade): neon==0.8.1 from file:///home/d/code/neon in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.8.1 in /home/d/.local/lib/python2.7/site-packages (from neon==0.8.1)
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.11 in /home/d/.local/lib/python2.7/site-packages (from neon==0.8.1)
Cleaning up...

**Comment by scttl** [comment]
Does `sudo nvcc --version` produce the same output?  Which Linux distribution/version are you currently running?

**Comment by duyhtq** [comment]
scott... it's working now.  thanks for your help!  much appreciated for making neon open source!
