### ISSUE TITLE
Define parallelism in YAML

### ISSUE THREAD

**Issue by seba-1511** [NervanaSystems/neon#52]
Is there a way to define the parallelism in the YAML file ? It could be useful for example when optimizing the hyperparameters and using all the GPUs in the machine. (I am not sure if doing hyperopt -n THREADS will spread the tasks across the GPUs)

**Comment by apark263** [comment]
Do you mean parallelism as in launching multiple runs each one assigned to
a different gpu?  If so there is no way to specify it via yaml, you have to
launch separate runs from command line using the -i option to specify which
device you want to run on.  If you mean parallelism as in splitting a
single run to run on several gpus at once, it is something that we are
working on adding to neon and is close to being added to the main
repository.

**Comment by seba-1511** [comment]
Cool ! (I meant the second one)

And when using the hyperopt command with -n were you able to spread each optimization procedure across the GPUs ? Would neon be responsible for that ?
