### ISSUE TITLE
MLP.predict_fullset doesn't work for saved models

### ISSUE THREAD

**Issue by seba-1511** [NervanaSystems/neon#55]
I trained a mlp on CIFAR10, and deserialized it in a later script. (That step works fine, I have the correct weights and everything I need.) When I call mlp.predict_fullset, cudanet raises the error:

 Traceback (most recent call last):
  File "11_merge_predictions.py", line 202, in <module>
    mlp.predict_fullset(data, 'test')
  File "/home/ubuntu/neon/neon/models/mlp.py", line 245, in predict_fullset
    reference[:, start:end] = batch_refs
  File "/home/ubuntu/neon/neon/backends/cc2.py", line 265, in __setitem__
    self._tensor.set_col_slice(start, stop, value)
  File "/home/ubuntu/cuda-convnet2/cudanet/cudanet.py", line 767, in set_col_slice
    raise generate_exception(err_code)
cudanet.cudanet.CUDANetException: Incompatible matrix dimensions.

I am again predicting on the test set of CIFAR10, and the GPU I use is the one on AWS. (~4gb) It is also the same as the one I used for training. Further more, mlp.predict_generator works fine.

**Comment by apark263** [comment]
Try printing the shapes of the associated tensors at the spot where the
error occurs and let us know what it says.
(I.e. start, stop, reference.shape and batch_refs.shape)

**Comment by seba-1511** [comment]
After hours of of looking, I realized I was loading the wrong experiment... Sorry about that, it has been one of these days.
