### ISSUE TITLE
Make fails in nervanagpu: OS X 10.10.3 - sed: illegal option -- r

### ISSUE THREAD

**Issue by dbl001** [NervanaSystems/neon#59]
Makefile:

define list_includes
  $(shell sed -rn 's/^<INCLUDE file="(.*)"\/>/\1/p' $(call strip_codes,$(1)))
endef

David-Laxers-MacBook-Pro:nervanagpu davidlaxer$ sudo !!
sudo make all
The directory '/Users/davidlaxer/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
installing maxas...
/tmp/nervanagpu.XXXXXXXX.waaER91X
Cloning into 'maxas'...
remote: Counting objects: 170, done.
remote: Total 170 (delta 0), reused 0 (delta 0), pack-reused 170
Receiving objects: 100% (170/170), 163.15 KiB | 0 bytes/s, done.
Resolving deltas: 100% (67/67), done.
Checking connectivity... done.
Checking if your kit is complete...
Looks good
Warning: prerequisite Carp 1.29 not found. We have 1.26.
Warning: prerequisite Data::Dumper 2.145 not found. We have 2.13506.
Writing Makefile for MaxAs::MaxAs
Writing MYMETA.yml and MYMETA.json
cp lib/MaxAs/MaxAs.pm blib/lib/MaxAs/MaxAs.pm
cp lib/MaxAs/Cubin.pm blib/lib/MaxAs/Cubin.pm
cp lib/MaxAs/MaxAsGrammar.pm blib/lib/MaxAs/MaxAsGrammar.pm
cp bin/maxas.pl blib/script/maxas.pl
/opt/local/bin/perl5.16 -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/maxas.pl
Manifying blib/man3/MaxAs::MaxAs.3pm
Appending installation info to /opt/local/lib/perl5/5.16.3/darwin-thread-multi-2level/perllocal.pod
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
building kernel: hgemm_nn_128x128...
make: maxas.pl: No such file or directory
make: *** [nervanagpu/kernels/cubin/hgemm_nn_128x128.cubin] Error 1
David-Laxers-MacBook-Pro:nervanagpu davidlaxer$ sed -r
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]

**Comment by apark263** [comment]
try installing maxas directly first:

https://github.com/NervanaSystems/maxas

The nervanagpu makefile should be trying to install it for you, but it
seems to have failed.  or perhaps it's installed but the path to it is not
available to your sudo.

**Comment by dbl001** [comment]
David-Laxers-MacBook-Pro:maxas davidlaxer$ pip install Carp
Collecting Carp
  Downloading carp-0.0.3.tar.gz
Collecting clepy (from Carp)
  Downloading clepy-0.3.23.tar.gz
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from Carp)
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.0 in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from clepy->Carp)
Requirement already satisfied (use --upgrade to upgrade): nose in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from clepy->Carp)
Requirement already satisfied (use --upgrade to upgrade): mock in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from clepy->Carp)
Installing collected packages: clepy, Carp
  Running setup.py install for clepy
  Running setup.py install for Carp
Successfully installed Carp-0.0.3 clepy-0.3.23

David-Laxers-MacBook-Pro:maxas davidlaxer$ make
cp lib/MaxAs/MaxAs.pm blib/lib/MaxAs/MaxAs.pm
cp lib/MaxAs/Cubin.pm blib/lib/MaxAs/Cubin.pm
cp lib/MaxAs/MaxAsGrammar.pm blib/lib/MaxAs/MaxAsGrammar.pm
cp bin/maxas.pl blib/script/maxas.pl
/opt/local/bin/perl5.16 -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/maxas.pl
Manifying blib/man3/MaxAs::MaxAs.3pm

David-Laxers-MacBook-Pro:maxas davidlaxer$ sudo make install
Password:
Appending installation info to /opt/local/lib/perl5/5.16.3/darwin-thread-multi-2level/perllocal.pod
David-Laxers-MacBook-Pro:maxas davidlaxer$ 

David-Laxers-MacBook-Pro:nervanagpu davidlaxer$ pip install Carp --upgrade
Requirement already up-to-date: Carp in /Users/davidlaxer/anaconda/lib/python2.7/site-packages
Requirement already up-to-date: clepy in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from Carp)
Requirement already up-to-date: jinja2 in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from Carp)
Requirement already up-to-date: decorator>=3.0 in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from clepy->Carp)
Requirement already up-to-date: nose in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from clepy->Carp)
Collecting mock (from clepy->Carp)
  Downloading mock-1.1.1.tar.gz (69kB)
    100% |████████████████████████████████| 73kB 813kB/s 
Collecting pbr>=0.11 (from mock->clepy->Carp)
  Downloading pbr-1.2.0-py2.py3-none-any.whl (83kB)
    100% |████████████████████████████████| 86kB 1.0MB/s 
Requirement already up-to-date: six>=1.7 in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from mock->clepy->Carp)
Requirement already up-to-date: funcsigs in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from mock->clepy->Carp)
Installing collected packages: pbr, mock
  Found existing installation: mock 1.0.1
    DEPRECATION: Uninstalling a distutils installed project (mock) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling mock-1.0.1:
      Successfully uninstalled mock-1.0.1
  Running setup.py install for mock
Successfully installed mock-1.1.1 pbr-1.2.0
David-Laxers-MacBook-Pro:nervanagpu davidlaxer$ pip install Dumper --upgrade
Collecting Dumper
  Downloading Dumper-1.0.4-py2.py3-none-any.whl
Installing collected packages: Dumper
Successfully installed Dumper-1.0.4
David-Laxers-MacBook-Pro:nervanagpu davidlaxer$ make all
installing maxas...
/var/folders/nj/nphdkhyj6s1dttb0pd9zb2wc0000gn/T/nervanagpu.XXXXXXXX.A9H2VpAv
Cloning into 'maxas'...
remote: Counting objects: 170, done.
remote: Total 170 (delta 0), reused 0 (delta 0), pack-reused 170
Receiving objects: 100% (170/170), 163.15 KiB | 0 bytes/s, done.
Resolving deltas: 100% (67/67), done.
Checking connectivity... done.
Checking if your kit is complete...
Looks good
Warning: prerequisite Carp 1.29 not found. We have 1.26.
Warning: prerequisite Data::Dumper 2.145 not found. We have 2.13506.
Writing Makefile for MaxAs::MaxAs
Writing MYMETA.yml and MYMETA.json
cp lib/MaxAs/MaxAs.pm blib/lib/MaxAs/MaxAs.pm
cp lib/MaxAs/Cubin.pm blib/lib/MaxAs/Cubin.pm
cp lib/MaxAs/MaxAsGrammar.pm blib/lib/MaxAs/MaxAsGrammar.pm
cp bin/maxas.pl blib/script/maxas.pl
/opt/local/bin/perl5.16 -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/maxas.pl
Manifying blib/man3/MaxAs::MaxAs.3pm
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: Can't create '/opt/local/lib/perl5/site_perl/5.16.3/MaxAs'
Do not have write permissions on '/opt/local/lib/perl5/site_perl/5.16.3/MaxAs'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 at -e line 1.
make[1]: *** [pure_site_install] Error 13
problems installing maxas
make: *** [maxas_check] Error 1
David-Laxers-MacBook-Pro:nervanagpu davidlaxer$ sudo make all
The directory '/Users/davidlaxer/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
installing maxas...
/tmp/nervanagpu.XXXXXXXX.JNGuTdEo
Cloning into 'maxas'...
remote: Counting objects: 170, done.
remote: Total 170 (delta 0), reused 0 (delta 0), pack-reused 170
Receiving objects: 100% (170/170), 163.15 KiB | 0 bytes/s, done.
Resolving deltas: 100% (67/67), done.
Checking connectivity... done.
Checking if your kit is complete...
Looks good
Warning: prerequisite Carp 1.29 not found. We have 1.26.
Warning: prerequisite Data::Dumper 2.145 not found. We have 2.13506.
Writing Makefile for MaxAs::MaxAs
Writing MYMETA.yml and MYMETA.json
cp lib/MaxAs/MaxAs.pm blib/lib/MaxAs/MaxAs.pm
cp lib/MaxAs/Cubin.pm blib/lib/MaxAs/Cubin.pm
cp lib/MaxAs/MaxAsGrammar.pm blib/lib/MaxAs/MaxAsGrammar.pm
cp bin/maxas.pl blib/script/maxas.pl
/opt/local/bin/perl5.16 -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/maxas.pl
Manifying blib/man3/MaxAs::MaxAs.3pm
Appending installation info to /opt/local/lib/perl5/5.16.3/darwin-thread-multi-2level/perllocal.pod
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
building kernel: hgemm_nn_128x128...
make: maxas.pl: No such file or directory
make: *** [nervanagpu/kernels/cubin/hgemm_nn_128x128.cubin] Error 1
David-Laxers-MacBook-Pro:nervanagpu davidlaxer$

**Comment by apark263** [comment]
Hi David,

I noticed that you are trying to install nervanagpu on a macbook pro.  I wanted to point out that nervanagpu currently only supports maxwell class gpus, so even if it gets installed, you probably will not be able to use it.

**Comment by dbl001** [comment]
Ok.

Chipset Model:	NVIDIA GeForce 9600M GT

It runs Cuda 6.5.

How about an EC2 GPU:

**Comment by scttl** [comment]
Hi David,

Unfortunately, all the GPU's Amazon currently offers through EC2 are older Kepler based models so again you wouldn't be able to use the nervanagpu backend there.
