### ISSUE TITLE
Deep Q-learning

### ISSUE THREAD

**Issue by llllaaaa** [NervanaSystems/neon#63]
I noticed that @seba-1511 implemented a Deep Q-learning cost function at  https://github.com/ZebTech/neon/tree/dqn

@scttl Could you provide official support for Deep Q-learning in the master branch?

**Comment by scttl** [comment]
Yeah this seems like something that should be easy to integrate into the main neon branch.  @seba-1511 did you want to put together a pull request for this?

**Comment by seba-1511** [comment]
Good evening,

Actually, I have an implementation for DQN and Gorila (with MPI) that works with neon. I am still polishing the code, and it does not really "fit" inside neon. (More of a side project built on top of it.) I was planning to make it public this weekend, but there are a few bugs remaining. I added @DoctorTeeth as a contributor to the repo, as he is also working on this.

Also, this DQN cost is probably wrong, an an updated version will be released. I'll post it here as soon as it works.

Séb

**Comment by DoctorTeeth** [comment]
Yeah this is something that I thought about as well: we had wanted to do "DQNs in neon", but basically the deep learning part of DQN is a pretty simple convnet with a least squares cost. You could probably put some DQN related stuff in neon, but without the rest of the code (dealing with the replay memory, dealing with ALE, etc) you're not going to have a fully functional DQN that you can train after just installing neon, and I suspect that we don't want to support that auxiliary stuff.

**Comment by nervanasys** [comment]
We can host the auxiliary stuff in a separate DQN repo.

**Comment by llllaaaa** [comment]
I think a separate DQN framework will be very useful. I hope it will allow the user to define the input data format, network structure and reward, so we can use it in applications other than game playing. @seba-1511 @DoctorTeeth Thanks for your great work.

**Comment by scttl** [comment]
closing this as a separate project/framework seems like a better approach than bolting everything into stock neon.
