### ISSUE TITLE
fprop_func of tanh activation

### ISSUE THREAD

**Issue by xiuxiazhang** [NervanaSystems/neon#66]
In neon/transforms/tanh.py
I am a little confused about fprop_func's implementation. 
Because in fproc_func it computes the derivatives.
which is  df() = 1 -f^2 . 
 61     def fprop_func(self, backend, inputs, outputs):
 62         backend.tanh(inputs, outputs)
 63         backend.multiply(outputs, outputs, inputs)
 64         backend.subtract(1.0, inputs, inputs)

I think it should be 
 61     def fprop_func(self, backend, inputs, outputs):
 62         backend.tanh(inputs, outputs)

Thanks, 
Xiuxia

**Comment by scttl** [comment]
Hi Xiuxia,

Please see my answer to your previous "issue" in #65.  That explains why things setup the way they are.
