### ISSUE TITLE
Ilya Sutskever's practical advices

### ISSUE THREAD

**Issue by seba-1511** [NervanaSystems/neon#69]
Good evening,

I was looking at ways to extract those last few percents when training a net, and I found that great post [1] from Ilya Sutskever from the beginning of the year which kind of reminded me of LeCun's practical tricks [2]. I think that it would be very helpful implement all those tricks in order to be able to reach/reproduce state of the arts. Maybe it could (should ?) be included in #62 ?And if possible, all of the tricks should be easily applicable to any dataset.

Here are the links:

[1] http://yyue.blogspot.co.uk/2015/01/a-brief-overview-of-deep-learning.html

[2] http://yann.lecun.com/exdb/publis/pdf/lecun-98b.pdf

Have a nice week,
Séb

**Comment by scttl** [comment]
Hi Séb,

Thanks for the comment.  Agreed, neon should either directly support (or make it easy to support) all the little things required to train nets well at scale, and skimming through the links I feel like we're a pretty reasonable portion of the way there.  Keep in mind a lot of this is ultimately up to the end user to ensure they have enabled these tricks and set up parameters appropriately.

As part of the refactor we'll definitely be revisiting these types of items.
