### ISSUE TITLE
AWS: No CUDA capable GPU installed. Forcing GPU=0

### ISSUE THREAD

**Issue by alexander-rakhlin** [NervanaSystems/neon#75]
Good day,

Can we expect neon to run on AWS g2.2xlarge instance, GRID K520?

I have Ubuntu 14.10, CUDA 7.0, CUDA samples okay, and nvcc is okay too:
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_22:59:02_CST_2015
Cuda compilation tools, release 7.0, V7.0.27

Still "No CUDA capable GPU installed. Forcing GPU=0", for each option
GPU=nervanagpu
GPU=cudanet

**Comment by scttl** [comment]
Hi,

AWS doesn't support newer Maxwell based GPU's, so the nervanagpu backend will not work, but cudanet should.

What was the exact syntax of the command you were trying to run?  Did you try `make -e GPU=cudanet install`?  Were you trying to run as `sudo`?

**Comment by alexander-rakhlin** [comment]
Hi,

I set in setup.cfg:
GPU=cudanet

And tried both:
sudo env “PATH=$PATH” env “LD_LIBRARY_PATH=$LD_LIBRARY_PATH” make install
and
sudo make install


I didn't try:
sudo make -e GPU=cudanet install 
neither
make -e GPU=cudanet install 

Should it work?

**Comment by scttl** [comment]
If you modified the GPU line of setup.cfg then that should perform the same functionality as `make -e GPU=cudanet` so I don't think the result will differ.

Even though `nvcc --version` appears to work when you run from the command line, it looks like the error you are reporting comes from the return value from that exact test.  In the top-level `Makefile`, the line is:
`ifneq ($(shell nvcc --version > /dev/null 2>&1; echo $$?), 0)` 

Out of curiosity what does running: `$(nvcc --version > /dev/null 2>&1; echo $?)` and `sudo $(nvcc --version > /dev/null 2>&1; echo $?)` from the command line report?

**Comment by alexander-rakhlin** [comment]
I have to wait for reasonable price to check it (something unusual goes on with AWS GPU spot instances recently, up to $6.5/hour for g2.2xlarge)

**Comment by nervanasys** [comment]
Tracking this under #80 going forward.
