### ISSUE TITLE
Create some example models of DBNs.

### ISSUE THREAD

**Issue by bibbly** [NervanaSystems/neon#76]
All the examples demonstrate MLPs or some variation thereof. There's nothing to show anybody how to use the DBN, or RBMLayer. 

In my experience, the existing examples cannot be easily modified to implement DBNs.

**Comment by fchollet** [comment]
Existing examples seem to be covering the main use cases for Neon (quite industry-flavored): RNNs, Convnets, MLPs. It could be there aren't much demand and applications for RBMs. 

Which leads to another question: why go through the effort of implementing RBMs in Neon, a library that seems geared towards use in industry? Maybe it's just my lack of expertise, but I do not know of any practical (non-research) applications of RBMs. Nor of any research application where the RBM couldn't be replaced with something simpler, for that matter.

**Comment by scttl** [comment]
Yes, we haven't had too much use for RBM's or DBN's internally as of late and thats the reason why we haven't kept the code in `rbm.py` and `dbn.py` as up to date as other model types.  After the refactor we may look to reintroduce support for these model types, but it's pretty low on the priority list.

**Comment by bibbly** [comment]
For various reasons that I won't bore you with, I have had occasion to need DBNs for large-scale image recognition tasks (in industry!). And Neon suits my needs pretty well at the moment. I would be most grateful if you guys could put up even a single example of the DBN in use - I can't for the life of me get it working!

All the best, Bibbly.

**Comment by nervanasys** [comment]
We don't have plans to currently add an example, but take a look at the latest code (v1.0.0rc1). You might find it easier.
