### ISSUE TITLE
cuda runtime error (38) : no CUDA-capable device is detected

### ISSUE THREAD

**Issue by lorefrn** [NervanaSystems/neon#77]
Hi! i've installed cutorch, but when i try to run the file main.lua an error occur:

qlua: cuda runtime error (38) : no CUDA-capable device is detected at /tmp/luarocks_cutorch-scm-1-5162/cutorch/lib/THC/THCGeneral.c:16
stack traceback:
	[C]: at 0x7fb587c61990
	[C]: at 0x7fb565797f80
	[C]: in function 'require'
	/home/lorenzo/torch/install/share/lua/5.1/cutorch/init.lua:2: in main chunk
	[C]: in function 'require'
	main.lua:8: in main chunk

What can i do?? 
Thank U
(controller: NVIDIA Corporation GM108M [GeForce 840M] (rev a2)
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04")

**Comment by lorefrn** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2013 NVIDIA Corporation
Built on Wed_Jul_17_18:36:13_PDT_2013
Cuda compilation tools, release 5.5, V5.5.0

**Comment by scttl** [comment]
Well I may be biased, but I'd recommend uninstalling torch and installing neon instead! :)

Closing as I assume you meant to post this on cutorch instead.
