### ISSUE TITLE
Add support for Kepler and older generation GPUs

### ISSUE THREAD

**Issue by nervanasys** [NervanaSystems/neon#80]

**Comment by SimoV8** [comment]
Hi, do you approximately know when older GPUs will be supported?

**Comment by nervanasys** [comment]
We are targeting a 1-2 month time frame.

**Comment by SimoV8** [comment]
Ok, thank you :)

**Comment by jjgraham** [comment]
@nervanasys has this issue been solved ?
I have a new K80 Kepler and i am having problems

[root@jupyter neon]# python /Public/neon/neon/backends/util/check_gpu.py
Found GPU(s) with compute capability: [3.7, 3.7]
3.7

When i try to run examples i get
RuntimeError: Device 0 does not have CUDA compute capability 5.0 or greater

**Comment by nervanasys** [comment]
Sorry, it is still pending. this is currently a priority item under active development. We hope to have it in this month.

**Comment by jjgraham** [comment]
@nervanasys Thanks for the quick reply !
We have a lot of K80s at UCSD and want to use neon

**Comment by nervanasys** [comment]
We'll be sure to update our progress here. Would love to hear more about your use case. Please email info@nervanasys.com

**Comment by great-thoughts** [comment]
Does neon support older GPU?

**Comment by scttl** [comment]
Kepler kernel support is now available publicly in v1.2.0 as of 85fd5c1

**Comment by rene4jazz** [comment]
Is there support for Fermi cards?
