### ISSUE TITLE
Support a mask in mini-batch in LSTM layer

### ISSUE THREAD

**Issue by avostryakov** [NervanaSystems/neon#85]
I will be great to support a mask for arbitrary sequences in mini-batches. A mask will contain ones in positions where sequences exist and zeros where not.

I mean this layer:
http://neon.nervanasys.com/docs/1.0.0rc1/generated/neon.layers.recurrent.LSTM.html#neon.layers.recurrent.LSTM

**Comment by jcoreyes** [comment]
Depending on what you're doing, using a masked cost might be enough http://neon.nervanasys.com/docs/1.0.0rc1/generated/neon.layers.layer.GeneralizedCostMask.html#neon.layers.layer.GeneralizedCostMask. 
Though I can see for some cases where you'll need a mask in the lstm layer.

**Comment by avostryakov** [comment]
Actually, I don't understand how I can use a masked cost. After LSTM layer,
I take a last hidden state and put it in a usual feedforward layer with
softmax. Only after it I have a cost function.
So, because I have sequences of different length in mini-batch I have to
mask them.

Anatoly Vostryakov,
Energy,
mailto: a.vostrjakov@gmail.com

//////

2015-09-11 22:12 GMT+03:00 John Co-Reyes <notifications@github.com>:

**Comment by sxjzwq** [comment]
I have the same question of using the masked cost. Do you have any examples of using the masked cost layer?

for example, given an image and a question with an answer sentence, both the words of question and answer will be input the LSTM step by step, however, I only want to measure the cost and errors between the generated answer words and the target (ground truth), which means I only want to calculate the cost and error only based on parts steps of the LSTMs outputs. I guess the masked cost layer will be helpful in this case. But how should I use it and where should I give the mask?

It will be really helpful if you have any examples. And please also let me know if I made any mistakes of understanding of the usage of this layer in the above example.
Thanks.

**Comment by jcoreyes** [comment]
There's an example here https://github.com/NervanaSystems/neon/blob/master/neon/data/imagecaption.py. The data layout for lstm input is (feature_size, steps * batch_size) where moving form left to right of the input tensor, you have the first step of a batch, then the second step of a batch and so on. So the mask tensor will have 1's where the sequence continues and 0 elsewhere. To use the cost mask, the dataset iterator has to return 2 elements where the 1st element is your normal input x and the 2nd element is a tuple (targets, mask).

**Comment by sxjzwq** [comment]
Thanks. I think that's what I need.

As my understanding, in the captioning case, the mask is like [1,1,1,1,1,0,0,0...] the last '1' means the end of target sentence. In the question answering case, the mask should be like [0,0,0,0,0,1,1,1,1,0,0,0,0...]. The first sequence of '0's corresponds to the given questions. All '1's corresponds answers and the last '1' is the end of answer. Then the cost function will be only applied on those steps marked as '1'.
Am I right?

Thanks.

**Comment by jcoreyes** [comment]
That's correct. Be careful with the data layout because a batch is contiguous not a sentence.

**Comment by soheilb** [comment]
I also think having a mask implementation for lstm/rnn to support varying length sequences within a batch is quite helpful. After all, one of the main advantages of using recurrent architectures is that they can handle varying length sequences...Here is the corresponding Theano example:
http://deeplearning.net/tutorial/lstm.html
