### ISSUE TITLE
3d convnet features

### ISSUE THREAD

**Issue by hyln9** [NervanaSystems/neon#88]
It seems that nervanagpu backend support 3d convolution but neon does not. Can you add these features to neon?

**Comment by apark263** [comment]
They will be added later -- in the meantime, you can follow the template of how the current Conv layers are implemented and input the 3 dimensional parameters in there.

**Comment by variousvirgil** [comment]
I see. Thanks!

**Comment by variousvirgil** [comment]
I found it's very difficult to debug when nervanagpu kernel crashed.
So I'm looking forward to the official implementation.

**Comment by scott-gray** [comment]
Seems I introduced a bug in 3d conv with some recent convolution changes.  A fix is already in and will be released soon.  We'll have better unit tests for 3d conv as well.

**Comment by scttl** [comment]
Hi, 

Just realized we forgot to close this.  Support for 3D convolution exposed at the layer level was introduced way back in da492cd4 from last October.

**Comment by hyln9** [comment]
Wow, thanks!
