### ISSUE TITLE
the MLP does not run on GPU for misterious reasons

### ISSUE THREAD

**Issue by sensus-sextus** [NervanaSystems/neon#94]
The simple script (based on neon's distribution example) with MNIST dataset fails on GTX 980 4GB.
 We run it on Ubuntu 14.04.02 OS and both graphic cards are made by Gigabyte.
Any possible set of drivers including beta versions of them does not fix this.
The output is the following
python mnist_mlp2.py                                     No handlers could be found for logger "neon.data.image"
(60000, 'train samples')
(10000, 'test samples')
Traceback (most recent call last):
  File "mnist_mlp2.py", line 151, in <module>
    mlp.fit(train_set, optimizer=optimizer, num_epochs=num_epochs, cost=cost, callbacks=callbacks)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/models/model.py", line 120, in fit
    self._epoch_fit(dataset, callbacks)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/models/model.py", line 142, in _epoch_fit
    x = self.fprop(x)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/models/model.py", line 173, in fprop
    x = l.fprop(x, inference)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/layers/layer.py", line 422, in fprop
    self.be.compound_dot(A=self.W, B=inputs, C=self.outputs)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/backends/nervanagpu.py", line 1134, in compound_dot
    kernel = _get_gemm_kernel(self.cubin_path, clss, op, size)
  File "<string>", line 2, in _get_gemm_kernel
  File "/usr/local/lib/python2.7/dist-packages/pycuda/tools.py", line 430, in context_dependent_memoize
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/backends/nervanagpu.py", line 1711, in _get_gemm_kernel
    module = _get_module(path, clss, op, size)
  File "<string>", line 2, in _get_module
  File "/usr/local/lib/python2.7/dist-packages/pycuda/tools.py", line 430, in context_dependent_memoize
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/neon-1.0.0rc1-py2.7.egg/neon/backends/nervanagpu.py", line 1703, in _get_module
    return drv.module_from_file(os.path.join(path, cubin))
pycuda._driver.RuntimeError: cuModuleLoad failed: file not found

The code is copy-pasted below.
This code works quite well on CPU (e.g. for Windows)

Thanks for help,
Dimitri 

from numpy import *
from numpy import genfromtxt
import logging
import os
import pandas as pd
from sklearn.datasets import fetch_mldata

from neon.backends import gen_backend
from neon.callbacks.callbacks import Callbacks
from neon.data import DataIterator, load_mnist
from neon.initializers import Gaussian
from neon.layers import GeneralizedCost, Affine, BatchNorm
from neon.models import Model
from neon.optimizers import GradientDescentMomentum, RMSProp
from neon.transforms import Rectlin, Logistic, Tanh, Softmax, CrossEntropyBinary, SumSquared, Misclassification
from neon.util.argparser import NeonArgparser

logger = logging.getLogger()

# parse the command line arguments
parser = NeonArgparser(__doc__)
parser.add_argument('--serialize', nargs='?', type=int,
                    default=0, const=1, metavar='N',
                    help='serialize model every N epochs')
parser.add_argument('--model_file', help='load model from pkl file')

args = parser.parse_args()

# hyperparameters
batch_size = 200
num_epochs = 100

# setup backend
be = gen_backend(backend=args.backend,
                 batch_size=batch_size,
                 rng_seed=args.rng_seed,
                 device_id=args.device_id,
                 default_dtype=args.datatype,
                 stochastic_round=False)

# load up the mnist data set
# split into train and tests sets
numclass = 10
mnist = fetch_mldata('MNIST original')

#df2.values
#mnisttest = genfromtxt('mnist_train.csv', delimiter=',')#
X_train= mnist.data[0:60000,:]
y_train= mnist.target[0:60000]

X_test= mnist.data[60000:,:]
y_test= mnist.target[60000:]
 #, (X_test, y_test), nclass = load_mnist(path=".")

print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

# setup a training set iterator
train_set = DataIterator(X_train, y_train, nclass=numclass)
# setup a validation data set iterator
valid_set = DataIterator(X_test, y_test, nclass=numclass)

# setup weight initialization function
init_norm = Gaussian(loc=0.0, scale=0.01)

# setiup model layers
layers = []
layers.append(Affine(nout=80, init=init_norm, activation=Tanh()))
layers.append(Affine(nout=64, init=init_norm, activation=Tanh()))
#layers.append(Affine(nout=64, init=init_norm, activation=Tanh()))
#layers.append(Affine(nout=64, init=init_norm, activation=Tanh()))
#layers.append(Affine(nout=64, init=init_norm, activation=Tanh()))
#layers.append(Affine(nout=64, init=init_norm, activation=Tanh()))
layers.append(Affine(nout=numclass, init=init_norm, activation=Softmax()))
#shortcut=True
# setup cost function as CrossEntropy
cost = GeneralizedCost(costfunc=SumSquared())

# setup optimizer
llrate= 1e-3
optimizer = GradientDescentMomentum(llrate, momentum_coef=0.7, stochastic_round=args.rounding)
#optimizer =RMSProp(stochastic_round=False, decay_rate=0.95, learning_rate=llrate, epsilon=1e-06, clip_gradients=False, gradient_limit=5, name='rmsprop')
# initialize model object
mlp = Model(layers=layers)
if args.model_file:
    assert os.path.exists(args.model_file), '%s not found' % args.model_file
    logger.info('loading initial model state from %s' % args.model_file)
    mlp.load_weights(args.model_file)

# setup standard fit callbacks
callbacks = Callbacks(mlp, train_set, output_file=args.output_file,
                      progress_bar=args.progress_bar)

# add a callback ot calculate

if args.validation_freq:
    # setup validation trial callbacks
    callbacks.add_validation_callback(valid_set, args.validation_freq)

if args.serialize > 0:
    # add callback for saving checkpoint file
    # every args.serialize epchs
    checkpoint_schedule = args.serialize
    checkpoint_model_path = args.save_path
    callbacks.add_serialize_callback(checkpoint_schedule, checkpoint_model_path)

# run fit
mlp.fit(train_set, optimizer=optimizer, num_epochs=num_epochs, cost=cost, callbacks=callbacks)

print('Misclassification error = %.1f%%' % (mlp.eval(valid_set, metric=Misclassification())*100))

**Comment by apark263** [comment]
Try getting the latest commit and doing a `make clean` and `make`.  Build issues should be fixed.

**Comment by vsov** [comment]
Unfortunately, that wasn't a build issue. I have pulled latest master, it's being recompiling everything right now, but it hardly will fix the issue.

**Comment by apark263** [comment]
>pycuda._driver.RuntimeError: cuModuleLoad failed: file not found

This message indicates that the kernel wasn't built.

**Comment by vsov** [comment]
Nope, we've got the same error... Everything was rebuilt from the scratch, make test says that everything is ok...

**Comment by vsov** [comment]
I have resolved the issue by removing all components (including maxas and nervanagpu) and installing everything from the scratch. Without that some files in neon were never replaced by newer versions, I don't know why.
