### ISSUE TITLE
Can't create a tensor from an existing tensor

### ISSUE THREAD

**Issue by seba-1511** [NervanaSystems/neon#96]
Good evening,

I am not sure whether this fits in neon or NervanaGPU, so I'll post it here. The problem is that the following code raises an error:

```python
be = gen_backend(backend='gpu')
b = be.array(np.array([1, 2, 3]))
a = be.array(b)
# AssertionError: nervanagpu.py:378
```

I think that in such a case, a should be an additional reference to the value in b. The use case is that when creating a DataIterator, one could pass an array of tensors as X, and this would avoid the cpu-gpu bottleneck. I could work on this issue, as it would greatly speed up DQN. 

On a side note I also find strange the `be.array(np.array([1, 2, 3]))`, but that's less problematic. (I think fixing that should also be relatively easy, as omitting the np.array triggers an error because it is used for the shape of the tensor.)

Best,
Séb

**Comment by jcoreyes** [comment]
How big are these array of tensors? You might still get a bottleneck using a gpu array of gpu tensors vs a cpu array of gpu tensors depending on how you access them. Is using b = np.array([tens1, tens2]) too slow?

**Comment by ursk** [comment]
If you are trying to create a reference to `b` without copying any data, why not just 
```b = a```
The be.array() function, per our documentation, "converts a numpy array to a GPUTensor".

**Comment by seba-1511** [comment]
So my specific use case is for DQN. At every step of the game I get a new image vector on which I need to make a single prediction. Then in a later stage, all those images are used to create the training data for the function approximator. (this requires two more transfers) As anyway the data is on the device the first time, I should keep it there.

What I think would be nice is to be able to create a DataIterator from a GPU/CPU array of Tensors. Maybe the easiest is to write a custom iterator, based on the DataIterator implementation.

**Comment by apark263** [comment]
The right way to handle this is to allocate a batch GPU tensor that is going to be used for the function approximator.  When you get the image vector from the single prediction, store it in one of the slots of the batch tensor.  You can predict on that single slice, and then perform the training when the batch tensor is full.

**Comment by tambetm** [comment]
@seba-1511, do you plan to keep entire replay memory in GPU? Default replay memory size is 1000000 in DeepMind's code. Assuming you can keep every screen frame in memory only once, you would need 1000000 * 84 * 84 * 2 (assuming 16-bit) = 13GB, which is above even Titan X.

Also you would need to randomly sample from replay memory for training, so the technique suggested by @apark263 wouldn't work. Can you create a tensor as non-contiguous slice of another tensor? And efficiently apply operators to it?

I just started working on my own implementation of DQN using Neon, but currently I'm striving for simplicity, rather than performance. Probably it will take quite some time to debug it.

**Comment by seba-1511** [comment]
@tambetm currently my implementation takes 0.12 seconds (on a 980) to make a a prediction on a single image, which is obviously unpractical. About the replay memory size, this is indeed an issue but my focus is primarily on having a working implementation rather than replicating DeepMind's results. 

@apark263 That's what I think I will end up doing, in a custom DataIterator class. Thank you.
