### ISSUE TITLE
Predict and DataIterator

### ISSUE THREAD

**Issue by rushter** [NervanaSystems/neon#97]
If i'm passing `DataIterator` to `predict()` method without `y` vector then this method fails.
```
test = DataIterator(X=X_test.values,  nclass=nclass)
...
mlp.predict(test)
``` 
``` 
  File "dl.py", line 297, in deep_learning
    predictions = mlp.predict(test).get()
  File "..../neon/models/model.py", line 243, in predict
    Ypred = self.be.empty((dataset.ndata, outsize))
  File "..../neon/backends/nervanacpu.py", line 591, in empty
    ary=np.zeros(shape, dtype),
TypeError: an integer is required
```
A problematic line:
https://github.com/NervanaSystems/neon/blob/master/neon/models/model.py#L229

I thought it should be equals `dataset.nclass`, but there is no such property in `DataIterator` object.

**Comment by nervanasys** [comment]
You could try the renamed get_output function that is clearer: https://github.com/NervanaSystems/neon/blob/master/neon/models/model.py#L212

It might be better for you to implement a function similar to get_outputs on your own for this use case as DataIterator currently assumes missing targets refers to building an autoencoder.
