### ISSUE TITLE
Cannot use fprop for MLP networks

### ISSUE THREAD

**Issue by sensus-sextus** [NervanaSystems/neon#98]
Dear All, 
I'm truing to get predictions from the trained network of the example "mnist_mlp.py".
But for the code like: 

xx= be.array(X_test)
prdc= mlp.fprop(xx)

it produces strange errors like

  File "D:/Dima/Python/neonka/bloo_neon5.py", line 157, in <module>
    prdc= mlp.fprop(xx)

  File "D:\Python27\lib\site-packages\neon-1.0.0rc1-py2.7.egg\neon\models\model.py", line 173, in fprop
    x = l.fprop(x, inference)

  File "D:\Python27\lib\site-packages\neon-1.0.0rc1-py2.7.egg\neon\layers\layer.py", line 422, in fprop
    self.be.compound_dot(A=self.W, B=inputs, C=self.outputs)

  File "D:\Python27\lib\site-packages\neon-1.0.0rc1-py2.7.egg\neon\backends\nervanacpu.py", line 763, in compound_dot
    assert B.shape[1] == C.shape[1]

AssertionError

I see no way to fix it, 
thanks for any help

**Comment by apark263** [comment]
the shape of your inputs are probably incompatible with your weights

**Comment by sensus-sextus** [comment]
This is not the case. I've tryed to use inputs from the training or testing set (that were succesfully used to train/test the net) but it does not help!

**Comment by apark263** [comment]
make sure that the batch size of your input is the same as the batch size when you trained the network.  you can zero-pad if you need to.

**Comment by sensus-sextus** [comment]
How can I control batch size of the inputs? 
I trieed making second dimension of the input array equal to "batch_size "  parameter of the network but it does not remedy the situation?!

**Comment by apark263** [comment]
it's impossible to tell without seeing your code

**Comment by sensus-sextus** [comment]
now it works if the input have exactly batch_size examples, thank you!
is there any way to get prediction if I have different number of input vectors?

**Comment by apark263** [comment]
so before when you said it still didn't work you were just using approximately batch_size examples?

if you have more input vectors than batch_size, use multiple batches.  If you have fewer (say K), then zero pad the input buffer and only look at the first K columns of the output

**Comment by sensus-sextus** [comment]
there was an indexing error while creating sub-arrays.

thank you very much for explanation
