### ISSUE TITLE
image_caption.py: pycuda.driver.LogicError after multi-bleu

### ISSUE THREAD

**Issue by h10r** [NervanaSystems/neon#99]
Hej,

thank you for providing such a great framework! Unfortunately, I'm having some trouble getting started.

I'm trying to run the `image_caption.py` example on `flickr8k`. 

After Epoch 9 and executing the `multi-bleu` perl script, it fails with an exception:

> Exception pycuda._driver.LogicError: 'context::detach failed: invalid device context - cannot detach from invalid context' in <bound method NervanaGPU.__del__ of <neon.backends.nervanagpu.NervanaGPU object at 0x7f18887353d0>> ignored

Any idea what I might be doing wrong / how to fix this?

Kind regards and all the best from Amsterdam,
Hendrik

**Comment by apark263** [comment]
This is a clean up error that can be disregarded -- a fix is on the way.
